### ISSUE TITLE
SyntaxErrors occur when running code line-by-line but not as a script.

### ISSUE THREAD

**Issue by hillarysanders** [yhat/rodeo#100]
When running code line-by-line (command-shift), 'SyntaxError: unexpected EOF while parsing' errors occur at the start of function definitions.

However, if you paste the same code into another python interpreter, it works fine, and if you press the 'run script' button, all of the functions are read in properly. If the code is run with command-shift over the entire function definition, no parsing error occurs.

thanks!

**Comment by glamp** [comment]
fixed in latest
