### ISSUE TITLE
feature request: Autocomplete doesn't work in the console

### ISSUE THREAD

**Issue by hillarysanders** [yhat/rodeo#101]
Could it? :D :dancer:

**Comment by hillarysanders** [comment]
That is to say - your options (e.g. 'print' when you type 'prin') are printed to the screen, but you're not able to select the autocompleted code you want (e.g. as you can in RStudio). That'd be sweeeet.

**Comment by glamp** [comment]
cdb6d14a2a41c6e2a2854b64c72154c6879d6271
