### ISSUE TITLE
Listening rodeo to port

### ISSUE THREAD

**Issue by praveen766** [yhat/rodeo#105]
Hi 
Is there a way to listen Rodeo to a host ip  and port rather than the local host, so that we can open rodeo in any browser  by typing url http://hostname:portnumber rather than http://localhost:5000 (something like R studio server or listening ipython to a host ip)

**Comment by roshannair** [comment]
Hi Praveen,

Use the host and port arguments to the rodeo command

for eg: rodeo . --host=0.0.0.0 --port 5000 --no-browser

Roshan

**Comment by roshannair** [comment]
Correction,

rodeo . --host=0.0.0.0 --port*=*5000 --no-browser
