### ISSUE TITLE
⌘ + enter and ↑ in the terminal not working

### ISSUE THREAD

**Issue by jdrudolph** [yhat/rodeo#113]
On a fresh `rodeo` instance I enter the following code in the editor.

```python
print('hello world')
```

Then I send it to the terminal with ⌘ + enter and it executes as expected.

Now I wan't to do some interactive changes to the previous line but the ↑ has no effect.

**Comment by glamp** [comment]
Yup definitely a bug. I'll take a look.

**Comment by tom-christie** [comment]
Perhaps related, but when I select multiple lines and hit ⌘ + enter, the cursor goes to a seemingly random line. For example, after executing lines 40-45 at once by selecting and pushing ⌘ + enter, the cursor will go to line 30.
