### ISSUE TITLE
Upon installing and running 'rodeo .', I receive error "Abort trap: 6"

### ISSUE THREAD

**Issue by rforgione** [yhat/rodeo#115]
![screen shot 2015-06-26 at 11 01 32 am](https://cloud.githubusercontent.com/assets/5572997/8380275/d9fa3164-1bf2-11e5-9a18-2353497e3fbd.png)

When running, I receive the error "Abort trap: 6". The application opens, but the kernel is unresponsive when I try to run code in the Python REPL; for example:

![screen shot 2015-06-26 at 11 04 20 am](https://cloud.githubusercontent.com/assets/5572997/8380324/20bbf48e-1bf3-11e5-95dd-721790bf2dca.png)

**Comment by glamp** [comment]
Oh man this sounds hairy. I'm really sorry you're getting this error. Unfortunately I don't think this has anything to do with Rodeo--maybe IPython or your Python distribution? Maybe try posting on one of those Issues lists.
