### ISSUE TITLE
Why asynchronous terminal? Syncronous better?

### ISSUE THREAD

**Issue by nickeubank** [yhat/rodeo#116]
Hi All!

Very excited about Rodeo, but have run into one aspect of the interface I don't really like. Is there a reason the terminal is asynchronous (by which I mean, the terminal prompt advances even if the python kernel is still working on last command)? 

I find it quite disconcerting -- most interactive programs will hold the cursor until the kernel finishes the last task it was given. I keep finding myself in a situation where either (a) I get very confused I'm not getting output back (this, obviously, I now understand, but hard for new users), or (b) moving forward in code several lines then getting an error from several lines back popping up. 

Thanks!

**Comment by glamp** [comment]
I suppose there's no real reason except that it was easiest to build this way. I do agree though, it's straight when you compare it to the way a regular terminal/repr works.

It should be easy enough to add. Maybe to start we can make it an optional config? If you'd be up for this, would you be willing to test it out?

**Comment by nickeubank** [comment]
Happy to test it, not sure I have the knowledge of this software to
contribute it, unless you want to do a little hand holding.
