### ISSUE TITLE
Arrays tab

### ISSUE THREAD

**Issue by bendichter** [yhat/rodeo#117]
Hi,

I love what the rodeo team has done so far! Coming from matlab (I know, I know) it would be really helpful if there were a tab like matlab's workspace window. This would be like the current "Data Frames" tab but would list the np.arrays that are currently defined and their shape, data type, and values if the shape is small. It might be helpful to also have other data-ish variables like strings, lists, dictionaries... in fact it would be even better if you could define what types you wanted in there. As a start though, np.arrays would be most useful. IMHO this would be even more useful than the Data Frames tab- I have never had to keep track of more than a few df's at a time, whereas I might have dozens of np.arrays.

I could try to implement this myself, although I'm not very experienced..

**Comment by glamp** [comment]
Yes. This will be in the next release (~1-2 weeks). If you're interested, I can include you in the beta. Let me know--greg@yhathq.com.

**Comment by glamp** [comment]
added
