### ISSUE TITLE
Ability to kill running command

### ISSUE THREAD

**Issue by kumarsameer** [yhat/rodeo#120]
Maybe because of asynchronous nature, its waiting for the command to finish and then show the entire output at one go.

In my case, it kills the whole purpose of the output, as the output is the error/accuracy reporting of machine learning model while it was running.

Also, how do you kill the running command ?

**Comment by kumarsameer** [comment]
I killed the command from the linux terminal, and now rodeo doesn't give output of any command.

**Comment by glamp** [comment]
Right now there isn't a way to do that :frowning: but it would be a good feature to add.

**Comment by AdrianoW** [comment]
Yeap, that is definitely a needed feature. Maybe an indicator over the console showing the running kernels with the time and a X to kill them.

**Comment by glamp** [comment]
good idea. i will add to the TODO

**Comment by glamp** [comment]
done in 1.2
8314d79604c17faf40e506467c6b5a3b5a2308f3
