### ISSUE TITLE
Can't start rodeo on Mac.

### ISSUE THREAD

**Issue by theyaa** [yhat/rodeo#121]
I have installed rodeo using "sudo pip install rodeo". Now when I try "rodeo ." I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 2944, in <module>
    
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 563, in _build_master
    # Find the best distribution and add it to the map
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 576, in _build_from_requirements
    raise DistributionNotFound(req)
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 755, in resolve
    if search_path is None:
pkg_resources.DistributionNotFound: simplegeneric>0.8

When I type pip list I see that I have simplegeneric: simplegeneric (0.8.1)

**Comment by andreabedini** [comment]
@theyaa make sure your python installation isn't broken, perhaps use a [virtualenv](https://virtualenv.pypa.io/en/latest/) to install rodeo.

**Comment by theyaa** [comment]
@andreabedini my python installation is not broken as I use PyCharm for my python development. I tried to re-install rodeo and then start it again and here are the output from both the re-install and re-run commands.

sudo pip install rodeo
Password:
Requirement already satisfied (use --upgrade to upgrade): rodeo in /Library/Python/2.7/site-packages/rodeo-0.4.3-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): ipython>=3.0.0 in /Library/Python/2.7/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.10.1 in /Library/Python/2.7/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): docopt in /Library/Python/2.7/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /Library/Python/2.7/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): mistune in /Library/Python/2.7/site-packages (from rodeo)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from Flask>=0.10.1->rodeo)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Library/Python/2.7/site-packages (from Flask>=0.10.1->rodeo)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from Flask>=0.10.1->rodeo)
Cleaning up...
TMatti-Mac:~ tmatti$ sudo rodeo
Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 2944, in <module>
    
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 563, in _build_master
    # Find the best distribution and add it to the map
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 576, in _build_from_requirements
    raise DistributionNotFound(req)
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 755, in resolve
    if search_path is None:
pkg_resources.DistributionNotFound: simplegeneric>0.8


Is it possible that rodeo does not work on python 2.7?

**Comment by glamp** [comment]
no

**Comment by theyaa** [comment]
@glamp I sent you an email to request the beta version.

**Comment by andreabedini** [comment]
@theyaa I didn't mean to come across as offensive :) there's lots of broken python installations out there!

**Comment by andreabedini** [comment]
it seems that simplegeneric is a dependency of ipython, and pip hasn't installed. perhaps try installing it manually `pip install simplegeneric`.
