### ISSUE TITLE
Hidden dependencies on jupyter_client and ipykernel?

### ISSUE THREAD

**Issue by rfilmyer** [yhat/rodeo#122]
I just installed rodeo, but wasn't able to get it working until I installed 2 extra auxiliary packages, `jupyter_client` and `ipykernel`, from pip. Shouldn't this be listed in the package dependencies, or is this some shenanigans with other modules in pip dropping dependencies?

Additionally, if `ipykernel` doesn't exist, or if Kernel.__init__() fails in any way, the command line program fails silently and is nonresponsive while it is stuck on the while loop checking for the config file's creation. (let me know if this should be a separate issue)

**Comment by andy47** [comment]
+1 for this. Thanks for the pointer about `jupyter_client` and `ipykernel`. I suspect this is caused by the latest changes in iPython 4.0. It might just be easier to pin a specific version number to dependent modules in `setup.py`

**Comment by kikohs** [comment]
Same issue, here thanks for the fix @rfilmyer

**Comment by glamp** [comment]
no longer a hidden dependency ([see here](http://rodeo.yhat.com/docs/#prerequisites)) so i'm going to close

**Comment by AndreMiras** [comment]
Any reason for not including "ipykernel" in "install_requires"?
That way installing rodeo would be as simple as just "pip install rodeo" without having to dig for documentation prerequisites.

**Comment by glamp** [comment]
going forward, Rodeo won't be distributed on PyPi so not really relevant anymore

**Comment by psychemedia** [comment]
@glamp "going forward, Rodeo won't be distributed on PyPi so not really relevant anymore"

So what is the plan for Rodeo in terms of availability and distribution?

FWIW, while Rodeo is available on pip, I think it would be handy if it installed the jupyter requirement, rather than put people off with it not finding it and it not working...?
