### ISSUE TITLE
Links to css and js files in /static/ aren't playing nice with reverse proxies

### ISSUE THREAD

**Issue by rfilmyer** [yhat/rodeo#123]
I'm running a very simple reverse proxy through nginx so I don't have to put rodeo on my root (and have some authentication). Unfortunately, I'm unable to load anything in `/static/`, because all of the links are to root-relative, rather than directory-relative paths. For example, here is the `<head>` tag of the page:

```
<head>
    <meta charset="utf-8" />
    <title>Rodeo</title>
    <meta name="Description" content="Rodeo | Data Science IDE"/>
    <link rel="shortcut icon" href=""/>
    <link href="/static/css/bootstrap.yeti.css" rel="stylesheet">
    <link href="/static/css/console.css" rel="stylesheet">
    <link href="/static/css/jquery.dataTables.css" rel="stylesheet">
    <link href="/static/css/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/static/css/jquery.splitter.css" rel="stylesheet"/>
    <link href="/static/css/styles.css" rel="stylesheet"/>
</head>
```

Because the links are e.g. `href="/static/css/console.css"`, rodeo looks for the file in my root directory, instead of `href="static/css/console.css"`, where it would be looking in my `/rodeo/` folder.

My nginx config is just
```
location /rodeo {
                 proxy_pass http://localhost:8789/;
                 auth_basic "Restricted Access";
                 auth_basic_user_file rodeo_htaccess;
     
         }
```

**Comment by rfilmyer** [comment]
If other people run into this problem, I was able to hack together a temporary solution by redirecting everything in <domain name>/static/ to rodeo. Obviously a very unpleasant solution but it works for me for now.

```
location /static {
                 proxy_pass http://localhost:8789/static;
                 auth_basic "Restricted Access";
                 auth_basic_user_file rodeo_htaccess;

         }
```

**Comment by rfilmyer** [comment]
Actually, it's a bit more complicated than that, since jquery will POST to the root directory as well whenever you (for example) type a command

**Comment by glamp** [comment]
resolved in latest
