### ISSUE TITLE
Display variables

### ISSUE THREAD

**Issue by sho-87** [yhat/rodeo#126]
Thinking about migrating over to rodeo from spyder because 1) it doesnt play well with windows 10 and 2) its fairly bloated

Are there any plans to display variables/structures other than dataframes in the right hand panel? Sometimes my data isn't in a dataframe (e.g. if I'm programming a full script and not interactively working with data analysis) but I'd still like to be able to see everything that I'm currently working with

**Comment by glamp** [comment]
Yes. This will be in the next release (~1-2 weeks). If you're interested, I can include you in the beta. Let me know--greg@yhathq.com.

**Comment by glamp** [comment]
added some in latest
