### ISSUE TITLE
ANSI encode output

### ISSUE THREAD

**Issue by glamp** [yhat/rodeo#13]
```
>>> raise Exception("FOO")
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-47-65402804b38d> in <module>()
----> 1 raise Exception("FOO")

Exception: FOO
```

**Comment by ogrisel** [comment]
Can you describe what is the problem here? What do you expect this to return instead?

**Comment by glamp** [comment]
Just the colors

**Comment by JanSchulz** [comment]
sending `%colors NoColor` after kernel startup makes the tracebacks readable... I had the same problem: https://github.com/JanSchulz/knitpy/blob/master/knitpy/engines.py#L38 and https://github.com/JanSchulz/knitpy/blob/master/knitpy/knitpy.py#L611

**Comment by glamp** [comment]
b7854ab488e3eb8eed82718347e202b9d95fcfb8
