### ISSUE TITLE
Using with Anaconda environments

### ISSUE THREAD

**Issue by tlnagy** [yhat/rodeo#132]
I just installed Rodeo 1.0.0 on OS X 10.11 via the installer and I'm getting the "Bad news! Rodeo can't start" error. I use Anaconda for managing my python environments and I was wondering how I could set it up to work with rodeo. 

I have jupyter and ipython installed in my root Anaconda environment:

```
conda list | grep jupyter
jupyter                   1.0.0                    py34_0
jupyter_client            4.1.1                    py34_0
jupyter_console           4.0.3                    py34_0
jupyter_core              4.0.6                    py34_0
```
Also running 
```
python -c "import IPython; import jupyter_client"
```
works fine. Is there a way to check which python interpreter Rodeo is using? Is there a way to get it to see virtualenvs?

**Comment by perrygeo** [comment]
+1 - it would be great to be able to switch runtime environments with Rodeo desktop. Most Python users these days have a virtualenv or conda env per project and not being able to use the custom env is a deal breaker.

For now it looks like the workaround is just to use the browser version and `pip install rodeo ipykernel jupyter_client` within your virtualenv.

**Comment by nbara** [comment]
Hey, I also use anaconda and Rodeo Desktop is working fine.

However you will need to change 'Preferences --> Default Python Command' to 
'/Users/yourusername/anaconda/bin/python'

Or whatever path your anaconda distro is located. 

Hope it helps

**Comment by kevindavenport** [comment]
You can set anaconda environments like so:
/Users/{username}/anaconda/envs/py27/bin/python
/Users/{username}/anaconda/envs/py35/bin/python
/Users/{username}/anaconda


http://rodeo.yhat.com/docs/

**Comment by coristig** [comment]
Multiple envs / paths is possible as of 1.2.1, closing
