### ISSUE TITLE
Rodeo desktop: the future

### ISSUE THREAD

**Issue by sho-87** [yhat/rodeo#133]
very happy to see the desktop release of rodeo! 

I like using Rstudio when I have to use R, and its nice to see that Python now has something similar. There are still some features missing. What are your future plans for rodeo? Is there a roadmap or a wishlist?

**Comment by yassineAlouini** [comment]
I am interested in the same things as @sho-87, would it be possible to add a road-map? 

Thanks in advance :smile:.

**Comment by nbara** [comment]
+1

**Comment by seantma** [comment]
+1 :)

**Comment by glamp** [comment]
You can see roadmap info (and more!) here: http://discuss.yhat.com/
