### ISSUE TITLE
Stuck on "Python is still starting up" for a while on Windows 7

### ISSUE THREAD

**Issue by zakahmad** [yhat/rodeo#134]
I tried both 32-bit and 64-bit Win 7 installations. After launching Rodeo and waiting for more than an hour I still get the following message in the console when I try anything:

Could not execute command. Python is still starting up. This should only take another couple seconds.

I uninstalled 64-bit, installed 32-bit version and got the same message.
Under Preferences -> General, I changed the Default Python Command to "C:\Python27\python.exe" and also tried "C:\Python27" (output of os.path.dirname(sys.executable) is "C:\\Python27"). None fixed the issue even after restarting Rodeo.

I'm not if there's more I can do on my end to make sure it's not my python installation that's rogue.

**Comment by olivierfriard** [comment]
This problem is also present on Debian 8.2 64 with v. 0.3.16.
Tried with /usr/bin/python and /usr/bin/python3.
No way to get out of "Could not execute command. Python is still starting up. This should only take another couple seconds."

**Comment by FilipMiletic** [comment]
I have the same problem on Windows 10 x64 running Python 3.5 only! :(

**Comment by PranY** [comment]
same problem with windows 7 x64

**Comment by gamegoofs2** [comment]
I'm getting the same thing. Windows 8/Python 3.5 restarted Rodeo a couple times and still the same thing.

**Comment by gython1** [comment]
Same here, win 7 x64 with python 3.5

**Comment by glamp** [comment]
@PranY @olivierfriard what version of python?

**Comment by glamp** [comment]
@zakahmad @olivierfriard @FilipMiletic @PranY @gython1 @gamegoofs2  Just to be sure this isn't the issue, can you try re-installing/upgrading `jupyter`, `matplotlib`, and `pandas`?

**Comment by keberwein** [comment]
The above suggestion worked for me. I'm running Anaconda on OSX with a custom location set in my Rodeo prefs "/usr/local/bin/Python3"

I did a re-install of the jupyterhub, matplotlib and pandas using:
`pip install --upgrade --force-reinstall <package_name>`

**Comment by ottocapo** [comment]
Same problem here on Windows 7. Did anybody find a way to fix this issue?

**Comment by peeter-t2** [comment]
Maybe you could add a note to follow the installation instructions also onto the download page? Otherwise just clicking the .exe is too tempting and may lead to slight frustration.

Installing jupyter+matplotlib+pandas fixed it. Matplotlib needs Visual Studio too, it seems. The easiest way to install matplotlib was by downloading and installing Anaconda (see instructions).
Great work on the software btw, thanks for the effort!

**Comment by ottocapo** [comment]
Absolutely. I forgot to comment but I got it to work after installing Anaconda. My bad.
Thanks to the developers!

**Comment by coristig** [comment]
This is fixed in 1.3.0.  The issue was with python paths having spaces in them.

Closing.
