### ISSUE TITLE
"Could not execute command. Python is still starting up. This should only take another couple seconds."

### ISSUE THREAD

**Issue by Alexander-Minyushkin** [yhat/rodeo#136]
I got this message for more then 5 minutes trying to execute something in command line.

Rodeo v1.0.2, Windows 7, 64 bit, Intel i3-3210, 8GB RAM

**Comment by hugo-pires** [comment]
I have the same problem

**Comment by levchik** [comment]
Same here: Mac OS X 10.10.4, Rodeo 1.0.2

I'm using /usr/local/bin/python3 as my "Default Python Command"

**Comment by oag335** [comment]
I have had this issue as well.  Windows 10, 64bit, Rodeo v1.0.0.  Running Python 2.7.8, (64-bit) and Anaconda 2.1.0

**Comment by keberwein** [comment]
I had the same problem on OSX. Reinstalling `jupyter`, `matplotlib`, and `pandas` solved this for me.
`pip install --upgrade --force-reinstall <package_name>`

Note: I'm using Python3 in Anaconda with a a default python command set in Rodeo. `/usr/local/bin/python3`

**Comment by jcbritobr** [comment]
None of this worked for me. win 8.1 here. :(

**Comment by phillipboy07** [comment]
I was having the issue as well, when I attempted to get Rodeo to work in Ubuntu. I followed @keberwein instructions, but the issue still existed. I clicked on View and selected "Toggle Dev Tools" and noticed there were some errors with npm modules. After I installed the missing modules, Python was working properly within Rodeo.

**Comment by oliviac12** [comment]
@phillipboy07 how can you find out the errors in Toggle Dev Tools. 
I am using OS X and I am having the same issue

**Comment by phamkhactuy** [comment]
I have same proplem. Are install Python before?

**Comment by phillipboy07** [comment]
You should see some errors within the Dev Tool display, that shows up.

**Comment by phillipboy07** [comment]
Python (2.7.6) was already installed since I'm running Ubuntu 14.04

**Comment by glamp** [comment]
no longer in Rodeo
