### ISSUE TITLE
Copy/paste error in windows IDE v1.0.2

### ISSUE THREAD

**Issue by jkort** [yhat/rodeo#140]
Editor copy/paste throws a javascript error - Menu.sendActionToFirstResponder is not a function under Win7 x64

**Comment by gregroberts** [comment]
Also getting this. ctrl+c within the editor does nothing, selecting copy from the edit menu throws the error.

**Comment by glamp** [comment]
Possibly related: https://github.com/atom/atom/issues/6587

**Comment by Fernerkundung** [comment]
Strg+V to paste data from the clipboard *into* the editor works for me.

This error also occurs when using edit menu -> paste.
