### ISSUE TITLE
Resize of code window still clips the content on Mac OS X

### ISSUE THREAD

**Issue by aullrich2013** [yhat/rodeo#141]
![screen shot 2015-10-17 at 6 56 44 am](https://cloud.githubusercontent.com/assets/4734283/10558627/59e7080a-749c-11e5-9d79-affeb3684e20.png)

I'm using 10.11 and Rodeo 1.0.2

Note that resizing the overall window then caused it to rerender properly.

**Comment by glamp** [comment]
Known issue. Working on it! I'll let you know when it's fixed.

I think the workaround for now is to adjust your windows, then hit refresh (cmd + R).

**Comment by glamp** [comment]
Fixed in 1.2
