### ISSUE TITLE
Get "[ERROR]: Result from code execution was null" on starting fresh Rodeo on Windows x64

### ISSUE THREAD

**Issue by samvrlewis** [yhat/rodeo#142]
I download Rodeo-win32-x64.exe on my 64 bit Windows 7 machine, installed and then started Rodeo.

I get the IDE view and everything seems to be functional but when I input anything into the console, I don't get anything returned.

Opening dev tools, I see this in the console:

![rodeo](https://cloud.githubusercontent.com/assets/3880246/10633060/944b3024-782b-11e5-9cee-080e75074111.png)

Have tried installing and reinstalling but face the same issue. Would be happy to try and fix if someone could point me in the right direction.

**Comment by glamp** [comment]
Yikes that's an oooogly one. I really have no idea what's going on. Email me greg at yhathq.com and we can setup a screenshare to debug. Thanks!

**Comment by rukku** [comment]
Having this error as well. Also on 64-bit Windows 7.

**Comment by rukku** [comment]
Had the same problem. Fixed it by installing Jupyter. Can you try it @samvrlewis?

@glamp Is there a way to bundle Jupyter with it? Or at least inform people that Rodeo needs Jupyter to work. People usually expect things just to work.
