### ISSUE TITLE
tab autocomplete doesn't work on Ubuntu 14.04 Chrome 

### ISSUE THREAD

**Issue by lennondu** [yhat/rodeo#143]
When I use tab, it shows a blank line in terminal.

**Comment by glamp** [comment]
Which version are you running?

**Comment by lennondu** [comment]
rodeo 0.4.4

**Comment by glamp** [comment]
Try the newest version (1.0.x)

**Comment by lennondu** [comment]
I download rodeo 1.0 linux_64bit from yhat. But I can't install it...
