### ISSUE TITLE
JS error starting Rodeo on OS X Yosemite

### ISSUE THREAD

**Issue by elyase** [yhat/rodeo#145]
I am getting the following error when I start rodeo:

![screen shot 2015-10-28 at 13 33 51](https://cloud.githubusercontent.com/assets/1175888/10788567/a5ff5aa0-7d78-11e5-8942-8cfe3cac0361.png)

Here is the text:

```
A JavaScript error occured in the main process

Uncaught Exception:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.getRC (/Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeohelpers.js:22:15)
    at EventEmitter.<anonymous> (/Applications/Rodeo.app/Contents/Resources/app.asar/src/main.js:50:22)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by glamp** [comment]
Yikes that's an oooogly one. 

What happens if you do this:

```
$ cat ~/.rodeorc
$ cat ~/.rodeoprofile
```

**Comment by elyase** [comment]
`~/.rodeorc` is empty and `~/.rodeoprofile` doesn't exist.

**Comment by glamp** [comment]
ok, try this and let me know what happens:

```
$ echo "{}" > ~/.rodeorc
```

**Comment by elyase** [comment]
Now everything works ok. Thanks a lot and feel free to close.

**Comment by glamp** [comment]
Not a problem. Thanks for submitting the issue!
