### ISSUE TITLE
Rodeo freezes, turning all white

### ISSUE THREAD

**Issue by AdrianoW** [yhat/rodeo#148]
Sometimes Rodeo freezes, becoming an empty white screen, loosing all information. 

I could not map exactly what triggers the problem, but it simply turns white. Probably it is related to the browser and its usage. Once it happens that Rodeo's window showed a popup content from my browser, overwriting the regular boxes.

**Comment by AdrianoW** [comment]
![image](https://cloud.githubusercontent.com/assets/933395/10950076/350ae9cc-831d-11e5-907a-a8250310c517.png)

Example of white screen

**Comment by glamp** [comment]
can you toggle dev tools and inspect the console output?  (View > Toggle Dev Tools)

**Comment by AdrianoW** [comment]
Nope.

Basically it freezes all operations. The menus work but they the commands
don't have any effect.

Today it happened because I have opened a big csv file and started to check
the information. In a long line it stopped and then turned white.

2015-11-04 18:01 GMT-02:00 Greg Lamp <notifications@github.com>:

**Comment by coristig** [comment]
@AdrianoW, can you download the latest version of Rodeo (1.3.0) and see if this is resolved?

**Comment by TakenPilot** [comment]
[Rodeo 2.0.0](https://github.com/yhat/rodeo/releases/tag/v2.0.0) contains the stability fixes for this issue as well.
