### ISSUE TITLE
Install `pyzmq` with the rodeo installation

### ISSUE THREAD

**Issue by luiscape** [yhat/rodeo#15]
Just pip installed `rodeo` and, on the first run, it complained the package `pyzmq` wasn't installed. I pip installed `pyzmq` and everything worked fine. Maybe that should be included as a dependency in the installation process or alike?

Really wonderful work, folks!

**Comment by ericchiang** [comment]
Thanks for reporting!

Oddly I'm was able to install fine in a virtual env on linux without pyzmq. It's probably a IPython dependency. What operating system are you on?

**Comment by glamp** [comment]
fixed in 0.2.1

**Comment by luiscape** [comment]
I'm on a Mac OSX (10.10.2). Python 2.7.8. 

Thanks for fixing!
