### ISSUE TITLE
Download link on website goes to wrong page.

### ISSUE THREAD

**Issue by cldershem** [yhat/rodeo#151]
The auto-download on the main [download page](https://www.yhat.com/products/rodeo/downloads) never started for me (Chrome 46, Ubuntu 15.10 64bit).  When I clicked the download link (see screenshow) it took me to the [yhat homepage](https://www.yhat.com/) instead of downloading anything.

![download link](https://cloud.githubusercontent.com/assets/201608/10946855/86a0adec-82f2-11e5-90e9-860afce3644c.jpg)

Obviously I can click the links below it, but it took a second to figure out why it wasn't working.

**Comment by glamp** [comment]
thanks should be fixed now
