### ISSUE TITLE
energy use on mac

### ISSUE THREAD

**Issue by ChristopherShort** [yhat/rodeo#153]
HI - very nice app - great idea.

Unfortunately my macbook pro (15", late 2013) runs very hot when using it.

Looking at the the 'energy use' it appears to never idle, with energy use an order of magitude larger than anything else I'm running.

It's good for about 30 minutes, but then needs to be turned off to let the machine cool down.  In testing today, after about 80 minutes, the heat could be felt through the keyboard - and the bottom shell was very hot.

cheers
Chris

**Comment by glamp** [comment]
I believe the issue comes from the file indexing for `cmd + t`. I puts a throttle in the code so it won't burn through your CPU. it's in 1.1.+. give it a try and let me know if the issue persists!
