### ISSUE TITLE
Rodeo can't start with Anaconda 2.4

### ISSUE THREAD

**Issue by sshuair** [yhat/rodeo#155]
I have installed the lastest Anaconda( [Anaconda2-2.4.0](https://www.continuum.io/downloads)). When I start the Rodeo, an error has occurred. I have reinstalled both Anaconda and Rodeo, but it still does't work.
![1](https://cloud.githubusercontent.com/assets/5787131/11018480/4d322994-8605-11e5-9abd-f0f157020ae0.jpg)

**Comment by msarahan** [comment]
This might be the matplotlib dll issue that we've been having with Anaconda 2.4.  If you updated from an earlier version, you either need to manually add (your install prefix)\Library\bin to your PATH environment variable, or sit tight and wait for the update.  It should be tested and released sometime tomorrow.

**Comment by sshuair** [comment]
Thanks! I'll waiting for the update.

**Comment by Kiminaka** [comment]
Hi, I have the same issue. Did you solve your problem with an updated version?

**Comment by sshuair** [comment]
Nope， I do not find the win update. I use Spyder and Pycharm instead.

**Comment by sshuair** [comment]
I think you can compile the source code with some software.

**Comment by nbara** [comment]
Also having this problem on OS X, with anaconda 2.4.0, matplotlib 1.5.0. 

The previous binary worked fine for me, now it looks like a mess.

![screen shot 2015-11-27 at 14 22 34](https://cloud.githubusercontent.com/assets/10333715/11443128/51e01d5e-9512-11e5-9450-973dc738ee41.png)

I've edited my .bash_profile to include anaconda/bin

What else can I try?

**Comment by glamp** [comment]
what is the path to the python version you want to run?

**Comment by nbara** [comment]
/Users/myname/anaconda/bin

**Comment by nbara** [comment]
I've tried doing a clean install (removing all files from Application Support)

It seems that deleting the .rodeorc and .rodeoprofile from my root folder, and it improved things somewhat:

![screen shot 2015-11-29 at 10 13 39](https://cloud.githubusercontent.com/assets/10333715/11456208/160a7150-9682-11e5-9410-8595765e8885.png)

Now Rodeo still can't start, and when I type anything in the console I get this error:

<img width="532" alt="screen shot 2015-11-29 at 10 16 01" src="https://cloud.githubusercontent.com/assets/10333715/11456212/3552baae-9682-11e5-923a-e6733b867e06.png">
