### ISSUE TITLE
Unable to save files

### ISSUE THREAD

**Issue by edoardovivo** [yhat/rodeo#156]
I am working on Rodeo 0.4.4 on a remote Linux server. I can open files in several tabs, an I am able to modify them. However, I am not able to save them. When I hit Crtl-S or File->Save, an icon appears on the Tab for a split second, suggesting something has happend, but the file does not get modified in the Server. 

Thank you. 
Edoardo

**Comment by edoardovivo** [comment]
I forgot to mention that I am using Chrome and that I have read/write permission on all files.

**Comment by edoardovivo** [comment]
Correction: The files are saved, but not in the directory they were retrieved from. Maybe a "set as working directory" button like in RStudio would be a good idea?

Thank you!

**Comment by glamp** [comment]
<0.5 no longer supported. If you try 1.0+ you should be able to do this.
