### ISSUE TITLE
Console font is too small

### ISSUE THREAD

**Issue by syzhjjw** [yhat/rodeo#157]
Console font is too small

**Comment by jasdumas** [comment]
I just saw this at the bottom of the Preference window that the font size can be changed!

![image](https://cloud.githubusercontent.com/assets/6685750/11101373/8d593216-8884-11e5-8e70-754689df327d.png)

**Comment by syzhjjw** [comment]
but when restart rodwo, the font size cannot work...

2015-11-12 3:59 GMT+08:00 Jasmine Dumas <notifications@github.com>:

**Comment by miishke** [comment]
I also have issue with font size not being applied after closing and reopening the app. I'm on OS X Yosemite and Python 3.5.

**Comment by glamp** [comment]
should be fixed in the next release

**Comment by glamp** [comment]
this has been released
