### ISSUE TITLE
Reload Confirmation

### ISSUE THREAD

**Issue by AdrianoW** [yhat/rodeo#159]
Please,

before reloading, issue a prompt asking the user if that is really wanted. Trying to issue some find and replace (command+R) I have lost some hours of work.

Thanks.

**Comment by nbara** [comment]
+1 on this

**Comment by glamp** [comment]
fixed in 017927b80e24998b292d31b9055dc484f7a1ad56

**Comment by AdrianoW** [comment]
Nice!! Thanks

2015-11-19 20:12 GMT-02:00 Greg Lamp <notifications@github.com>:
