### ISSUE TITLE
Rodeo v1.0.2 multiline edit tab

### ISSUE THREAD

**Issue by kpykc** [yhat/rodeo#160]
There seems to be a problem with multiline editing.
When I'm selecting few lines to indent simultaneously, and pressing Tab to indent, only the last line indented. 

<img width="619" alt="multiline_tab" src="https://cloud.githubusercontent.com/assets/509191/11120493/5ce2704e-8950-11e5-91e4-476ce6b282b3.png">

**Comment by ben519** [comment]
Also experiencing trouble (although different) using tab - when I highlight multiple lines and hit Tab, the highlighted selection gets erased.  Although when I hit Shift+Tab the section un-indents appropriately.

On second look, I don't see any explicit documentation stating that multi-line indentation is supported, but   I think it'd be great if this was fixed/implemented.

**Comment by glamp** [comment]
try `shift + [` and `shift + ]`

**Comment by sokser** [comment]
On a mac its `control + [` and `control + ]`
