### ISSUE TITLE
Create releases and add a CHANGELOG

### ISSUE THREAD

**Issue by yassineAlouini** [yhat/rodeo#162]
It would be nice to have **releases** corresponding to the different rodeo versions. 
For example, one should have at lease the release of the version **v0.4.4** available in the Github repository. 

Furthermore, a **CHANGELOG** recording the new additions for each new release would be appreciated. If no one has time for this, I can start doing it next week. 

Anyway, rodeo is an awesome tool :smile:. Keep up the great work guys :+1:.

**Comment by glamp** [comment]
added https://github.com/yhat/rodeo/blob/master/CHANGELOG
