### ISSUE TITLE
Markdown render many times

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#165]
Sequence:

1) Highlight section of editor
2) Click 'markdown renderer' button

(did the above ~5-10 times)

Got below:

![image](https://cloud.githubusercontent.com/assets/7118371/11287281/69c55018-8ee8-11e5-9299-9d789c32a85b.png)

**Comment by glamp** [comment]
Lots of markdown?!?! That sounds more like a feature than a bug.

**Comment by glamp** [comment]
fixed in latest
