### ISSUE TITLE
Feature request:  Visually indicate active operation and manually interrupt

### ISSUE THREAD

**Issue by dhicks** [yhat/rodeo#171]
I'm working with a bit of code that runs very slowly (community detection on a large network).  There doesn't seem to be any visual indication that the console is actively chewing on a bit of code (unless I had a `print` line somewhere in every loop or something like that), and there's no way to interrupt things if I decide they're taking too long.  Those would be nice features to have.  

Just in case this actually reflects a problem, I'm running Rodeo 1.0.2 on Mac OS X El Capitain.

**Comment by glamp** [comment]
will be in 1.2.0
8314d79604c17faf40e506467c6b5a3b5a2308f3
