### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by MattW** [yhat/rodeo#172]
Trying to run any python from the console or a file results in a javascript error.  Following image shows common error, all are TypeError with executeStream.

OS is Windows 7, using Anaconda with Python 3.4.  Jupyter and Matplotlib installed successfully.

![image](https://cloud.githubusercontent.com/assets/382178/11357802/88e64946-9228-11e5-8b6d-6f60d3b59f1d.png)

**Comment by glamp** [comment]
Hey Matt,

Sorry about this. Try version 1.1.15. It should be out in the next 30-40 minutes.

**Comment by MattW** [comment]
Thanks for the quick response glamp!  I'm now getting "Rodeo is starting up...We're launching your python session. This should only take a moment or two."  I know there is some words in the documentation on what to do if things don't start up.  The problem is, I never get to any sort of dump.  Is there a log file anywhere?

**Comment by glamp** [comment]
does that pop-up stay on the screen?

**Comment by MattW** [comment]
I closed it after about an hour.

**Comment by glamp** [comment]
Can you run this in your terminal?

```
cd ~/.matplotlib/
fc-list  # Should take a couple minutes.
```

Then reopen Rodeo and see if it works?

**Comment by MattW** [comment]
I'm on windows and have no fc-list command.  I did try switching to the 32-bit version and it appears to be the same issue.

**Comment by Azure-rong** [comment]
When clicked "Restart Session", the Javascript error appeared again. Except the "executeStream" error, it also showed the "execute" error.

**Comment by fkratzert** [comment]
hey there,
unfortunately i have the same problem (or some similary java script error) showing up on the start. im running on windows 7, using anaconda with python 2.7, updatet versions of jupyter, matplotlib etc. i also tried the 32bit, and the 64bit version. strange thing is, that on my colleagues computer with same setup it runs without problems. Any hint on that?
![unbenannt](https://cloud.githubusercontent.com/assets/13069767/11897385/95aa6d9a-a58f-11e5-958b-8a884aad73c8.PNG)

**Comment by Nosferican** [comment]
Experiencing the same issue here: Win10, Python 3.5.

**Comment by dlukes** [comment]
Same issue as @fkratzert and @Nosferican (i.e. the `write PIPE` error) on Win10 and Python 3.5 (Anaconda3-2.4.1 and Rodeo-v1.1.23, both 64-bit).

**Comment by samuelleach** [comment]
Experiencing the same on Mac OS (10.11.2)

**Comment by glamp** [comment]
fixed in 1.3.0
