### ISSUE TITLE
Working directory in Console not matching the Preference working directory 

### ISSUE THREAD

**Issue by seantma** [yhat/rodeo#176]
Tried `! ls` and found I'm at `/` rather than the working directory I've set through Preferences.

**Comment by 1beb** [comment]
Same problem here on both windows and linux. Working directory is largely ignored in favor of whatever directory Rodeo was called from. 

Workaround: 

```
import os
os.chdir(desired_dir)
````

**Comment by mcmunder** [comment]
Same problem here on OSX Yosemite. Got a `PermissionError [Erno 13]` when trying to read from files inside the default working directory. Same when I was trying to create a file with `open('test.txt', 'w+').close()`.  @1beb 's workaround solves this. This should be fixed!

**Comment by kevindavenport** [comment]
Same problem here

**Comment by glamp** [comment]
fixed in 2.4+
