### ISSUE TITLE
Copy/Paste doesn't work 14.04 LTS

### ISSUE THREAD

**Issue by pybokeh** [yhat/rodeo#178]
Installed with https://www.yhat.com/products/rodeo/downloads/linux_64  
  
Running Xubuntu 14.04 LTS 64-bit in Oracle Virtualbox instance inside Windows 8.1 host.  
  
Sorry, I don't have a native Linux machine at the moment to determine if problem is due to virtualbox.

**Comment by pybokeh** [comment]
Hmm, maybe related to issue #140.  I didn't notice that I got a javascript error ("Javascript error occurred in the main process") at first because the error message dialog window rendered behind the main Rodeo GUI window.

**Comment by glamp** [comment]
Ah ha! Found it!
![linux-copy-paste-no-work](https://cloud.githubusercontent.com/assets/1409333/11746664/1b9b2f0a-9fed-11e5-90ab-85aa002df2ad.png)

**Comment by glamp** [comment]
fixed in 1.1.21
