### ISSUE TITLE
i can't close my console when it is runing 

### ISSUE THREAD

**Issue by elon-** [yhat/rodeo#179]
there is no short cut key or or a button to stop my console when it is running. i used to work with spyder there is option called kill the current process , causing it to exit it immediately in the console . this was very helpful when i run and print  a large data after cleaning process. please add it

**Comment by glamp** [comment]
available in 1.2

**Comment by rforgione** [comment]
@glamp has this since been removed? I don't see it in 2.0.13. There is an 'interrupt kernel' button but it's not actually working for me.

**Comment by glamp** [comment]
@TakenPilot @coristig thoughts here?

**Comment by rforgione** [comment]
@glamp @TakenPilot @coristig just wanted to follow up on this. Is there any reliable way to kill a command that is currently running? I'd be happy to dig into the code myself if someone could point me in the right direction.
