### ISSUE TITLE
Startup Time is too long

### ISSUE THREAD

**Issue by babetoduarte** [yhat/rodeo#180]
The startup time for my rodeo installation on mac OSX takes several minutes to start up:
![screen shot 2015-11-30 at 7 04 28 pm](https://cloud.githubusercontent.com/assets/2272956/11488528/397b9920-9795-11e5-9a23-75ef750e3721.png)
![screen shot 2015-11-30 at 7 01 31 pm](https://cloud.githubusercontent.com/assets/2272956/11488489/d7e3c84a-9794-11e5-8367-80ba5243a7b9.png)

I know the dialog says it might take a moment or two, but it would be nice if this time could be reduced.

**Comment by glamp** [comment]
What are your system specs?

**Comment by glamp** [comment]
Does it ever finish?

**Comment by babetoduarte** [comment]
@glamp Yes it does. It just takes 2min+.

**Comment by babetoduarte** [comment]
I opened the activity monitor to check what was going on, and found that the process fc-list is the one heavily loading my machine while Rodeo starts:
![screen shot 2015-12-01 at 12 23 15 pm](https://cloud.githubusercontent.com/assets/2272956/11508410/bde2b270-9826-11e5-9a4b-9a83a8dfd3ed.png)

 As fc-list terminates, Rodeo finishes starting up:
![screen shot 2015-12-01 at 12 26 09 pm](https://cloud.githubusercontent.com/assets/2272956/11508421/cef215a6-9826-11e5-9ffd-a869592b7526.png)

**Comment by glamp** [comment]
Looks like something is wrong w/ matplotlib: 

http://stackoverflow.com/questions/17490444/import-matplotlib-pyplot-hangs

Can you try that and let me know if it fixes things?

**Comment by Azure-rong** [comment]
Redeo can not open in Win7 32bit. It just stuck in the start up section and seems can never be finished.
p.s. I have already install Anaconda in the computer. Is it would be the problem?

**Comment by babetoduarte** [comment]
@glamp I executed the commands, the execution of fc-list took nearly a second and outputted the following:
```
$ fc-list
Fontconfig warning: ignoring UTF-8: not a valid region tag
/usr/X11/lib/X11/fonts/75dpi/charBI12.pcf.gz: Charter:style=Bold Italic
/Library/Fonts/Cochin.ttc: Cochin:style=Italic,斜體,Kursiv,Kursiivi,Italique,Corsivo,イタリック,이탤릭체,Cursief,Itálico,Курсивный,斜体,Cursiva
/usr/X11/lib/X11/fonts/100dpi/lubR18-ISO8859-1.pcf.gz: LucidaBright:style=Regular
/usr/X11/lib/X11/fonts/75dpi/lubBI08.pcf.gz: LucidaBright:style=Italic
...
...
```
It listed a vast amount of fonts, preceded by the message: "Fontconfig warning: ignoring UTF-8: not a valid region tag".

After that, I proceeded to launch Rodeo but I saw no change in the startup time. You can verify this by the hour on the screenshots:
![screen shot 2015-12-02 at 9 11 21 am](https://cloud.githubusercontent.com/assets/2272956/11533113/1228e606-98d6-11e5-8cfd-777d56574908.png)
![screen shot 2015-12-02 at 9 12 56 am](https://cloud.githubusercontent.com/assets/2272956/11533115/12471eb4-98d6-11e5-8633-cedb037886b6.png)
![screen shot 2015-12-02 at 9 13 11 am](https://cloud.githubusercontent.com/assets/2272956/11533116/12476892-98d6-11e5-97e6-ec893971baca.png)
![screen shot 2015-12-02 at 9 14 45 am](https://cloud.githubusercontent.com/assets/2272956/11533114/1245d0ea-98d6-11e5-9a87-55b926ee5d8a.png)
The only other strange thing I noticed is that fc-list was executed twice. 

I hope this feedback helps, and please let me know if you need me to try anything else.

**Comment by weinerjm** [comment]
I'm experiencing the exact same issue as @babetoduarte. Running `fc-list` in `~/.matplotlib` does not fix the issue either.

I also tried removing and re-installing `matplotlib` with `pip`, which didn't help.

**Comment by weinerjm** [comment]
I think I found a workaround. After I `brew install fontconfig` and run `fc-list` in `~/.matplotlib/` then Rodeo starts up within a few seconds. If I instead use XQuartz's `/opt/X11/bin/fc-list` then I experience long boot-up times.

Strangely enough, my XQuartz is up-to-date and both `fc-list` seem to be the same version:
```
$ /usr/local/bin/fc-list --version
fontconfig version 2.11.1
```
versus
```
$ /opt/X11/bin/fc-list --version
fontconfig version 2.11.1
```

I'd be interested to see if this works for @babetoduarte as well!

**Comment by babetoduarte** [comment]
@weinerjm I tried running brew '''install fontconfig''' and then running '''fc-list'' from '''~/.matplotlib''', but your fix doesn't seem to work for me. I also checked and both versions of '''fc-list''' are up to date as well.

Who knows, maybe it is a build flag problem of some sorts.

**Comment by weinerjm** [comment]
Bummer. It also occurred to me that it could be an issue with the version of a build dependency like freetype or its dependency libpng, or some sort of special font.

Are you certain that `/usr/local/bin` comes before `/opt/X11/bin` in your `PATH` variable so that you weren't still using the XQuartz version of `fc-list` after installing `fontconfig`? That's something I've messed up before. Did you try a `brew update` and `brew upgrade`, just to be sure?

**Comment by glamp** [comment]
any updates? did anyone try brew update and brew upgrade?

**Comment by weinerjm** [comment]
Installing the latest version of fontconfig via brew and then running
fc-list in ~/.matplotlib worked for me, as I described above. I haven't had
to make any changes since then.

**Comment by yakzan** [comment]
I also faced the same issue, for me it didn't ever finish on my MBA. 

Adding "pythonCmd": "/opt/local/bin/python" into ~/.rodeorc solved the problem for me and got rodeo launching past this point.

**Comment by babetoduarte** [comment]
I tried brew update and brew upgrade, but the situation hasn't changed. I even updated to the lates version of Rodeo, but still no change.

**Comment by babetoduarte** [comment]
Update: I was running both Homebrew and macPorts. I god rid of macports, and this bug doesn't happen any more in my case. Most certainly there was a python version conflict between both package managers. Startup now only takes a few seconds! :)

**Comment by glamp** [comment]
Great!
