### ISSUE TITLE
"Bad news! Rodeo can't start :-(" on OSX

### ISSUE THREAD

**Issue by nbara** [yhat/rodeo#182]
Hi there,

Just installed Rodeo Desktop 1.1.16 and I'm getting the infamous 'Bad news' message.

![screen shot 2015-12-02 at 10 44 15](https://cloud.githubusercontent.com/assets/10333715/11528935/a5b1a1d2-98e1-11e5-8c0f-c0b584c6c865.png)

I'm using anaconda 2.4.0 on OSX 10.11, python is installed at the default anaconda location( ~/anaconda/bin)
I've tried updating and downgrading matplotlib from 1.4.3 to 1.5.0
Default Python Command is set to: /Users/nbara/anaconda/bin

I don't know if it's related, but clicking 'Restart session' gives me this:
![screen shot 2015-12-02 at 10 47 25](https://cloud.githubusercontent.com/assets/10333715/11529004/18063dc4-98e2-11e5-80fe-1602f427d3f3.png)

**Comment by fmikaelian** [comment]
Hello,

I got the same screen error on OSX 10.11.1 since I upgraded my Rodeo Desktop to 1.1.15.
I still use hombrew python located in /usr/local/bin/python, and the jupyter-client & Ipython modules are both correctly installed.

Can you help ?

Many Thanks

**Comment by glamp** [comment]
Can you try using 1.1.16?

**Comment by nbara** [comment]
The screens in my first post above are from 1.1.16 (downloaded today)

**Comment by glamp** [comment]
`/Users/nbara/anaconda/bin` needs to be `/Users/nbara/anaconda/bin/python`

**Comment by nbara** [comment]
Yes I've tried that as well. Same error...

**Comment by glamp** [comment]
can you open Dev Tools and see if there are any logs?

`View > Toggle Dev tools`

**Comment by nbara** [comment]
There is indeed an error, but I'm not sure what it means...

![screen shot 2015-12-02 at 16 02 23](https://cloud.githubusercontent.com/assets/10333715/11535960/22589854-990e-11e5-925a-a3fe7219d0c9.png)

**Comment by glamp** [comment]
i'm doing a patch release. 1.1.17 will be available for download shortly...

**Comment by nbara** [comment]
Great, thanks. Will give it a try asap and report back. :)

**Comment by glamp** [comment]
up now

**Comment by nbara** [comment]
![screen shot 2015-12-02 at 16 51 50](https://cloud.githubusercontent.com/assets/10333715/11537462/06f800ac-9915-11e5-840d-f0ce80dee1f5.png)

Thanks @glamp

**Comment by glamp** [comment]
awesome!

**Comment by fmikaelian** [comment]
I still got the "Bad news! Rodeo can't start" error with the version 1.1.17 :/

**Comment by glamp** [comment]
can you open Dev Tools and see if there are any logs?

`View > Toggle Dev tools`

**Comment by fmikaelian** [comment]
I got the same logs as @nbara
![screen shot 2015-12-02 at 21 35 30](https://cloud.githubusercontent.com/assets/12005605/11543418/ccf3915a-993c-11e5-8f94-b04f1a8e16f2.png)

**Comment by fmikaelian** [comment]
Issued fixed since version 1.1.19 :-)
Many thanks @glamp
