### ISSUE TITLE
`from pprint import pprint` breaks Environment panel (Desktop)

### ISSUE THREAD

**Issue by dlukes** [yhat/rodeo#186]
On a fresh instance of Rodeo, after running the following, `foo` does not appear in the Environment panel:

```python
from pprint import pprint
foo = [1, 2, 3]
```

If I then type `import pprint` at the console prompt, the panel "wakes up" again.

Looking at the output of `dir()` from the IPython console, there's a lot of stuff that Rodeo loads into the Python image, presumably for similar purposes as the `pprint` module (i.e. providing UI functionality):

```python
['ast', 'inspect', 'json', 'np', 'pd', 'pip', 'pp', 're', 'types']
# none of these are there when I open ipython from the terminal
```

Is there perhaps a cleaner way of doing this by isolating the stuff that the IDE crucially relies on for functionality from the user's environment? The current setup is brittle because the user can easily yet unknowingly mess it up, as demonstrated by myself...

System info: OS X 10.11.1, Rodeo v1.1.19 (Desktop), Anaconda3 2.4.0

**Comment by glamp** [comment]
I can't reproduce this.
```
>>> from pprint import pprint 

>>> foo = [1, 2, 3]

>>> foo
[1, 2, 3]
```

I don't think the issue you're describing is critical. The user would have to unload or delete one of the imports you listed.

**Comment by dlukes** [comment]
I'm afraid I didn't make myself clear: of course you can access `foo` at the prompt after creating the variable, it just **doesn't show up in the Environment pane** in the upper right-hand corner (if you've previously run `from pprint import pprint`). I still think it's an issue worth addressing, time permitting, because currently, **any user running a script which imports the `pprint` function** (which is often useful for debugging purposes) **will essentially break down Rodeo's UI** (the variable list in the Environment pane will disappear) and spend quite some time scratching their head to figure out what caused this.

Should anyone have the time or ability to look into this some more, I include more detailed instructions to reliably reproduce this under OS X 10.11.1 (I can't confirm if Windows is affected or not because I can't get Rodeo to start on Win10 -- see yhat/rodeo#172 -- but I don't see why it shouldn't be):

1. Create a fresh, pristine user account to make sure there's no interference from older bits of setup.
2. Download and install [Anaconda Python 3.5 64-bit for OS X](https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda3-2.4.1-MacOSX-x86_64.pkg) (version 2.4.1 at time of writing). I selected the option to install only for the current user, i.e. under `~/anaconda`.
3. Download and install [Rodeo for OS X](https://www.yhat.com/products/rodeo/downloads/osx) (version 1.1.23 at time of writing).
4. Start Rodeo. If you get stuck at the stage of starting the Python session (with the spinning gears logo), close Rodeo, add `"pythonCmd": "/Users/<username>/anaconda/bin/python3",` to your `~/.rodeorc` and restart Rodeo.
5. At the IPython prompt, type `foo = [1, 2, 3]`. (Or do this in the editor pane and evaluate each line with Cmd+Enter, it doesn't matter.) An entry for `foo` will appear in the variable list in the upper right-hand corner Environment pane.
6. Now, type and eval `from pprint import pprint`. The entry for `foo` in the Environment pane disappears (along with any other variables you may have added). The variables are **still** present in the Python image, just eval `foo` at the prompt, but the functionality of the UI element which should be displaying them has been broken by the import.
7. If you then type and eval `import pprint`, the list of variables reappears in the Environment pane, whose functionality is thus restored.

If it's impossible to reproduce the issue using the procedure outlined above, then something weird and possibly mystical is afoot :)

> The user would have to unload or delete one of the imports you listed.

Well, not really, as the Environment pane is broken by **importing** the `pprint` function from the `pprint`module.

As for the criticalness of the issue -- the problem is that the causality is really not obvious, I had a fairly hard time figuring out what was causing the Environment pane to stop working properly. And as said above, importing the `pprint` function for debugging purposes is something a number of users can be expected to do, it's nothing out of the ordinary.
