### ISSUE TITLE
Cmd + Enter inserts newline in addition to running selection (Desktop)

### ISSUE THREAD

**Issue by dlukes** [yhat/rodeo#187]
Perhaps this is intended behavior (?), but if so, would it be possible to add an option to disable it? After re-running a script a few times, I end up with a bunch of empty lines at the end of the file which have to be erased manually :)

System info: OS X 10.11.1, Rodeo v1.1.19 (Desktop), Anaconda3 2.4.0

**Comment by glamp** [comment]
yes this is by design. maybe we could add an option?

**Comment by dlukes** [comment]
That would definitely help :) Personally though, I can't really think of a use case where I'd want those newlines to be inserted...
