### ISSUE TITLE
Rodeo can't pick up python path for /usr/

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#189]
If the python executable is set to `/usr/bin/python`, rodeo fails with the javascript error below:

[OS X 10.10]

![image](https://cloud.githubusercontent.com/assets/7118371/11640811/93449a20-9d02-11e5-8a98-8775b9091085.png)

**Comment by blewy** [comment]
I'm having this problems also, any fix ?

**Comment by glamp** [comment]
fixed in 1.2 and improved in 1.3
a442ec77bb2648b8d0c64bd5056a9bf96d15bbc0
