### ISSUE TITLE
Default Python Command update should reload the session when its changed

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#192]
Right now, if I have an incorrect python path, and then change it to a correct python path, the code fails w/ a JS error that it can't find my python path, b/c I haven't reset my session.

We should likely follow process below:
1) User updates path
2) User is prompted "You've changed your path, do you want to restart your session to use your new path?(Y/N)
3) Rodeo restarts

**Comment by glamp** [comment]
8314d79604c17faf40e506467c6b5a3b5a2308f3
