### ISSUE TITLE
fail to use rodeo on mac

### ISSUE THREAD

**Issue by harryprince** [yhat/rodeo#193]
Uncaught Exception:
TypeError: Cannot read property 'executeStream' of null
    at EventEmitter.<anonymous> (/Volumes/Rodeo/Rodeo.app/Contents/Resources/app.asar/src/desktop/main.js:124:13)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Volumes/Rodeo/Rodeo.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:85:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

**Comment by binga** [comment]
+1. Same error here. @glamp any workaround?

**Comment by fsbatista** [comment]
+1

**Comment by glamp** [comment]
If you open dev tools View > Toggle Dev Tools, are there any logs?

**Comment by binga** [comment]
I see the following message.
(electron) ipc module is deprecated. Use ipcRenderer module instead. /Applications/Rodeo.app/Contents/Resources/atom.asar/common/api/lib/deprecate.js:89

**Comment by fsbatista** [comment]
pplications/Rodeo.app/Contents/Resources/atom.asar/common/api/lib/deprecate.js:89 (electron) ipc module is deprecated. Use ipcRenderer module instead.
desktop-main.js:1 [LOG]: using python: /anaconda/bin/python
desktop-index.html:1 Uncaught SyntaxError: Unexpected end of input
desktop-main.js:1 [ERROR]: Result from code execution was null.(anonymous function) @ desktop-main.js:1

**Comment by forstater** [comment]
Same error here as well. /Applications/Rodeo.app/Contents/Resources/atom.asar/common/api/lib/deprecate.js:89 (electron) ipc module is deprecated. Use ipcRenderer module instead.

I also got the following: Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by NathanielF** [comment]
I also can't get Rodeo to open on a mac. I get the following error: 

![image](https://cloud.githubusercontent.com/assets/10588167/13027770/706840e2-d254-11e5-9e23-c92ee007e1fe.png)

**Comment by glamp** [comment]
please try version 1.3.0 as there are significant improvements to Python PATH usage

**Comment by NathanielF** [comment]
Path issue seems to resolved. I past the initial screen where i need to input the path (in my case a conda environment) and am shown a screen listing the features of Rodeo and a button which says something like let's get started with thie IDE, but when i press the button i see this error message: 

Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at /Applications/Rodeo.app/Contents/Resources/app.asar/src/desktop/main.js:38:20
    at /Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeo/kernel.js:179:11
    at null._onTimeout (/Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeo/kernel.js:144:7)
    at Timer.listOnTimeout (timers.js:89:15)

Any idea?

**Comment by paragguruji** [comment]
@NathanielF Same error here:

`Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at /Applications/Rodeo.app/Contents/Resources/app.asar/src/desktop/main.js:38:20
    at /Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeo/kernel.js:179:11
    at null._onTimeout (/Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeo/kernel.js:144:7)
    at Timer.listOnTimeout (timers.js:89:15)`

**Comment by TakenPilot** [comment]
[Rodeo 2.0.0](https://github.com/yhat/rodeo/releases/tag/v2.0.0) contains the stability fixes for this issue.
