### ISSUE TITLE
different versions in pip and standalone

### ISSUE THREAD

**Issue by johanez** [yhat/rodeo#197]
I installed rodeo with ```pip install rodeo```, using conda and python 3.4 on an linux machine. The version is to be 0.4.4.
I also installed the standalone 1.1.2 on a Windows machine. It looks much better!

Is there a way to either:
* get a more up to date version for pip?
* run the standalone in a browser?

**Comment by glamp** [comment]
no pip is being deprecated

**Comment by johanez** [comment]
While there are many good desktop IDEs for python, a rodeo you could run on a remote server through the browser would be very useful for many i think. 

See also Issue#220: Feature request: Connect to remote jupyter notebook server
