### ISSUE TITLE
Link to gif file in readme is dead

### ISSUE THREAD

**Issue by Gabriel-p** [yhat/rodeo#198]
See here:

https://github.com/yhat/rodeo/blame/master/README.md#L29

the link is dead:

https://raw.githubusercontent.com/yhat/rodeo/master/rodeo/static/img/Rodeo-Demo.gif

**Comment by urkud** [comment]
The gif file was removed in a8758c68af0e2b12e96fa30e42e9f4505389ce1f

**Comment by glamp** [comment]
fixed!
