### ISSUE TITLE
Cannot add folder within Rodeo

### ISSUE THREAD

**Issue by homerhanumat** [yhat/rodeo#200]
In the Files pane the working directory is shown with little cogs next to it.  When I press the cogs I get an option to Add Folder.  In the dialog box I give the prospective folder a name and press OK, but nothing happens.

Running latest version of Rodeo.  Issue occurs on Mac OSX and on Liinux.

Homer

**Comment by coristig** [comment]
Confirmed that this is still an issue in 1.3.0

**Comment by glamp** [comment]
Fixed in 1.3.1/b0d3fcbf8b58c346b65a9bce9c78b3e80ebc40de
