### ISSUE TITLE
import seaborn error

### ISSUE THREAD

**Issue by jforsythe44** [yhat/rodeo#203]
I get this error when I try to import seaborn.  

I don't have any problems running seaborn in iPython Notebook or from pycharm?

-------------------------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-25-73ad5ea94595> in <module>()
      4 import matplotlib as mpl
      5 import datetime
----> 6 import seaborn as sns
      7 
      8 sns.set(style='white')

C:\Users\######\AppData\Local\Continuum\Anaconda\lib\site-packages\seaborn\__init__.py in <module>()
      2 from .utils import *
      3 from .palettes import *
----> 4 from .linearmodels import *
      5 from .categorical import *
      6 from .distributions import *

C:\Users\#######\AppData\Local\Continuum\Anaconda\lib\site-packages\seaborn\linearmodels.py in <module>()
     22 from .external.six.moves import range
     23 
---> 24 from . import utils
     25 from . import algorithms as algo
     26 from .palettes import color_palette

ImportError: cannot import name utils

**Comment by glamp** [comment]
closing as this seems like a seaborn issue, not a Rodeo
