### ISSUE TITLE
matplotlib installation instructions insufficient on Windows

### ISSUE THREAD

**Issue by minimaxir** [yhat/rodeo#204]
On Windows, the instruction to install matplotlib is:

`pip install matplotlib`

This will not work and will throw errors on a fresh installation.

![rodeo](https://cloud.githubusercontent.com/assets/2179708/12043460/2a276d12-ae3a-11e5-9e9b-022f86782298.png)

Per [the installation instructions](http://matplotlib.org/users/installing.html):

> For standard Python installations you will also need to install compatible versions of setuptools, numpy, python-dateutil, pytz, pyparsing, and cycler in addition to matplotlib.

> For Python 3.5 the Visual C++ Redistributable for Visual Studio 2015 needs to be installed. In case Python 2.7 to 3.4 are not installed for all users (not the default), the Microsoft Visual C++ 2008 ( 64 bit or 32 bit for Python 2.7 to 3.2) or Microsoft Visual C++ 2010 ( 64 bit or 32 bit for Python 3.3 and 3.4) redistributable packages need to be installed.

> Matplotlib depends on Pillow for reading and saving JPEG, BMP, and TIFF image files. Matplotlib requires MiKTeX and GhostScript for rendering text with LaTeX. FFmpeg, avconv, mencoder, or ImageMagick are required for the animation module.

**Comment by minimaxir** [comment]
From [the blog post mentioned in the documentation](https://houndofweb.wordpress.com/2013/06/08/install-matplotlib-in-windows/)

`pip install distribute
easy_install matplotlib`

Doesn't work either. Hmm.

**Comment by glamp** [comment]
going to close since this seems like a "matplotlib sucking issue" rather than an issue w/ Rodeo

**Comment by glamp** [comment]
also, matplotlib is no longer required (as of 1.3.0)
