### ISSUE TITLE
Rodeo (mac native) fails to detect matplotlib

### ISSUE THREAD

**Issue by craigcitro** [yhat/rodeo#205]
Just downloaded Rodeo v1.2.1, and pointed it to a valid python path (in a virtualenv). I get stuck at "Looks like you're missing *matplotlib*". 

I can confirm that matplotlib is indeed installed, and as per the ["testing your setup"](http://rodeo.yhat.com/docs/#prerequisites) page, executing

    $ ipython -c "import matplotlib"

in the same virtualenv succeeds.

Happy to help debug, but right now I'm stuck with an overlay and can't even try out Rodeo. :disappointed:

**Comment by maxtheman** [comment]
I can confirm that I'm also having this issue with a virtualenv, with jupyter and python PATH as well as matplotlib.

**Comment by jiaaro** [comment]
I'm also having this issue. When I install jupiter and matplotlib globally (outside a virtualenv) and tell it `/usr/bin/python` then it fails the jupyter check :disappointed:

**Comment by craigcitro** [comment]
ok, so this is apparently a known issue for matplotlib:
  http://matplotlib.org/faq/virtualenv_faq.html

for @glamp -- it might be worth updating http://rodeo.yhat.com/docs/#prerequisites to say `import matplotlib.pyplot`, since that matches the actual runtime check.

**Comment by AlJohri** [comment]
Having this same problem outside of a virtualenv. It finds python and jupyter but not matplotlib. I'm using pyenv.

The homebrew python works fine but I'd prefer to use my pyenv installation.

I specified the path as `/Users/atul/.pyenv/versions/3.5.0/bin/python`. I believe it has something to do with being a non-framework install but I'm just guessing?

**Comment by AlJohri** [comment]
I was able to sort of get it working by installing anaconda through pyenv: `pyenv install anaconda3-2.4.0`

I then set the path within rodeo native to `/Users/johria/.pyenv/versions/anaconda3-2.4.0/bin/python3` and it was able to find all the necessary libraries.

I think there is something wrong with the detection of matplotlib code.

**Comment by coristig** [comment]
We've removed matplotlib as a dependency in 1.3.0 and have done a bunch of path-related improvements.

@craigcitro, @jiaaro, @maxtheman can you guys try running the latest version and see if this is resolved?

I've been able to run a virtualenv on my machine w/ and w/o matplotlib.  Thanks!

**Comment by maxtheman** [comment]
@coristig Works for me perfectly.

I was also able to change rodeo's default path to a virtualenv installation of ipython and have it find, matplotlib, jupyter, and other local things in site-packages as expected. Great work!

**Comment by AlJohri** [comment]
@coristig works for me too using python 3.5.1 via pyenv

For any future readers, I set the path to: `/Users/username/.pyenv/versions/3.5.1/bin/python`

**Comment by glamp** [comment]
based on @AlJohri and @maxtheman going to close as it seems it is either (a) fixed and/or (b) has an acceptable workaround

**Comment by claytonm** [comment]
I cannot run Rodeo 2.5.2 on a Mac in a virtualenv because it cannot find matplotlib.
