### ISSUE TITLE
preferences cannot be changed while modal dialog box is up

### ISSUE THREAD

**Issue by tedunderwood** [yhat/rodeo#206]
Trying to install on OS X Mavericks. Modal dialog box comes up, says "looks like you're missing jupyter."

I conclude it's looking in the wrong place, 'cause I have jupyter. Want to add a new python path. But I can't, because I'm stuck in the modal dialog box. Clicking on the preferences pane does nothing. No matter what I do, "looks like I'm missing jupyter." No other action is possible; cannot tell it where to find jupyter.

**Comment by tedunderwood** [comment]
I fixed the path issue by adding it to $PATH on the command line, but it still can't find jupyter, even though jupyter is conda installed. I'm using miniconda version of Python 3.5, and conda installed jupyter 1.0.0-py35_1. But Rodeo does not appear to find or recognize it.

**Comment by coristig** [comment]
This is resolved in 1.3.0, closing.
