### ISSUE TITLE
Error:write EPIPE

### ISSUE THREAD

**Issue by zhiyue** [yhat/rodeo#207]
env:
windows 10 

I download exe installer and follow tutorial to install it.
but when i finish setup the path of Python.
![](http://i4.tietuku.com/b49b409a01dcb2c7.jpg)
![](http://i4.tietuku.com/8e2e13e49fa487f9.jpg)
The following error happen:
![](http://i4.tietuku.com/c1b9ef235a23cae7.jpg)

then I can't use it..

how to solve problem?

**Comment by glamp** [comment]
this will be fixed in 1.3

a442ec77bb2648b8d0c64bd5056a9bf96d15bbc0
