### ISSUE TITLE
Show subclasses of DataFrame in addition to pandas.DataFrame

### ISSUE THREAD

**Issue by karthik1024** [yhat/rodeo#21]
Thanks for the great work! It would nice if the Dataframe list also included subclasses in addition to pandas.DataFrame

**Comment by glamp** [comment]
ok that should be pretty easy. do you know how to detect a subclass in python?

**Comment by pikeas** [comment]
`ClassName.__subclasses__()`

**Comment by karthik1024** [comment]
Can use something like `isinstance(obj, pandas.DataFrame)` ?

**Comment by glamp** [comment]
done. in next release. ef2f584
