### ISSUE TITLE
Anaconda + Rodeo in Mac

### ISSUE THREAD

**Issue by Fabs** [yhat/rodeo#212]
I have anaconda2 and anaconda3, and both show the same error with Rodeo 1.2.1 (downloaded from the website).

[setup]
![image](https://cloud.githubusercontent.com/assets/10524/12059002/310f3866-af3a-11e5-9063-83311dc3d94f.png)

[error]
![image](https://cloud.githubusercontent.com/assets/10524/12059006/42dbf12e-af3a-11e5-9e3b-cd596f6237c3.png)

**python --version**
Python 2.7.11 :: Anaconda 2.4.1 (x86_64)

**which python**
/Users/fabs/anaconda2/bin/python

**which pip**
/Users/fabs/anaconda2/bin/pip

**which conda**
/Users/fabs/anaconda2/bin/conda

**Comment by Fabs** [comment]
After setting up with /usr/local/bin/python (from homebrew) I was able to add more paths later and use with conda, so it looks like only the test is broken.

**Comment by jgrosche** [comment]
I also experienced this issue today, I pretty much have the same setup as Fabs, anaconda setup in my profile, same versions etc...

**Comment by moltaire** [comment]
I had the same problem and it was solved by moving 

>export PATH="/Users/MyUserName/anaconda/bin:$PATH"

to the very first line of my .bash_profile.

Got this from a response to #144

**Comment by jdcmf** [comment]
Same issue here, PATH is set. Using zsh

**Comment by Fabs** [comment]
Fixing the path solves the issue for me too. But I have a couple anacondas and paths and envs, and I though that this SET PATH on Rodeo should take care of this when I supply the path for the GUI.

I actually have an alias: 
alias rodeo-conda2='PATH=$HOME/anaconda2/bin:$PATH open /Applications/Rodeo.app'

and rodeo-conda3 and etc...

Thanks anyway for the help.
