### ISSUE TITLE
100% CPU usage on save (OSX - El Capitan)

### ISSUE THREAD

**Issue by rrggrr** [yhat/rodeo#216]
File save hangs after executing program.  AM shows 100% cpu.  No console messages.

<img width="556" alt="activity_monitor__my_processes_" src="https://cloud.githubusercontent.com/assets/1245156/12069541/29485970-b005-11e5-8040-f78684241138.png">

**Comment by glamp** [comment]
where are you saving the file?

**Comment by varoudis** [comment]
same here. I haven't even saved or open a file yet.
Macbook retina 2015 with latest OSX.

**Comment by TakenPilot** [comment]
(Rodeo 2.0.0)[https://github.com/yhat/rodeo/releases/tag/v2.0.0] contains the stability fixes for this issue.
