### ISSUE TITLE
OSX graphical/display/rendering problems

### ISSUE THREAD

**Issue by iron0012** [yhat/rodeo#222]
The newest version of Rodeo appears to have trouble rendering/displaying properly most elements of the UI (frames, etc) on my system (OSX, Mavericks). For a split second upon starting up the program, the proper four-pane interface is displayed. However, it then changes to this:
<img width="1280" alt="screen shot 2016-01-14 at 1 07 53 pm" src="https://cloud.githubusercontent.com/assets/8052991/12334889/0d5a09f8-bac2-11e5-8467-1724a30dbaa6.png">

Interestingly, the Python interpreter appears to work just fine, as you can see. I can enter code at the prompt and it is interpreted correctly when I hit enter. 

Scrolling down, all of Rodeo's various menus (like "Okay you're ready to go", "Looks like we're having trouble finding your Python path", the Rodeo tour, even the "Want a free sticker?" menu) are displayed at once, on one long page (this screenshot shows just the top of them):

<img width="1280" alt="screen shot 2016-01-14 at 1 25 24 pm" src="https://cloud.githubusercontent.com/assets/8052991/12335048/cc2809d4-bac2-11e5-9721-365c90da0bab.png">

I tried "Reset windows to default sizes", messing with the zoom, restarting the session, and nothing seems to make a difference. I feel like I could make one little change and everything would "snap" back into the proper display, but I don't know how to make that happen.

Thanks.

**Comment by ejolly** [comment]
I was having the exact same problem after downloading and copying the newest version and replacing an older version. A fix that worked for me was: deleting the the application, removing the rodeo preference files e.g. `rm .rodeo*` in your home directory, removing the command-line version of rodeo I had previously installed from pip, e.g. `pip uninstall rodeo`, then copying the downloaded application to your Applications folder again and relaunching.

**Comment by iron0012** [comment]
That worked, thank you!
