### ISSUE TITLE
Importing Modules Defined in Working Directory

### ISSUE THREAD

**Issue by pspitler3** [yhat/rodeo#223]
Does anyone else have issues importing a module in the current working directory into a new .py file? For example if I did the example on the basic module python documentation found here: https://docs.python.org/2/tutorial/modules.html

I would get an error on the import fibo. Is anyone else running into this?

**Comment by pspitler3** [comment]
Upon looking into it a little more, it seems the console is not going to the working directory. So the module isnt getting picked up. If I cd into working directory from the console it works as expected.

**Comment by glamp** [comment]
Ok i'm going to close since this is technically #176 but thank you very much reporting! :+1:
