### ISSUE TITLE
Double slashes required when setting the Python path via Windows GUI

### ISSUE THREAD

**Issue by bryancshepherd** [yhat/rodeo#224]
Using Windows 10, double slashes are required to set the path in the initial startup splash screen, i.e., this one:
![rodeo](https://cloud.githubusercontent.com/assets/4349868/12486709/cc2ca056-c031-11e5-8011-aee060ab835a.PNG)

The [documentation](http://yhat.github.io/rodeo-docs/docs/#oh-no-something-went-wrong) states that double slashes are required when setting the path manually, but it is not mentioned in regards to this splash screen. If the intent is for the splash screen to accept paths with single slashes, then there seems to be a bug. If not, I'd add a note to say that double slashes are also required on the splash screen.

**Comment by glamp** [comment]
This will be fixed in 1.3. We're making this a "file-picker" instead of a paste in your path as it is today

**Comment by glamp** [comment]
a442ec77bb2648b8d0c64bd5056a9bf96d15bbc0
