### ISSUE TITLE
Rodeo fails to open if working directory has been removed since last sessions

### ISSUE THREAD

**Issue by nbara** [yhat/rodeo#226]
1. Close Rodeo
2. Delete/Move your previous default working directory
3. Open Rodeo

Lo and Behold
<img width="532" alt="screen shot 2016-01-26 at 12 08 07" src="https://cloud.githubusercontent.com/assets/10333715/12579095/906cb194-c425-11e5-9217-912b7f62e492.png">

**Comment by glamp** [comment]
Will be fixed in 1.3 which is out this week.

**Comment by glamp** [comment]
9ac9a6f29999fa62ec90cc86f18f91cad4e51cc4
