### ISSUE TITLE
Each file save slower than preceding one, slowly becomes unusable (Rodeo 1.0, Mac OS 10.11.2)

### ISSUE THREAD

**Issue by jreades** [yhat/rodeo#227]
I can't see anything in the system logs to tell me what is going on, but have found that each time I save a set of edits to a file the save process becomes slower until the UI becomes completely unresponsive. It could be some kind of race condition between the automatic saves and my habit of saving frequently, but at a certain point a force quit seems to be the only way to recover. Will keep an eye on the logs to see if anything useful comes up but it's definitely unique to Rodeo on this computer and have seen similar behaviour on my desktop (again, a Mac running 10.11.2) at work.

Lots to love about Rodeo but this is a real problem for me at least.

**Comment by glamp** [comment]
Do you have "autosave" mode enabled?

**Comment by jreades** [comment]
I was about to say ‘yes’ because I was fairly certain that I had, but it turns out that according to Rodeo’s Editor prefs I don’t.

**Comment by glamp** [comment]
i can't reproduce. do you have explicit steps you could give me?

**Comment by jreades** [comment]
I’ll try to get to this as soon as I can — I’m in the middle of a heavy bit of teaching (3 weeks to go!) and so don’t have much time to ‘faff’ but I won’t forget and will try to get you any relevant params/logs when I next have a moment to work on my research. I’m keen to see if I can dump Canopy in favour of Rodeo because it’s a better UI and a closer to the code, so I will definitely be doing work in Rodeo going forward and if the problem recurs I will know about it!

jon

> On 9 Feb 2016, at 15:34, Greg Lamp <notifications@github.com> wrote:
> 
> i can't reproduce. do you have explicit steps you could give me?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yhat/rodeo/issues/227#issuecomment-181916555>.
> 

--
Jon Reades

m: 07976.987.392
e: jon@reades.com <mailto:jon@reades.com>
im: jereades

**Comment by jreades** [comment]
HI Greg — I’ve done some more investigating and I suspect it’s actually something in Electron or the Rodeo Helper that is giving me issues as opposed to the file-saving process. I’ve got some screen shots from top at the time but am wary of just posting those to GitHub, but I see Electron using 72.2% of the CPU and Rodeo Helper using 89.1% in one screenshot, and 81.0% and 96.5% in another. Both when I’m doing basically nothing at all.

I’ve just now remembered that PyCharm displayed similar behaviour for me: consumed basically all CPU resources and caused the fans to come to life (when even running big queries in PostGIS/Postgres rarely does that). So it might be something about my system but I can’t figure out what as I’ve actually reinstalled Python from brew to set up a clean distribution to use with Rodeo and python scripts don’t seem to display the same behaviour.

jon

**Comment by glamp** [comment]
ok sorry to hear that. going to close since seems like it's not a Rodeo issue
