### ISSUE TITLE
Windows 10: Rodeo fails to recognize local matplotlib installation

### ISSUE THREAD

**Issue by rrane** [yhat/rodeo#228]
Rodeo keeps giving me the same startup error to install matplotlib. I have been using spyder until now and have had no issues with my matplotlib installation until now. A reinstall or downgrade of matplotlib didnt work either. 

Is there an alternative location I should install matplotlib than the default conda installation location? 
Also Rodeo couldn't recognise python initially either and required giving double slashes as opposed to single slashes as in the program.

Thanks a lot for your help! Screen capture is as below:

![image](https://cloud.githubusercontent.com/assets/4378726/12700572/f33d0d30-c83c-11e5-9872-e2e78b956065.png)

**Comment by glamp** [comment]
matplotlib is no longer a dependency (as of 1.3.0). going to close
