### ISSUE TITLE
Tab for docstrings

### ISSUE THREAD

**Issue by kevindavenport** [yhat/rodeo#229]
Is there a way to hit shift+tab or any other combo to see the docstrings for a given function similar to what tab does in IPython notebook?

**Comment by bagasabisena** [comment]
Hi, would like to as well whether this has been implemented or is planned for future releases

**Comment by glamp** [comment]
will be in 1.3 (Feb 15th)

**Comment by glamp** [comment]
Sneak peak :smile: 

![image](https://cloud.githubusercontent.com/assets/1409333/13028839/d7b191ec-d248-11e5-97e3-b90429f0df32.png)

**Comment by glamp** [comment]
1.3.0 is out. closing!

**Comment by kevindavenport** [comment]
The entire popup comes up during typing? or did you have to hit something to invoke. If it comes up automatically for each letter, I think it would be distracting/costly.

**Comment by glamp** [comment]
No not during typing, you have to hit tab.
