### ISSUE TITLE
Windows 8.1 64 Bit JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by BlackArbsCEO** [yhat/rodeo#230]
Big fan of the Rodeo IDE. It was working fine initially but recently when I try to run the program I get the following error:

![rodeo java error](https://cloud.githubusercontent.com/assets/7452471/12859164/8b749924-cc11-11e5-95ec-0cd3189a101b.png)

Please advise.

**Comment by glamp** [comment]
It's possible that your python process is taking a "longer than expected" to startup. Try waiting after startup for a few seconds before running a command.

This will be fixed in the next release (1.3) which will be out this week.

**Comment by glamp** [comment]
a442ec77bb2648b8d0c64bd5056a9bf96d15bbc0

**Comment by BlackArbsCEO** [comment]
I downloaded the new version of rodeo 1.3. When I try to start it I get the following error pop up and then the "Starting Up" window just hangs and the IDE is unusable. Please advise.

![rodeo java error v1 3](https://cloud.githubusercontent.com/assets/7452471/13063174/91dd7b48-d402-11e5-8804-77fa0fc45be8.png)

**Comment by ihollaback** [comment]
I just downloaded Rodeo yesterday and got the same error as BlackArbsCEO.

![image](https://cloud.githubusercontent.com/assets/8344183/14149993/e10690c6-f674-11e5-890a-9ecfb75fa6e0.png)
