### ISSUE TITLE
.rodeorc overrided with default fontType on Rodeo launch

### ISSUE THREAD

**Issue by nikiluk** [yhat/rodeo#232]
The .rodeorc file is overrided each time with "fontType": "Helvetica Neue" property. This leads to inability to save the Font property and use it automatically during the next launch of Rodeo instance. Besides, fontSize property is not overrided and could be saved.

After .rodeorc saved (manually edited in Notepad++ or in Rodeo)
`{
  "id": "6bb3ac40cf3d11e5baac63f6c3185857",
  "fontType": "Consolas",
  "version": "1.2.1",
  "paneVertical": "46.661490683229815%",
  "paneHorizontalRight": "46.685472496473906%",
  "paneHorizontalLeft": "46.685472496473906%",
  "pythonCmd": "C:\\Users\\Nikita\\Anaconda3\\python.exe",
  "defaultWd": "C:\\Users\\Nikita\\Dropbox\\_CODE",
  "theme": "css/styles-presentation.css",
  "fontSize": 16,
  "displayDotFiles": true,
  "editorTheme": "ace/theme/github",
  "trackingOn": true,
  "autoSave": true
}`

After Rodeo session is restarted
`{
  "id": "6bb3ac40cf3d11e5baac63f6c3185857",
  "fontType": "Helvetica Neue",
  "version": "1.2.1",
  "paneVertical": "45.88509316770186%",
  "paneHorizontalRight": "46.5444287729196%",
  "paneHorizontalLeft": "46.5444287729196%",
  "pythonCmd": "C:\\Users\\Nikita\\Anaconda3\\python.exe",
  "defaultWd": "C:\\Users\\Nikita\\Dropbox\\_CODE",
  "theme": "css/styles-presentation.css",
  "fontSize": 16,
  "displayDotFiles": true,
  "editorTheme": "ace/theme/github",
  "trackingOn": true,
  "autoSave": true
}`

**Comment by berlinluk** [comment]
agree. this is a bug

**Comment by TakenPilot** [comment]
This is fixed in the new pre-release version of Rodeo, since we're using a different way to save these settings that makes persistence _much_ easier than before.  We'll be releasing a new major version in the next week or two that will include this fix.
