### ISSUE TITLE
How can I get Rodeo to set the current working directory as that of the current script?

### ISSUE THREAD

**Issue by izaakm** [yhat/rodeo#233]
This is important to me because I work with scripts on two different machines.

Given the following script located at "/path/to/my-script.py":

    import os
    import sys
    print os.path.dirname(sys.argv[0])
    print os.getcwd()

When I run this in the Rodeo IDE, I get this output:

    /usr/local/lib/python2.7/site-packages/ipykernel
    /usr/local/lib/python2.7/site-packages/ipykernel

But what I expect, and when I run this from Terminal, is something like the following:

    $ python /path/to/my-script.py
    /path/to
    /Users/home

Rodeo v1.2.1
OSX 10.11.3

**Comment by AlJohri** [comment]
I have a similar issue where if I run:

```
>>> !pwd
/
```

then

```
>>> !cd ~

>>> !pwd
/
```

also

```
>>> !cd /Users/johria/

>>> !pwd
/
```

**Comment by glamp** [comment]
I'm assuming you're launching Rodeo from the OSX Dock?

You can switch working directories form the preferences tab
![image](https://cloud.githubusercontent.com/assets/1409333/13218693/01bfe242-d94a-11e5-8b0a-352fb5291f61.png)

Though there is a bug in that the console doesn't also switch #176 (working on this :smile:)

To switch the console, you can just run `cd` as you normally would.
![image](https://cloud.githubusercontent.com/assets/1409333/13218711/21dfe568-d94a-11e5-9741-078a7018c552.png)

To set the default working directory for the console and the file picker, go to *Preferences > Default Working Directory*

![image](https://cloud.githubusercontent.com/assets/1409333/13218732/3c1ca768-d94a-11e5-8737-e16fa5912854.png)

**Comment by izaakm** [comment]
Yes, I'm opening Rodeo from Finder. 

Once I open this example script in Rodeo, and set/change directories as you have indicated, I still don't get the expected output in relation to using `sys.argv[0]`; below is the console output:

```
>>> import os 
... import sys 
...  
... print os.path.dirname(sys.argv[0]) 
... print os.getcwd() 
... 
/usr/local/lib/python2.7/site-packages/ipykernel
/Users/username/temp
```

![screenshot 2016-02-22 10 18 12](https://cloud.githubusercontent.com/assets/1505395/13222366/ad894df4-d94d-11e5-9bc0-dcc3402a4d62.png)

**Comment by glamp** [comment]
take a look at the new release (2.4+). should answer all these questions!

![image](https://cloud.githubusercontent.com/assets/1409333/18955045/a8fc6aae-8623-11e6-981f-82782bdbe4e8.png)
