### ISSUE TITLE
Rodeo (Windows) hangs, CPU core maxes out for seemingly no reason 

### ISSUE THREAD

**Issue by michaelwsherman** [yhat/rodeo#238]
I'm seeing periodic hangs in Rodeo. They seem to happen when I'm interacting with the code window in the GUI--scrolling, highlighting, switching files, etc.

The hangs are characterized by watching the Rodeo process shoot to 25% CPU in Task Manager (that's one core) and watching the memory usage slowly tick up, about 10k per second. After a few minutes, the hang will end, but then it will intermittently start again usually a few minutes late.

I have a 16GB machine, so I don't think the issue has anything to do with memory usage (I'm seeing 52% Physical Memory utilization in Task Manager).

I'm running Win 7, SP 1, 64-bit. Processor is i5-3570 @ 3.4 GHz . Autosave is off.

Let me know what other information is needed, or anything I should try, and I'll be happy to oblige.

Thank you.

**Comment by bryancshepherd** [comment]
Seeing the same thing recently on my Windows 10/64-bit machine. As @michaelwsherman noted, it tends to happen when interacting with the editor windows. I don't think I noticed it prior to upgrading to 1.3, but I'm not sure about that.

**Comment by michaelwsherman** [comment]
I haven't upgraded to 1.3, so it existed in the prior version.

**Comment by varoudis** [comment]
One core is always full on a MacBook Retina 2015 with latest OSX too.
Seems like the Rodeo package manager needs probing.

**Comment by kmatt** [comment]
Could be an Electron issue? https://github.com/atom/atom/issues/6437

**Comment by boral** [comment]
Rodeo takes up so much CPU on Windows. Please minimize it. And I am also facing the occasional hangs.

**Comment by TakenPilot** [comment]
Changing over to using the React and Redux frameworks reduces the CPU usage of the node and browser parts of the app, but the main part causing the high CPU usage is still around.  I'm looking at different ways to deal with this right now.

**Comment by TakenPilot** [comment]
Finally!  Introducing CPU back-off in the 2.0.2 version should make all the CPU issues disappear.  Closing this.
