### ISSUE TITLE
Version number is not accurately reflected in 'About'

### ISSUE THREAD

**Issue by bryancshepherd** [yhat/rodeo#239]
After downloading and installing the Rodeo-v1.3.0-windows_64.exe file available here:

https://www.yhat.com/products/rodeo/downloads/windows_64

the version number displayed in Rodeo > About Rodeo is still 1.2.1. 

Help > Check for Updates gives a "You're up to date" message.

**Comment by glamp** [comment]
That is very strange as the version number comes directly from the package.json file. Did you previously have v1.2.1 installed? If not, then that's even stranger :ghost:

**Comment by bryancshepherd** [comment]
Yes, 1.2.1 was previously installed.

**Comment by bryancshepherd** [comment]
It looks like the .rodeorc file in my users folder didn't get updated. There's a 'version' parameter there that still says 1.2.1 and seems to be the source for the version number in Rodeo > About.

**Comment by kmatt** [comment]
Had same issue, deleted .rodeorc, upon restart it now reports v1.3

**Comment by TakenPilot** [comment]
This issue has been fixed in the latest pre-release version.  The fix will be included in the major version launching later this month.
