### ISSUE TITLE
vim keybindings may be killer feature

### ISSUE THREAD

**Issue by matthew-brett** [yhat/rodeo#24]
Very nice indeed - I agree with you that this fills a gap between the full notebook experience and development using a proper text editor.

Good bindings for vim are a feature that the ipython notebook can't easily provide, and it would be very attractive for us clumsy-in-notebook vim users if these were easy to enable for rodeo.

**Comment by glamp** [comment]
super easy. i'm going to add a preferences tab and i'll make sure this is one of them.

**Comment by matthew-brett** [comment]
Great - thanks - looking forward to it...

**Comment by glamp** [comment]
done in bc55604c34eb1621be566d4e18ccae0d1c16f4d3

**Comment by matthew-brett** [comment]
Nice - thank you!
