### ISSUE TITLE
pip package maintenance

### ISSUE THREAD

**Issue by bpirvu** [yhat/rodeo#241]
I just started using rodeo in the browser (i.e. not in standalone mode) and it works as expected.

I installed the pip package (https://pypi.python.org/pypi/rodeo) on my Ubuntu 14.04 remote server and I noticed that that package is quite outdated (v.0.4.4 from Sept. 2015) compared to the released standalone version, which seems to be at least at v1.0.0 (http://blog.yhat.com/posts/rodeo-native.html).

My question is: is it planned to maintain / regularly update the pip package, or do you plan to release rodeo only in standalone mode in the future?

**Comment by glamp** [comment]
No the pip version will not continue to be developed.

Are you looking for a server-based IDE?

**Comment by bpirvu** [comment]
Yes, exactly!

I'm using Spark on an Ubuntu server without desktop environment and I must be able to edit the files directly on the server. Until now I've been using Jupyter notebooks, but I'm not very happy with the workflow that results from using notebooks, so I thought I give Rodeo a try...

Is there an alternative to the pip version?

**Comment by glamp** [comment]
pip has been officially deprecated

going to close as this is really the "Rodeo on a server" question
