### ISSUE TITLE
Restart session kills unsaved files

### ISSUE THREAD

**Issue by klancaster** [yhat/rodeo#243]
Restarting a session with a script file unsaved loses all the unsaved changes. The application should prompt the user to save or discard unsaved changes before restarting.

**Comment by glamp** [comment]
What version are you running? Anything after 1.0 should prompt you before restarting your session.

**Comment by klancaster** [comment]
I'm running 1.3 and did not get a warning. I am seeing javascript errors at times when I try to quit the program - any chance that it might be related?

**Comment by glamp** [comment]
Yes do you have a screenshot or the error messages?

**Comment by klancaster** [comment]
I'll get a screenshot the next time it happens and upload it. Its not consistent.

**Comment by TakenPilot** [comment]
This should be impossible in the latest pre-release version on Github.  The fix will be included in the next major version being released later this month.
