### ISSUE TITLE
While running code, prompt symbol remains visible, even though code runs synchronously

### ISSUE THREAD

**Issue by rforgione** [yhat/rodeo#245]
Hi all,

I noticed that when running code in the Rodeo REPL, the prompt symbol shows up even while code is running synchronously. Subsequent inputs to the REPL are unresponsive until the initial code finishes running. See below:

![](http://recordit.co/nxIgSarMps.gif)

In contrast, this is how RStudio handles it:

![](http://recordit.co/viJcinxzQs.gif)

**Comment by gwerbin** [comment]
Not only RStudio, but the R GUI, IDLE, IPython, Juptyer, Bash, and Zsh...

**Comment by rforgione** [comment]
Yep, fair point @gwerbin.

**Comment by TakenPilot** [comment]
This is fixable.  There are "busy" and "idle" events we can listen for to disable or enable the prompt.  I'll probably be working on this exact feature tomorrow as I add visual improvements to the console.

**Comment by TakenPilot** [comment]
This is done in the latest pre-release version.  When the release comes out next week, this will be included.
