### ISSUE TITLE
Printing special character crashes the console

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#252]
When I try `print("°")` the console hangs.  Hoping there is a simple fix for this.

**Comment by TakenPilot** [comment]
This seems to work now in [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3)

<img width="920" alt="screen shot 2016-08-26 at 12 20 36 am" src="https://cloud.githubusercontent.com/assets/4154804/17994003/f813bad2-6b22-11e6-8e42-06989afbaa8f.png">
