### ISSUE TITLE
[ Feature Request ] Able to Resize console cursor size

### ISSUE THREAD

**Issue by boral** [yhat/rodeo#255]
The width of console cursor is too large. Please add an option to enable users to use a thinner cursor in console.

The thick cursor blocks the view as exactly where the cursor is and this leads to typing in the wrong area.

**Comment by TakenPilot** [comment]
Thanks for the feature request!  We're currently using jqconsole for our console implementation, and they don't have a blinking cursor implementation.  We could override their css to make a smaller cursor, but without blinking it will be almost invisible on a user's screen.
