### ISSUE TITLE
Ubuntu PPA?

### ISSUE THREAD

**Issue by brendan-r** [yhat/rodeo#256]
Firstly, thanks so much for Rodeo!

An Ubuntu PPA / .deb repo would be fantastic, and make updating _much_ easier/automatic. The Ubuntu equivalent of (#6).

**Comment by coristig** [comment]
hey @brendan-r 

Just added support for this (doing final testing now).  Running commands below should add the .deb repo and install.

```{bash}
# add the yhat public key and add the repo
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 33D40BC6
sudo add-apt-repository -u "deb http://rodeo-deb.s3.amazonaws.com/ rodeo main"

# install rodeo and run it
sudo apt-get -y install rodeo
/opt/Rodeo/Rodeo
```

Let me know if this works / doesn't.  Appreciate the feedback!

**Comment by brendan-r** [comment]
Seems to work, thanks!
