### ISSUE TITLE
Issues with non-standard anaconda path OSX 10.10.5

### ISSUE THREAD

**Issue by alexpkeil1** [yhat/rodeo#257]
I have anaconda at a non-standard path (/usr/local/anaconda). Rodeo seems to "forget" where anaconda python is, so I have to remind it about 75% of the time when I open it (can't figure out why it works sometimes). 

Install via Conda also does not work (fails with message "/bin/sh: conda: command not found")

Terminal output here shows that python and conda are easily accessed outside of Rodeo:

`which python`
/usr/local/anaconda/bin/python

`conda --version`
conda 4.0.5

**Comment by TakenPilot** [comment]
I can reproduce this bug, and this is fixed in the upcoming release.

**Comment by TakenPilot** [comment]
Yeah, I just merged the code that looks at `which python` tonight, so the next release will have this fixed.
