### ISSUE TITLE
Javascript errors on startup (OS X 10.10.5)

### ISSUE THREAD

**Issue by perrygeo** [yhat/rodeo#258]
I wipe my `~/.rodeo*` files, download and install 1.3 and this is the first two dialog boxes I see
<img width="476" alt="screen shot 2016-03-24 at 10 11 33 pm" src="https://cloud.githubusercontent.com/assets/1151287/14036278/f1dbdfca-f20d-11e5-9eaf-cc92a63a0b35.png">
<img width="447" alt="screen shot 2016-03-24 at 10 11 39 pm" src="https://cloud.githubusercontent.com/assets/1151287/14036282/f855b146-f20d-11e5-952f-e65d4a8aeeb4.png">

then go to change my python path
<img width="576" alt="screen shot 2016-03-24 at 10 12 01 pm" src="https://cloud.githubusercontent.com/assets/1151287/14036335/4a46cf80-f20e-11e5-8ccf-7c89a7d6c686.png">

**Comment by TakenPilot** [comment]
[Rodeo 2.0.0](https://github.com/yhat/rodeo/releases/tag/v2.0.0) contains the stability fixes for this issue.
