### ISSUE TITLE
default working directory doesn't actually work

### ISSUE THREAD

**Issue by hernamesbarbara** [yhat/rodeo#265]
This is my default working directory:

![image](https://cloud.githubusercontent.com/assets/738191/14723995/bff98ff4-07e1-11e6-886e-5f3374e7b13e.png)

But when I log in, these are the files I see in the UI

![image](https://cloud.githubusercontent.com/assets/738191/14724009/ca821568-07e1-11e6-8aa3-e54e4c1cf440.png)

this tells me that Rodeo.app is not respecting my preferred default working directory.

**Comment by TakenPilot** [comment]
I can reproduce this bug, and this is fixed in the upcoming release.

**Comment by TakenPilot** [comment]
Or at least it's more consistent.

There are two working directories: one for the ipython instance, and one for the file viewer.  I'm trying to figure out the best way for them to interact.  Any ideas?

**Comment by TakenPilot** [comment]
Fixed in latest on master, so v1.4.10 will have these changes.
