### ISSUE TITLE
Rodeo keeps freezing

### ISSUE THREAD

**Issue by aw236** [yhat/rodeo#271]
While I love the concept, I can't get Rodeo to work for me.

Rodeo is able to load up fine as well as run code. However, it frequently freezes while I'm coding, even when just starting. Sometimes I can code for 5 minutes straight before a productivity-halting freeze. Additionally, if I alt-tab away then alt-tab back, it will be frozen and unresponsive with 100% certainty. It takes anywhere from 5 seconds to several minutes before it becomes responsive. 

I tried working with IDLE and Terminal but can't replicate the issue so I'm sure this is particular to Rodeo.

I am running OSX El Capitan 10.11.4, Python 2.7.11, and Rodeo v1.3.0. My system specs:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

**Comment by newhotter** [comment]
nobody here.  Anyone?

**Comment by glamp** [comment]
There is a bug in Electron that causes the app to freeze when `sendSync` is called. It doesn't happen every time, but it happens enough on certain machines (i.e. yours).

We're in the middle of fixing this (and many other issues) right now. There is a release slotted for May ~10th that will include these fixes.

**Comment by natalieklein** [comment]
I have the same issue and really look forward to it being fixed because otherwise I like Rodeo!

**Comment by TakenPilot** [comment]
The pre-release removed all the things that were causing Rodeo to freeze randomly, at the cost of some of our features.  In a week or two we're going to launch a new major version that will include the fix.
