### ISSUE TITLE
JS error starting Rodeo on OS X Yosemite

### ISSUE THREAD

**Issue by MHaringa** [yhat/rodeo#272]
I am getting the following error message when I start Rodeo:

![Error starting Rodeo](https://cloud.githubusercontent.com/assets/12985683/15010770/2949258a-11ee-11e6-817d-e69c14391da1.png)

Any suggestions to solve this?

**Comment by TakenPilot** [comment]
I can reproduce this error.  It occurs when python produces output that isn't expected, and the current release isn't very good about handling unexpected things.  There is going to be a new release (and a beta) this month that will address a lot of these stability issues.

**Comment by coristig** [comment]
@MHaringa can you try downloading the latest release here and see if that fixes things?

https://github.com/yhat/rodeo/releases

**Comment by MHaringa** [comment]
Great! Problem is solved.

2016-06-09 16:19 GMT+02:00 coristig <notifications@github.com>:

**Comment by glamp** [comment]
🎸
