### ISSUE TITLE
Javascript error while fitting xgboost in Rodeo

### ISSUE THREAD

**Issue by boral** [yhat/rodeo#278]
I was fitting xgboost model on a dataset in Rodeo. But whenever I am trying to fit the model I get the following error. Please help.
![capture](https://cloud.githubusercontent.com/assets/12884971/15224568/d7543ffc-1897-11e6-9f2e-db3add9fe95c.PNG)

**Comment by TakenPilot** [comment]
This error is thrown when python produces unexpected output in some way that we're not capturing.  

The new version (1.4.x) addresses this in most cases, but I had to build a lot of the pieces from scratch to gain that stability.  I'm in the process of adding the features back now though.

**Comment by TakenPilot** [comment]
The issue has been fixed in the recent version in master, so marking the issue as closed.  When we release the new major version this month, the fixes will be included.
