### ISSUE TITLE
Changing fonts bug

### ISSUE THREAD

**Issue by rainman28** [yhat/rodeo#289]
Dear developers,

I have noticed that changing fonts in the settings does not work smoothly. Firstly, the font size sometimes changes, and, secondly, cursor appears at some distance from the place where I am typing after I change the font. Last but not least, the setting seems to affect all the fonts in the interface, whereas people often want to change only the font of the code.

Also, it would be very nice to have access to the entire collection of system fonts - there was no way for me to select Monaco as the default font for code.

(I am trying out Rodeo on OS X 10.11.5.)

Thank you,
Artur

**Comment by TakenPilot** [comment]
Thanks for the feedback!

I'm trying to reproduce the the bug where the cursor appears in a different spot from the typing.  Is this happening in the console or the file editor?

Agreed, having access to all the fonts would be really convenient.  There is a current limitation of the editor that we are using that the font must be monospaced, but that seems to be the only limitation.

**Comment by rainman28** [comment]
Thank you! It does occasionally happen in the editor.

**Comment by glamp** [comment]
fonts have been consolidated! 👍 ergo issue is fixed
