### ISSUE TITLE
make panes resizable

### ISSUE THREAD

**Issue by glamp** [yhat/rodeo#3]
Be able to have 4 panes that are resizable.

**Comment by glamp** [comment]
@coristig what was the one you found?

**Comment by glamp** [comment]
@coristig  your thoughts...

**Comment by roshannair** [comment]
+1
At the moment, editing windows are really cramped. If not resizable panes, it would be really nice to have alternative layouts. For eg:- editor on left and ipython console on right, and the plot and dataframe panes hidden.

Thanks for the excellent work putting this together! Very helpful.
