### ISSUE TITLE
Clearing console doesn't clear plots in the console

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#312]
Using Rodeo 1.4.5

using ctrl + l to clear the console, I get something like:

![image](https://cloud.githubusercontent.com/assets/7118371/15757256/afdf9714-28d2-11e6-927c-5f4e962e9664.png)

Then after typing cmd + l, I get:

![image](https://cloud.githubusercontent.com/assets/7118371/15757270/c69615a0-28d2-11e6-89ed-9b13ce749275.png)

**Comment by TakenPilot** [comment]
Are those plots iframes (html or scripts) or images?

**Comment by TakenPilot** [comment]
This has been fixed in v1.4.7
