### ISSUE TITLE
Rodeo is not saving python path setting

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#313]
Version: Rodeo 1.4.5
OSX 10.11.5

I can change my python path to "//anaconda/envs/datasci/bin/python" in Rodeo's preferences but every time I close and re-open Rodeo it gets reset to "/usr/bin/python"

**Comment by TakenPilot** [comment]
Fixed with that merge.  New version this weekend will contain fixes currently now in master.

**Comment by ben519** [comment]
You da man, Dane!

**Comment by BrianMiner** [comment]
Same issue with linux version 2.1.4. There were many issues installing because the path was not set correctly as well. Are there instructions from installing from source (github)?

**Comment by thigm85** [comment]
Same issue with mac version 2.2.0. Every time I initialize Rodeo I have to state my python path.
