### ISSUE TITLE
Executing any code in the console while python path setting is incorrect crashes Rodeo

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#314]
Version: Rodeo 1.4.5
OSX 10.11.5

Rodeo's default path "/usr/bin/python" is incorrect for my setup.  If I execute something in the console without fixing this first, Rodeo crashes.  Can anything be done to prevent Rodeo from crashing here?  At least an error message would be nice.

**Comment by TakenPilot** [comment]
Rodeo doesn't really have a default path.  It should be using the setting in your preferences.  If there is no setting in your preferences, or if the setting in the preferences doesn't work, then it tries to auto-detect your python.

The auto-detection works like this: it takes a bunch of paths that are typical python paths (/usr/bin/python, /usr/local/bin/python, ~/anaconda/bin/python, etc.), runs them all, and then whichever ones work, it takes top of the list and uses that, and that becomes your new setting in your preferences.

Where is your python path?  I could add it to the list?  Also, how are you fixing it?

**Comment by ben519** [comment]
The path I want to use is //anaconda/envs/datasci/bin/python, and Rodeo works when I set this path manually in the preferences.

My issue is more regarding Rodeo's behavior.  This was basically my experience:
1) Install Rodeo
2) Open Rodeo
3) Enter a command in the console (e.g. 1 + 1)
4) Rodeo console freezes.  No error messages or apparent way to unfreeze the console

I was able to debug the issue and figure out that I needed to change my python path in the settings.  I think the console was freezing because the path Rodeo selected for me did not have Jupyter installed.

**Comment by TakenPilot** [comment]
That's probably exactly what happened.  The console was waiting for an update from python that never came.

I'm doing two things:
1)  Not overriding a person's path if they set it.
2)  Having the detection of python time out and give an error message when something bad happens.

**Comment by TakenPilot** [comment]
I'm also adding the command `which python` to the list of places to look for python, and making that really high priority in the list.  That should catch your case.
