### ISSUE TITLE
The "Check for updates" button doesn't have a response

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#317]
Version: Rodeo 1.4.5
OSX 10.11.5

As of now, I think I'm on the newest version of Rodeo, so I'd expect a message like "Your version is up to date", but I'm not receiving any message.

**Comment by TakenPilot** [comment]
Ah, that's true!  

I removed the notification dialog of "You're on the current version." because it was showing up whenever we checked for an update, and it was getting annoying.  I'll add it back in for when a person checks for updates from the application menu.
