### ISSUE TITLE
Store plots files in tmp dir outside of package directory

### ISSUE THREAD

**Issue by kjford** [yhat/rodeo#33]
Running into trouble plotting with the following error:

    IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/rodeo/static/plots/1429821893-f96713d9-3684-44b6-8f44-88ef98f9e592.png'

I had to pip install rodeo with sudo but running rodeo as other than su won't allow writing to the site-package directory.  Is it possible to stash tmp files someplace else that has write access by the user?  Or cmod the plots directory to allow writing by non-owners?

**Comment by glamp** [comment]
What version are you running? This should be fixed in https://github.com/yhat/rodeo/commit/4e5c43020710f12e91713e8aa4cae08256c5db65

**Comment by glamp** [comment]
oh wait i see the problem. i can fix that.

**Comment by kjford** [comment]
> What version are you running? 

0.2.1

from `kernel.py`:

    __dirname = os.path.dirname(os.path.abspath(__file__))
    ....
    def __hijack_plots():
        fname = "{__dirname}/static/plots/%d-%s.png" % (int(time.time()), str(uuid.uuid4()))
        plt.savefig(fname)

**Comment by kjford** [comment]
Thanks.  And love the idea of this IDE.

**Comment by JanSchulz** [comment]
https://github.com/yhat/rodeo/issues/34#issuecomment-95880854 would fix this as well :-)

**Comment by glamp** [comment]
1f6cbe91ccbc8c78bd1f33fa6247008a7039d713
