### ISSUE TITLE
All themes can not be changed on ubunutu 16.04

### ISSUE THREAD

**Issue by xiekunwhy** [yhat/rodeo#332]
Themes can not be changed in version 1.4.9
![2016-06-10 00-13-33](https://cloud.githubusercontent.com/assets/17738229/15937236/968a5532-2ea0-11e6-8886-1df919afeab0.png)
![2016-06-10 00-13-47](https://cloud.githubusercontent.com/assets/17738229/15937235/9649b40a-2ea0-11e6-995c-0a40cc144239.png)

**Comment by TakenPilot** [comment]
That's true.  We had to take a lot of features out to address the stability issues first.  We're planning to add this back in later.
