### ISSUE TITLE
Allow "enter" button to submit forms on startup

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#339]
Source: http://discuss.yhat.com/t/rodeo-2-0-looks-like-we-cant-find-python/38

We should allow "enter" key to submit forms on Rodeo startup

**Comment by TakenPilot** [comment]
In [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3), enter presses you!

It just closes the window automatically when the main window is ready.
