### ISSUE TITLE
plotting dataframes using df.plot() does not work?

### ISSUE THREAD

**Issue by trtg** [yhat/rodeo#34]
So far the only plotting that seems to work for me (using chrome on osx) is ggplot. Trying to directly plot a dataframe does not see to generate anything in the plots tab. Am I missing something? Perhaps some configuration setting?

**Comment by kjford** [comment]
try:

    import pylab as plt
    plt.show()

**Comment by glamp** [comment]
can you share your code?

@kjford is right. we hijack the `plt.show()`, so plots generated by some other means won't work

**Comment by JanSchulz** [comment]
I think it would make more sense to use the iypthon display machinery:

* accept `display_data` (together with execute_result) in _run_code and check the `image/png` mimetypes (or others), which has a uuencode png file as content, which can be displayed via `<img src:"data:<content>">` (from the top of my head...) -> See here for similar code in knitpy: https://github.com/JanSchulz/knitpy/blob/master/knitpy/knitpy.py#L536
* send a `%matplotlib inline` during kernel startup, to capture all matplotlib file. 

This will also make it possible to capture plots from non-matplotlib plotting libs like igraph

**Comment by glamp** [comment]
:+1: that seems like a good idea

**Comment by glamp** [comment]
should be fixed 9327375798478ed9446db1f47d1e12bf6e5b1f9c
