### ISSUE TITLE
Changing editor style in Rodeo 2.0?

### ISSUE THREAD

**Issue by Danderssen** [yhat/rodeo#341]
Is there still a way to change the style of the editor window in Rodeo 2? I can't find any option in the settings.

Thanks!

**Comment by stsievert** [comment]
That'd be nice... I don't like the serif font used in the control items.

**Comment by TakenPilot** [comment]
There will definitely be themes again, but I had to temporarily pull that out to get everything rebuilt in a stable way quickly.

**Comment by TakenPilot** [comment]
-> http://discuss.yhat.com/t/some-feature-is-missing/63
