### ISSUE TITLE
Rodeo cannot be opened (2.0.0 Mac)

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#343]
Unable to open Rodeo 2.0.0 from Mac os Spotlight. The error shown is "The application “Rodeo” can’t be opened."

Following are the logs from syslog
Jun 15 15:15:26 Udays-iMac lsd[304]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
Jun 15 15:15:26 --- last message repeated 1 time ---
Jun 15 15:15:26 Udays-iMac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000002a.Electron[97105]): Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Rodeo.app/Contents/MacOS/Electron
Jun 15 15:15:26 Udays-iMac Finder[310]: spawn_via_launchd() failed, errno=111 label=[0x0-0xae1ae1].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
Jun 15 15:15:26 Udays-iMac Finder[310]: spawn_via_launchd() failed, errno=111 label=[0x0-0xae1ae1].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1
Jun 15 15:15:26 Udays-iMac lsd[304]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist

**Comment by TakenPilot** [comment]
It seems to be an issue with the `lsd` process:

- https://discussions.apple.com/thread/7558756
- https://github.com/Microsoft/vscode/issues/92
- http://apple.stackexchange.com/questions/220562/what-is-the-lsd-process-on-os-x-and-why-is-it-using-so-much-cpu-power
- https://github.com/arduino/Arduino/issues/4314

That first one seems to be the most likely to fix this specific issue.  They're saying to run this command and then restart:
```bash
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.fram ework/Support/lsregister -kill -r -domain local -domain system -domain user ; killall Dock
```

**Comment by sawantuday** [comment]
This happens only when the App is opened with Spotlight or from Applications directory. When started from the mounted installation disk, Rodeo 2.0 works well (double click instead of drag to Applications).

May be this is related with older version of Rodeo. I had 1.3.0 installed which got replaced with Rodeo 2.0.0

**Comment by TakenPilot** [comment]
Oh!  In that case, it might be related to this:  https://github.com/yhat/rodeo/issues/301

**Comment by sawantuday** [comment]
Looks like the issue came back! I already tried creating symlink which results in damaged installation. I also tried a reboot that didn't worked either
![screen shot 2016-06-15 at 9 50 52 pm](https://cloud.githubusercontent.com/assets/2276220/16088328/2e66d11c-3344-11e6-884e-aa5db3b4f791.png)

As an additional info I am on MacOS 10.11 El Capitan.

**Comment by TakenPilot** [comment]
So weird.  What happens if you try to run the reinstalled app with sudo or from another user?

**Comment by sawantuday** [comment]
When started with following commands App starts normally (Same user without sudo). 
```
$ cd /Applications 
$ ./Rodeo.app/Contents/MacOS/Rodeo
```
Plus, splash screen shown warning, Fail to load `/extensions/mathMenu.js` and `/extensions/mathZoom.js.`

**Comment by davechallis** [comment]
Had the same issue (i.e. Rodeo wouldn't start, error messages in logs related to Electron), adding the fix from #301 and then removing it fixed things for me, i.e.:

1. `cd /Applications/Rodeo.app/Contents/MacOS/ && ln -s Rodeo Electron`
2. Start Rodeo from Launchpad (this fails with '"Rodeo" is damaged and can't be opened.')
3. `cd /Applications/Rodeo.app/Contents/MacOS/ && rm Electron`
4. Start Rodeo from Launchpad (this time it launches with any problem)

**Comment by TakenPilot** [comment]
@sawantuday  Those error messages are from a feature in 1.x Rodeo that I haven't exposed yet so I could add the stability fixes.  They're harmless, and when I hook up the feature again they'll go away.  Probably everyone is getting those.

**Comment by sawantuday** [comment]
@davechallis No luck, still shows the same message ("Rodeo" is damaged) after removing Electron link. 
@TakenPilot Thank you for details 👍

**Comment by narenreddy** [comment]
I got similar message but when I rebooted my machine(after Rodeo install on Mac) and opened Rodeo for first time from Applications(in Finder). Then afterwards, Spotlight is picking Rodeo like old version.

**Comment by elkbrsathuji** [comment]
restarting\rebooting the machine solved the issue.

**Comment by TakenPilot** [comment]
This issue seems to have been resolved?  If so, I'm going to close it...
