### ISSUE TITLE
Not able to view arrays in 2.0.2

### ISSUE THREAD

**Issue by jolespin** [yhat/rodeo#349]
In the earlier versions, when I initiated an array object I was able to view it.  I can't do that now.  Is this functionality taken out of 2.0.2?

**Comment by TakenPilot** [comment]
Ah, this:  http://discuss.yhat.com/t/some-feature-is-missing/63

**Comment by jolespin** [comment]
was it causing the platform to crash? it was one of the main reasons i used rodeo

**Comment by TakenPilot** [comment]
You can see the roadmap here: [rodeo-feature-roadmap](http://discuss.yhat.com/t/rodeo-feature-roadmap/48)

You're talking about the dataframe view.

**Comment by jolespin** [comment]
Do you think it will be integrated into newer additions? Also, is it possible to download older versions?
