### ISSUE TITLE
File failed to load: /extensions/MathZoom.js(2.0.2 Mac OS11.11.5)

### ISSUE THREAD

**Issue by oucb** [yhat/rodeo#350]
When i open the application, there is a notice on the Lower left corner of the Start interface:
File failed to load: /extensions/MathMenu.js 
File failed to load: /extensions/MathZoom.js

**Comment by ptoche** [comment]
Confirmed on 2.0.4. dmg

**Comment by albertorepo** [comment]
Same on Linux

**Comment by JavierLopatin** [comment]
Same on ubuntu 14.04

**Comment by DerekYves** [comment]
Same on Mac 10.10

**Comment by duyck** [comment]
Same on Mac OS X 10.11.5. Also seems to be missing preferences and help tab in lower right (Files, Plots, Packages) window. No ability to change theme at this time unlike past versions.

**Comment by TakenPilot** [comment]
Those warnings should be gone now (as of 2.0.6)
