### ISSUE TITLE
rodeo command return error (w3m: Can't load http://localhost:5000/)

### ISSUE THREAD

**Issue by JuYoungLim** [yhat/rodeo#36]
workuser@testm13:~/kung-foo$ rodeo .
 _______      ___   ______   ________    ___
|_   __ \   .'   `.|_   _ `.|_   __  | .'   `.
  | |__) | /  .-.  \ | | `. \ | |_ \_|/  .-.  \
  |  __ /  | |   | | | |  | | |  _| _ | |   | |
 _| |  \ \_\  `-'  /_| |_.' /_| |__/ |\  `-'  /
|____| |___|`.___.'|______.'|________| `.___.'

''''''''''''''''''''''''''''''''''''''''''''''''''
  URL: http://localhost:5000/
  DIRECTORY: /home/workuser/kung-foo
''''''''''''''''''''''''''''''''''''''''''''''''''
w3m: Can't load http://localhost:5000/.
w3m: Can't load http://localhost:5000/.

**Comment by glamp** [comment]
Try running with --no-browser and manually open your browser to local host :5000

**Comment by torontodevelopers** [comment]
trying to install this on aws and while no-browser gives me no error, it also doesn't serve a webpage when visiting the ipaddress:5000

**Comment by geledek** [comment]
Same problem here. Started `rodeo . --no-browser` without error message, `--verbose` output seems ok. But using ip_address:5000/ only has ERR_CONNECTION_REFUSED on browser.

OS: Ubuntu 14.04.3 LTS
Rodeo 0.4.4
