### ISSUE TITLE
No 4th column in Environments tab

### ISSUE THREAD

**Issue by DmitriR** [yhat/rodeo#360]
Rodeo 2.0.4 OSX 10.11.5
New install.
I can only see 3 columns in the Environments [Name; Type; REPR]; the column with icons to expand data structures is missing. 
Do I perhaps need to do something in the configuration etc. to make it show?

**Comment by TakenPilot** [comment]
This is solved in Rodeo 2.0.7 for primitives and pandas.DataFrames

The other types like Series, Lists and Arrays will come later!  Until then, using `?some_list` works for viewing docstrings about it, and `some_list` on the command line will show the contents.
