### ISSUE TITLE
Code completion bug for directories/files

### ISSUE THREAD

**Issue by barcadad** [yhat/rodeo#376]
Code completion for commands like pd.read_csv add a redundant directory - that is, if my data are in home/data/data1.csv and my default directory is home, then if I type "filename = 'data/'", the code completion correctly offers the files in my 'data' directory, but then appends 'data/' yet again, so it is duplicated (i.e., home/data/data/data1.csv) - so it's not really working as code completion should.

**Comment by coristig** [comment]
This is fixed as of [2.0.11](https://github.com/yhat/rodeo/releases/tag/v2.0.11)

Closing
