### ISSUE TITLE
Option to hide sidebar banner

### ISSUE THREAD

**Issue by bobcolner** [yhat/rodeo#379]
It would be nice have a bigger workspace by hiding the right-hand sidebar. Conciser using a splash-screen for branding, etc.

**Comment by coristig** [comment]
For now this is what we're going to stick with and focus on building new features.

**Comment by atulkakrana** [comment]
I agree. Sidebar is an annoyance.

Atul

**Comment by fdrennan** [comment]
Agree. It's nearly a dealbreaker for me.

**Comment by CatsLoveJazz** [comment]
Agree. The sidebar is completely unnecessary and extremely off putting, even an offence to efficient use of screen real estate
