### ISSUE TITLE
[Feature Request] Ability to indent/unindent entire code blocks

### ISSUE THREAD

**Issue by christopherjenness** [yhat/rodeo#385]
This is a common IDE feature that is extremely useful.

**Comment by TakenPilot** [comment]
Agreed.  Our auto-complete code is overwriting this feature badly.  This is a BUG.

**Comment by glamp** [comment]
For now on mac you can do `cmd + [` to unindent and `cmd + ]` to indent

**Comment by TakenPilot** [comment]
Pfft, that's lame.  I just added this feature, and I'm building the release (2.0.10) now with this.  It'll be out in a few minutes.
