### ISSUE TITLE
How to run python3 as the default?

### ISSUE THREAD

**Issue by xiekunwhy** [yhat/rodeo#399]
Can some one tell me how to set python3 as the default version running in Rodeo, or how to switch from the default version to another?

**Comment by xiekunwhy** [comment]
Resovled, leave Environment Variables and change Python Command box from python to python3.

**Comment by xiekunwhy** [comment]
Resovled, leave Environment Variables box empty and change Python Command box from python to python3.

**Comment by RoyBoy432** [comment]
When I make the change from python to python3, there is a "permission denied" error I cannot save the new settings. Any suggestions?
