### ISSUE TITLE
rodeo usage on remote host

### ISSUE THREAD

**Issue by epifanio** [yhat/rodeo#40]
I have rodeo installed on a server online and i want access to it remotely
is there a command line otion or configuration file where to set the hostname (instead of just localhost) and to avoid to open a browser from the host machine ?

**Comment by glamp** [comment]
yes, there is now!

614828f9bad59944359b8e7f3f8e7e6209c29f1c
```
$ rodeo

Usage:
  rodeo [--port=<int>] [--no-browser] [--host=<IP>] [<directory>]
  rodeo (-h | --help)
  rodeo --version
```

**Comment by epifanio** [comment]
thanks, on my system the output is a bit different : 

```
epimac:~ epi$ rodeo
rodeo

Usage:
  rodeo [--port=<int>] [<directory>]
  rodeo (-h | --help)
  rodeo --version

Options:
  -h --help     Show this screen.
  --version     Show version.

Help:
Rodeo is a data centric IDE for python. It leverages the IPython
Kernel but presents a different user experience than the notebook. 
Those of you who use products like SublimeText or Eclipse will
probably find rodeo familiar.

Examples:
To run a rodeo server, just execute the `rodeo` command like so:
    $ rodeo . # basic usage
    $ rodeo . --port=4567 # run in this directory, but on port 4567
    $ rodeo /path/to/a/folder # run in a different directory
    $ rodeo /path/to/a/folder --port=4567 # new directory, new port
```

**Comment by erikreppel** [comment]
Is this still possible in newer versions, or does the move to a desktop application remove this ability?

**Comment by abalter** [comment]
I'm guessing it removes it. Python needs an equivalent to rstudio desktop/server. I was hoping rodeo would do it, but alas they have switched from web to desktop completely it appears.
