### ISSUE TITLE
No Help Tab in 2.0.13 on OSX 10.11.6

### ISSUE THREAD

**Issue by jayleverett** [yhat/rodeo#401]
Hi -

First off thanks for a great IDE. This is exactly what I'm looking for in a scientific Python editor.

My issue is similar to [#364](https://github.com/yhat/rodeo/issues/364) - no help tab in the lower right pane. Commands of the form `?round` do work, but they print output to the console rather than to a dedicated tab.

I'm running Rodeo 2.0.13 on OSX 10.11.6.

Any ideas?

Thanks,
Jay

**Comment by TakenPilot** [comment]
I did that on purpose.

I think it's bad UI design to have an action in one place cause feedback in a completely different part of the screen.  This will be especially true once we move to multi-window layouts!

Feel free to open a topic on http://discuss.yhat.com to talk about it.

**Comment by christopherjenness** [comment]
Can it still be an option though?  I much preferred the way it used to be (lower right panel)?
