### ISSUE TITLE
Does the latest version still support browser-based?

### ISSUE THREAD

**Issue by xinzhou1023** [yhat/rodeo#407]
I need a IDE that works on remote linux server. Does Rodeo still support browser-based version, like Rstudio Server. I think it's a cool feature for data science python IDE.

**Comment by TakenPilot** [comment]
It will!  Just not yet.

Right now we're using IPC to communicate between the internal browser window processes and the main process, but I have a plan to move to web sockets.  When I finish that, it'll be runnable on a server.  That's currently two or three months away on the roadmap.

**Comment by michaelklachko** [comment]
Suggestion: I'd like the ability to run the same code on different remote machines. It would be nice if I could store my source files in my cloud based Rodeo account, and use the browser based Rodeo interface to edit, automatically transfer to, and execute on a  specified remote host.  Do you think this is feasible?

**Comment by robromanowski** [comment]
@TakenPilot 
I also just posted on a different issue with you as well, and luckily found this. I want to make my interest for this known as well - this is exactly why I found Rodeo - hearing it was browser based (and as xinzhou1023 also used, the Rstudio equivalent for Python). 

If this is still in the pipeline that would be great - my use for Rodeo would be ideal only if it was browser based still (i.e we have a Linux remote server, we want to install Rodeo on it, and be able to connect it to from a Windows desktop - just like how I do for RStudio.) This would definitely make you guys the only option that exists for this, IMO.

**Comment by ben-gready** [comment]
@TakenPilot This would be extremely useful for me and my team as well.  We would love to have an Rstudio server equivalent for python.  Do you have any idea of the timeline that this might be available?

**Comment by carlosperate** [comment]
Something like this would be fantastic! It's been a little while, has any progress been made in this respect?

**Comment by tdomhan** [comment]
I'd also like to know if there has been any progress made on this as it sounds like a very useful feature to be able to run on a remote machine with lots of RAM and compute, just like jupyter can.

**Comment by abalter** [comment]
Adding another pitch for getting this going.

**Comment by kentore82** [comment]
+1 for webUI! :)

**Comment by Fersalva** [comment]
Please please please. webUI

**Comment by quantsignals** [comment]
Would be great to be able to hook rodeo up to a remote spark python shell

**Comment by robmosh** [comment]
+1 for webUI!

**Comment by falexwolf** [comment]
+1 for webUI!

**Comment by jamartinh** [comment]
+1

**Comment by dsimmie** [comment]
+1 web UI

**Comment by paulokopny** [comment]
+1 web UI

**Comment by Syakyr** [comment]
+1 for web UI!

**Comment by ionmadrazo** [comment]
+1 for web UI! I believe this feature would make rodeo unique.

**Comment by abalter** [comment]
@ionmadrazo -- or at least like RStudio ;)

**Comment by mashaye** [comment]
+1 for web UI!

**Comment by leetschau** [comment]
+1 for web UI!

**Comment by TitorX** [comment]
Is anyone still follow this issue?

**Comment by hoechenberger** [comment]
This project seems to be pretty much abandoned.

**Comment by danielfm123** [comment]
+1
