### ISSUE TITLE
windows 10 - os.getenv returns None while it shouldn't

### ISSUE THREAD

**Issue by mmagnuski** [yhat/rodeo#409]
Doing
```python
import os
os.getenv('APPDATA')
```
returns `None` in rodeo, but the correct output anywhere else (Jupyter notebook, Spyder, IPython etc.)
This causes some packages (like `mne-python`) to fail on import.

**Comment by TakenPilot** [comment]
<img width="411" alt="screen shot 2016-08-07 at 5 29 26 pm" src="https://cloud.githubusercontent.com/assets/4154804/17465419/834a9034-5cc4-11e6-8974-b34b8ce0e0ae.png">

Are you sure?

Can you provide more information about what APPDATA should be?

**Comment by mmagnuski** [comment]
look at the title - the problem appears on windows. APPDATA is an environment variable on windows that specifies where appdata directory is. :smiley:

**Comment by TakenPilot** [comment]
Ah, right!  😀   Here's some screenshots from Windows:

Running jupyter console from the windows cmd.exe terminal:

<img width="371" alt="screen shot 2016-08-07 at 6 58 11 pm" src="https://cloud.githubusercontent.com/assets/4154804/17465938/0f555904-5cd1-11e6-8dea-4e90c2f29f65.png">

Running the same commands in Rodeo:

<img width="497" alt="screen shot 2016-08-07 at 6 59 01 pm" src="https://cloud.githubusercontent.com/assets/4154804/17465940/125dabf6-5cd1-11e6-8b6b-f0f8999a54fd.png">

Though, this is running in version 2.0.14 which is going out on Monday, but I haven't made any big changes beyond adding the ability to run rodeo from the console or by right clicking on folders to set the working directory.

**Comment by TakenPilot** [comment]
It could be that the way I'm starting Rodeo leads to different environment variables being passed to Rodeo, and therefore to the ipython console.  That's a problem I ran into on OSX, and it might be a problem on Windows as well.  I'll dig into this some more.

**Comment by mmagnuski** [comment]
thanks! I'll try with a new installation of rodeo first. I remember I had some problems immediatelly after installation and had to restart rodeo.

**Comment by TakenPilot** [comment]
How did it go?  Did the new version fix the issue?

**Comment by mmagnuski** [comment]
Yes, works very well, thanks!

**Comment by TakenPilot** [comment]
: )
