### ISSUE TITLE
Bug with hitting tab in the terminal

### ISSUE THREAD

**Issue by SakuraSound** [yhat/rodeo#41]
This is some great stuff! I ran into this bug while using it though. 

I know there currently is no autocomplete in the terminal right now, but when I attempted, the line goes blank and I can not delete anything from the current buffer.

Typing an "l" in the terminal
![Typing an "l" in the terminal](https://cloud.githubusercontent.com/assets/1021121/7312668/78316274-ea04-11e4-8f4a-0eb169668539.png)

Hitting tab in the terminal afterwards
![Hitting tab in the terminal afterwards](https://cloud.githubusercontent.com/assets/1021121/7312674/91bd0504-ea04-11e4-98a0-67d8b0b61a92.png)

I attempt to delete but to no avail. Seems to only accept further input, not remove any. Pressing enter brings this screen up.
![I attempt to delete but to no avail. Seems to only accept further input, not remove any. Pressing enter brings this screen up.](https://cloud.githubusercontent.com/assets/1021121/7312692/c47dd0d6-ea04-11e4-84d3-0059c8424532.png)

**Comment by glamp** [comment]
should be fixed w/ ipython autocomplete
