### ISSUE TITLE
Startup the app in ~ instead of /

### ISSUE THREAD

**Issue by hernamesbarbara** [yhat/rodeo#418]
build: rodeo.app 2.1.0

when you boot the app, both the file viewer (bottom right buffer) and the console (bottom left buffer) appear to be in `/` directory. this is a little weird and maybe better to just have it start in the users home folder `~`.

**Comment by TakenPilot** [comment]
Fixed in [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3)
