### ISSUE TITLE
Make this into Atom.io package!

### ISSUE THREAD

**Issue by v3ss0n** [yhat/rodeo#42]
It will make atom.io's python support very powerful

**Comment by davinov** [comment]
+1

**Comment by DavidLGoldberg** [comment]
I can help!

**Comment by glamp** [comment]
:+1:

**Comment by 24hours** [comment]
https://github.com/24hours/rodeo-atom 

I made this atom package. 
ctrl+` : bring up the console, 
ctr + r : run the script 

steps: 
run 
>  rodeo . 
>  open Atom editor.

**Comment by DavidLGoldberg** [comment]
Ahh will have to check it out FYI convention I think is usually atom-rodeo
for naming but shouldn't matter much!

**Comment by glamp** [comment]
I couldn't get it to work. How do I open the atom part of it?

**Comment by 24hours** [comment]
you will need this https://atom.io/

**Comment by glamp** [comment]
yeah i got that part. how do i get the rodeo plugin aspect to work. i installed the atom-rodeo package but nothing happened when is started rodeo and opened atom.

**Comment by 24hours** [comment]
use ctrl + ` and the 'console' will show up like this 
![screen shot 2015-07-03 at 5 18 41 am](https://cloud.githubusercontent.com/assets/650407/8486882/01ca8ff4-2143-11e5-9ef7-be5abf11be2c.png)

you can treat it a ipython console.

use ctr + r if you want to run code on the text editor. 
The output will be shown on console too.

**Comment by kruser** [comment]
:+1:
