### ISSUE TITLE
Python path not being recognized(Windows)

### ISSUE THREAD

**Issue by rohit-toha** [yhat/rodeo#420]
Hi,

The python in my system is installed at "C:\Program Files\Python\Python 3.5\python.exe". Unfortunately, Rodeo isn't recognizing it. Could this be related to the "spaces" in the path??

BTW, the command to check the path "for %i in (python.exe) do @echo. %~$PATH:i" gives me the same location as above.

**Comment by TakenPilot** [comment]
Ah, thanks for letting me know!

I'm looking at better ways to find and configure python so Rodeo is installed more easily.  Could you help me out by looking for the rejection reason in your logs?  The logs are in your home directory in `rodeo.log`, and it'll have something like:

```
findPythons {cmd: "python"}, rejection: "something here"
```

**Comment by rohit-toha** [comment]
Hi,

I couldn't find anything related to rejection. Attaching my log file. Hope it helps.

**Comment by ankostis** [comment]
I'm having the same problem with Rodeo `v2.1.1`, both with my an old Anaconda3 and [WinPython-3.5.2](https://winpython.github.io/) - no spaces in the path; 
the Ok button never gets enabled.

Note that **on purpose**, I have no python installed/registered on my Windows, to bmake it easy to switch distributions.

I'm pasting the interesting lines from my log-file:

```
2016-08-10T14:25:27.887Z - info: resources\app\node\kernels\python\steve-irwin:: findPythons { pythonOptions: { cmd: 'python', shell: 'cmd.exe' },
  rejected: 'Unable to check python with options {"cmd":"python","shell":"cmd.exe"}' }

...

2016-08-10T14:26:53.635Z - info: resources\app\node\kernels\python\client:: checkPython { cmd: 'd:\\Apps\\WinPython-64bit-3.5.2.1\\python-3.5.2.amd64\\nPython.exe ' }
2016-08-10T14:26:54.842Z - info: resources\app\node\kernels\python\client:: checkPython { cmd: 'd:\\Apps\\WinPython-64bit-3.5.2.1\\python-3.5.2.amd64\\nPython.exe' }

```
Please, whatever "automated" method you choose to go, always make sure that the "manual" way (entering the path to `python.exe`) works flawlesly - in Windows there are many strange ways to configure and distribute python environments, and you must have a non-smart way to deal with all of them.

**Comment by ankostis** [comment]
I'm adding my ipython-versions, because I suspect they are not what *rodeo* expects them to be:

```
$ pip list |grep -E 'jupyter|ipython|notebook'  ## cygwin :-)
bipython (0.1.2)
ipython (5.0.0)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (5.0.0)
jupyter-core (4.1.0)
notebook (4.2.1)
```

**Comment by TakenPilot** [comment]
@ankostis Thanks!

There is an manual way, but it seems to be buggy at the moment on Windows.  Sometimes it works and sometimes it doesn't, and I can reproduce the problem fairly easily.  I'll release a version later today with a fix.

**Comment by blakeboswell** [comment]
I have a similar issue as @ankostis.  When installing rodeo 2.1.1 on Windows 7, rodeo will not auto-detect my python path or recognize a manually entered path.  The manually entered path matches the result of 
```
for %i in (python.exe) do @echo. %~$PATH:i
```

Log items:
```
findPythons { pythonOptions: { cmd: 'python', shell: 'cmd.exe' },
  rejected: 'Unable to check python with options {"cmd":"python","shell":"cmd.exe"}' }
2016-08-15T20:45:24.606Z - info: resources\app\node\kernels\python\client:: checkPython { cmd: 'C:\\Users\\bboswell\\portables\\Anaconda3\\python.exe' }
```

Additional info that may not be helpful: I use cygwin as the primary command prompt.  However, I do not use the python version that is distributed with cygwin even though it is installed on my machine.  I use anaconda installed in the location indicated in the logs above.

Please let me know if you need anymore information.

**Comment by TakenPilot** [comment]
I think I understand.

Well, Rodeo is trying to spawn a process with `C:\\Users\\bboswell\\portables\\Anaconda3\\python.exe` as the cmd, and then it's trying to run a IPython kernel.  Anaconda comes with IPython, so that's not a worry.

Since this problem is coming up a lot, I decided to rewrite and redesign the startup screens and the preferences to include a file picker and better feedback about why a particular python is no good.  The new release should have this, and I'm just testing it now across all the systems.

----

https://github.com/yhat/rodeo/blob/2a36178e8fd9476d5140d048c7de91553cf324ff/src/node/kernels/python/client.js#L455

That rejection message seems to be in response to a timeout.  As in, it's taking longer than a minute to start python!

**Comment by TakenPilot** [comment]
I found the issue.  There was:
1) a unicode character in the command that Rodeo was trying to run, and Windows 7 didn't like that.
2) Windows 7 also required a [Environment]::exit(0) command at the end of every powershell script.

Could you folks let me know if [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3) fixes this issue?

**Comment by blakeboswell** [comment]
I installed v2.1.3 this morning and it worked for me.  Rodeo automatically detected my python path.  Thanks!

**Comment by TakenPilot** [comment]
Thanks for letting me know!  : )
