### ISSUE TITLE
Default font is missing on Windows 10

### ISSUE THREAD

**Issue by Zeklandia** [yhat/rodeo#423]
Instead, Rodeo is rendered with an ugly serif font. Now that there is no option to change the font, this issue can't be fixed at all.

**Comment by brydavis** [comment]
I'm noticing this too.

**Comment by Zeklandia** [comment]
![image](https://cloud.githubusercontent.com/assets/2998257/18609730/521c8dcc-7cbe-11e6-92e6-8867a7808a8b.png)

**Comment by glamp** [comment]
this is fixed in 2.3+
