### ISSUE TITLE
dynamic documents

### ISSUE THREAD

**Issue by xuefengliang** [yhat/rodeo#425]
is there a way to create dynamic documents with embedded chunks of python code like rmarkdown ?

**Comment by TakenPilot** [comment]
Not yet!  But soon.

The old way of doing it (and the way other applications do it) is kinda...   I think it could be done better.  I want to do something where a preview of the markdown and python results would be auto-updated as people edited the document.

I'm also not sold on the format that other people are using for this feature.

Any ideas are appreciated!  Especially over here: [discussion forums](http://discuss.yhat.com)
