### ISSUE TITLE
Rodeo doesn't save files when "~" is in the path

### ISSUE THREAD

**Issue by glamp** [yhat/rodeo#428]
![image](https://cloud.githubusercontent.com/assets/1409333/17750629/75a587f2-6491-11e6-99b9-a01ed2da2fd1.png)

**Comment by TakenPilot** [comment]
How did you get to this error?

**Comment by TakenPilot** [comment]
Found it!  Fixed in [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3)
