### ISSUE TITLE
python2 supported?

### ISSUE THREAD

**Issue by 230v** [yhat/rodeo#43]
>>> sys.version
'3.4.1 (default, Nov  3 2014, 14:37:43) \n[GCC 4.9.1 20140930 (Red Hat 4.9.1-11)]'

How i can run on Python2?

**Comment by gregroberts** [comment]
I am also curoius about this. I am running:

Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1
500 64 bit (AMD64)] on win32

and cannot get any plots working.

**Comment by rodneykeeling** [comment]
Working fine here.

```
>>> sys.version
'2.7.6 (default, Sep  9 2014, 15:04:36) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]'
>>> from ggplot import *

ggplot(aes(x='date', y='beef'), data=meat) + \
    geom_point(color='lightblue') + \
    stat_smooth(span=.15, color='black', se=True) + \
    ggtitle("Beef: It's What's for Dinner") + \
    xlab("Date") + \
    ylab("Head of Cattle Slaughtered")
<ggplot: (287353225)>
```

Plot shows up just fine.
