### ISSUE TITLE
High memory usage after using rodeo in ubuntu

### ISSUE THREAD

**Issue by potholiday** [yhat/rodeo#438]
My system is a Ubuntu distros and I have installed rodeo 2.1.1 in it. Rodeo is very good but lacks many function like third mouse click,dark mode, clearing memory/cache, pop-out plots etc. This is the problem I have noticed in my system while using Rodeo. After completion of an analysis or a program with rodeo the memory of the system spikes (idle ram~35%, after rodeo>70%). The problem is even after closing/exiting rodeo the memory seems to stay at  very high percentage. I always have to restart/logout the system to reset the memory to idle precentage

**Comment by TakenPilot** [comment]
On Linux, there was an issue where processes were not being killed automatically by the system when the parent process exited.

That means your python process would continue to live even if you killed Rodeo.  😞 

In version [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3), Rodeo will force kill its child processes before exiting, and log messages if it cannot.  It also has a ton of logging tracking each process it creates and destroys.

This is very much a problem _only_ for specific Linux distros that are allowing Rodeo to create children and then abandon them, and has to do with a nodejs bug.

Does this information help?

**Comment by potholiday** [comment]
Yeah, thanks for the immediate reply and thanks for rodeo
