### ISSUE TITLE
path to .virtualenvs/rodel/bin/python not retained by 2.1.3 Rodeo update

### ISSUE THREAD

**Issue by KC3101** [yhat/rodeo#440]
Ever since the update to Rodeo 2.1.3, app startup always hangs at the install requirement for Jupyter.  Entering the python path /Users/<username>/.virtualenvs/rodeo/bin/python allows Rodeo to open.  This python path is shown in settings, and all the packages for jupyter, numpy, pandas, matplotlib are present. Mac OS X 10.11.6.

**Comment by TakenPilot** [comment]
> /Users//.virtualenvs/rodeo/bin/python

Why the double slash?

Anyway, rodeo typically looks at the default python instance when it starts, i.e., typing `python` on the command line.  You want a very specific python instance, so changing the path manually is correct.

I don't know why you lost your python command setting on update, though.  It's saved in the `pythonCmd` setting in localStorage in the browser, which you can see by looking in the DevTools.

**Comment by KC3101** [comment]
Sorry, /Users//.virtualenvs  is a typo, there is no “//”

[cid:image001.png@01D201F6.196F68C0]
I’ve not been to DevTools before, but did locate what seems to be the appropriate section. The path to Python is correctly stated here, but Rodeo still will not load, hanging at Jupyter.
[cid:image002.png@01D201F6.196F68C0]

This has only been the case since recent updates.

**Comment by TakenPilot** [comment]
Hmm, this is interesting.

Could you check the logs at ~/rodeo.log to see why it's rejecting your jupyter installation?

Maybe you have a very old version of jupyter?  What happens if you run

```python
from jupyter_client import manager
```

or 

```python
from IPython.kernel import manager
```

from the command line version of python?

Rodeo tries to run [this](https://github.com/yhat/rodeo/blob/master/src/node/kernels/python/start_kernel.py):
```python
try:
    from jupyter_client import manager
except ImportError:
    try:
        from IPython.kernel import manager
    except ImportError:
        raise Exception('Jupyter is not installed')
```

**Comment by KC3101** [comment]
Dane,
I do find this line near the top of the log file:  stdout: '{"executable": "/Users/kcrist/.virtualenvs/test1/bin/python", "hasJupyterKernel": true, "argv":

You are pretty much asking beyond my understanding of the programming here, but I seem to have things up to date:

[cid:image001.png@01D201F9.8D644950]

Keith

**Comment by TakenPilot** [comment]
Thanks for your help so far!

That line means that jupyter is being found, so some other error must be happening.

Could you drag a screenshot of the error into github?  Could you send the nearby lines close to the logs that you just found?

**Comment by KC3101** [comment]
![screen shot 2016-08-29 at 1 38 48 pm](https://cloud.githubusercontent.com/assets/19418923/18060792/02af9664-6dee-11e6-9062-bd579b6fe2e9.png)

![screen shot 2016-08-29 at 1 41 42 pm](https://cloud.githubusercontent.com/assets/19418923/18060887/66c1dba8-6dee-11e6-8911-9687b85c3535.png)

These are the log entries that are flagged as stderr:' ' , or at least those closest to the occurrence of "Jupyter" in the log file.

**Comment by KC3101** [comment]
And this is the error on Rodeo start up:

<img width="789" alt="screen shot 2016-08-29 at 1 45 18 pm" src="https://cloud.githubusercontent.com/assets/19418923/18061000/fa2b7fde-6dee-11e6-8f80-0f4a1375c042.png">

**Comment by TakenPilot** [comment]
Yeah, that appears to all be correct for Jupyter.

I wonder if Rodeo is getting confused between different version of python, somehow.  I'm going to do some tests to see if I can reproduce this issue.  Based on the logs that you've sent me, I have a pretty good idea of where the error might be.  Thank you!

Since you're on a mac, you can skip the startup screen by running:
```bash
/Applications/Rodeo.app/Contents/MacOS/Rodeo --no-startup
```
on the command line.  If there really _is_ a real issue though then this might fail, but from the logs it seems like your system is set up very well.

**Comment by KC3101** [comment]
That will start Rodeo, but with this error in the Console

<img width="362" alt="screen shot 2016-08-29 at 1 57 32 pm" src="https://cloud.githubusercontent.com/assets/19418923/18061510/ffcf4518-6df0-11e6-90de-b11d6fb0afb3.png">

I had fixed that once before, it was due to an old directory path for Default Working Directory. That is again showing the wrong path.  Looking for Users/kcrist/Lrnpy; should be Users/kcrist/Documents/Lrnpy

**Comment by TakenPilot** [comment]
Ah ha!  Typo.  You're missing an 'n' on the end of python.

**Comment by TakenPilot** [comment]
Ah ha!  Typo.  ENOENT means that file does not exist.

Are you sure it's typed exactly?

If you go into the preferences, there is a file picker button that can help.

**Comment by KC3101** [comment]
Oops... this is from an iMac, the directory change was on my laptop.  On the iMac, the Default Working Directory path is correct.

**Comment by KC3101** [comment]
If I start Rodeo from the app, and re-enter the python path at the Jupyter error, that error is not present.

**Comment by TakenPilot** [comment]
Excellent!  Thanks so much!

I'll track down the error and it'll be in the next release.

**Comment by KC3101** [comment]
Actually, that "n" at the end of pytho was cut by the window width, it is on the next line.  I did copy your command line and paste it into the terminal window, that console error message is present when Rodeo starts.

**Comment by KC3101** [comment]
So that seems a little odd, but after I moved the Lrnpy folder into Documents and updated the path in the Settings dialog, Rodeo starts from that Terminal cmd without error

**Comment by TakenPilot** [comment]
That is weird.  If I had more information I could put something into Rodeo to auto-detect this situation, but as it is, I just have no idea.  Glad it works now though!
