### ISSUE TITLE
feature request: debugger (with breakpoints)

### ISSUE THREAD

**Issue by mmagnuski** [yhat/rodeo#445]
I really like where Rodeo is going - but currently I am using mostly Spyder. One of the main reasons for using Spyder over Rodeo is debugging. Although debugging in Spyder is not painless - it is there and is quite useful most of the time.
It would be super nice if Rodeo had some debugger - that would certainly win me over.
I know it is a big feature to add - are you planning on adding it?

**Comment by kanihal** [comment]
I also need debug option in Rodeo.

**Comment by loneharoon** [comment]
debugging still not possible in Rodeo?

**Comment by bjce** [comment]
indeed a debugging-option would be great for Rodeo!

**Comment by Henri-Lo** [comment]
Spyder is very unreliable while rodeo is reliable but missing many essential feature, please add this.

**Comment by mmagnuski** [comment]
@Henri-Lo: on the other hand - Spyder is actively developed while rodeo has been silent for last 6 months
edit: see [this](https://github.com/yhat/rodeo/issues/631) issue.

**Comment by mmagnuski** [comment]
Rodeo has been silent for last two years and can be decalred dead, so I'm going to close this issue.

**Comment by bjce** [comment]
sad!
