### ISSUE TITLE
Over plotting on the previous programme output plot 

### ISSUE THREAD

**Issue by rejusam** [yhat/rodeo#45]
When I run a new program for plotting, the plot is overplating on my previous program's output plot.
Last output plot 
![selection_092](https://cloud.githubusercontent.com/assets/6176357/7316949/0ef901aa-ea99-11e4-8e5d-3245d467fff6.png)
When I run a new programme, it is overplotting on the marked portion as shown below
![selection_093](https://cloud.githubusercontent.com/assets/6176357/7316977/44c1ec3e-ea99-11e4-9db5-61bcd07ce408.png)

**Comment by glamp** [comment]
try with 9327375798478ed9446db1f47d1e12bf6e5b1f9c and let me know if it's working
