### ISSUE TITLE
Contextual help is not visible

### ISSUE THREAD

**Issue by juanfcocontreras** [yhat/rodeo#468]
Rodeo 2.3.0 in Mac 10.11.6 with default theme.

Screenshot attached.

<img width="1029" alt="rodeo" src="https://cloud.githubusercontent.com/assets/4047415/18741518/fbb12ad8-80af-11e6-8c64-4ea8aac60ab5.png">

**Comment by TakenPilot** [comment]
Woah!  That wasn't intended.

I can reproduce this.  Fix will be within the hour.

**Comment by TakenPilot** [comment]
Building 2.3.1 right now.

**Comment by TakenPilot** [comment]
Should be available now.
