### ISSUE TITLE
Windows UAC and font appearance

### ISSUE THREAD

**Issue by klonuo** [yhat/rodeo#47]
Hi,
this looks very nice, but just after trying it I thought to shamelessly give my 2c:

1. On Windows rodeo wont start unless I run it as administrator.

2. Font sizes doesn't look right. On your screenshots it seems you develop on Mac, but on Windows it looks like this:

![IE](http://i.imgur.com/fMxIWlq.png)

![Chrome](http://i.imgur.com/LqVYkZ4.png)

 - Console font is too small
 - Code editor font is also small
 - tooltip font is too big
 - and also Tab fonts are too big

At least that's my first impression.

Keep up the good work!

**Comment by klonuo** [comment]
> 1. On Windows rodeo wont start unless I run it as administrator.

Sorry, this is my fault, as I installed with pip from Administrator CLI.
So it is as expected.

**Comment by Biluoshilang** [comment]
can you teach me how to run it on windows please?
I got the error "failed to create process" even if I had tried so many ways

**Comment by klonuo** [comment]
@Biluoshilang, sorry but your trace is insufficient to me to be determined.
Are you perhaps running Python 3.x?

My example is with Python 2.7.8

**Comment by glamp** [comment]
got rid of the snippets so this should be gone

**Comment by syzhjjw** [comment]
Console font is too small
