### ISSUE TITLE
2.3.0 broke the styling on the tab documentation!

### ISSUE THREAD

**Issue by eldonclay** [yhat/rodeo#471]
Looks like there isn't a background style on the tab documentation? Completely unusable on non-white themes.

**Comment by TakenPilot** [comment]
Yep!  That's been fixed in 2.3.1 released today.  Restart Rodeo to get the update!

Dup of https://github.com/yhat/rodeo/issues/468, who reported it just before you.  : )

**Comment by eldonclay** [comment]
Awesome! Thanks!
