### ISSUE TITLE
Upgrading rodeo from inside rodeo not working in ubuntu 14.04

### ISSUE THREAD

**Issue by potholiday** [yhat/rodeo#473]
I am using Ubuntu 14.04 and rodeo 2.2.0 . according to your [website](https://www.yhat.com/products/rodeo) the latest version of rodeo is 2.3.1. I tried to upgrade my 2.2.0 to latest version using `Help>Check for Updates` but  its showing this message ` Rodeo has all the latest updates!`. Any reason why its not updating from rodeo itself?

**Comment by TakenPilot** [comment]
You're right, it doesn't work: http://electron.atom.io/docs/api/auto-updater/

> There is no built-in support for auto-updater on Linux, so it is recommended to use the distribution’s package manager to update your app.

**Comment by potholiday** [comment]
Thanks for the reply and I have one recommendation can you increase the start up time of rodeo. It takes a while(20-30 sec) to fully load rodeo in my system. The splash screen is unnecessary and I believe you have some analytical script(just a guess) inside splash screen.

**Comment by TakenPilot** [comment]
Sure do. That analytical script is checking for Python, Jupyter and a bunch
of data science libs, blocking new users until they understand that they
have to be installed, or that they should install Anaconda.

You can get rid of it though using the `--no-startup` flag as mentioned in
the readme here on Github, or from looking at `--help`. I figured that
people wise enough to know Github would probably know what to do with it. 😇
