### ISSUE TITLE
Rodeo 2.3.2 fails to start

### ISSUE THREAD

**Issue by thecpshah** [yhat/rodeo#476]
I have just installed Rodeo 2.3.2 but it fails to start.

When I launch it, it gives me the following error (please see the attached image)

When I click on "I USE A DIFFERENT COMMAND FOR PYTHON" and enter `ipython`, it does start but does not execute any command e.g. `x = 2`

In the preferences, I also entered path for `anaconda` as `~/anaconda/bin/python` but that does not work either

My system is as follows

Mac
El-capitan
Anaconda 2.7
Virtual Env 3.5

Please let me know how can I fix this issue?

<img width="819" alt="screen shot 2016-09-25 at 08 18 21" src="https://cloud.githubusercontent.com/assets/10298891/18813637/d7f10cda-82f8-11e6-9b31-23475c766c7f.png">

**Comment by glamp** [comment]
are you running python in a virtual-env? if so, can you try using a python PATH that *isn't*? would be interesting to see if that's the issue.

**Comment by thecpshah** [comment]
I have two environments on my machine.

Python 2.7 is not virtual

Python 3.5 is virtual. 

Should I remove the virtual environment?

**Comment by McCroden** [comment]
I'm getting the same error. macOS Sierra 10.12. Had Anaconda and Rodeo installed before. Anaconda (4.1.11): Anaconda Navigator version 1.3.1. 

I have 3 environments: 2.7, 3.4, 3.5. 

The `python` command works in a standard Terminal window.

![image](https://cloud.githubusercontent.com/assets/4575239/19329392/0cd55552-909e-11e6-9bf3-0aecb00318e8.png)

**Comment by BiaoPeng** [comment]
do install the ipython/jupyter?

**Comment by BiaoPeng** [comment]
did you install the  ipython/jupyter?

**Comment by McCroden** [comment]
Yes. Everything was installed through Anaconda. Rodeo had ran fine when I used it before this update, but that was a few months ago. I don't use Rodeo too frequently
