### ISSUE TITLE
Rodeo crashed my site-packages

### ISSUE THREAD

**Issue by 230v** [yhat/rodeo#48]
He create link python => python3 and pip (not pip3) crashed progress install another package.
Example (pip default use python2, for python3 designed pip3):
![- 24 04 2015 - 14 42 49](https://cloud.githubusercontent.com/assets/9416005/7318051/67d14200-ea90-11e4-8f2a-974ccaa2a64e.png)

**Comment by glamp** [comment]
confused here. seems like the wrong package (`grab`)? closing for off topic
