### ISSUE TITLE
'module' object has no attribute 'start_new_kernel' on startup

### ISSUE THREAD

**Issue by vfxGer** [yhat/rodeo#481]
start_kernel.py line 62 on start up getting this error: 
`AttributeError: 'module' object has no attribute 'start_new_kernel' on startup`
Using python 2.7 on OSx
Can't copy from the start up window to show the exact error message.

**Comment by glamp** [comment]
@vfxGer What version of Rodeo are you running?

**Comment by vfxGer** [comment]
2.3.2

**Comment by cimarie** [comment]
@vfxGer I had the same problem. I've fixed it by installing `jupyter_client` via `pip install jupyter_client`.

Hope that can solve the problem for you too :)

**Comment by vfxGer** [comment]
It seems to be working, not sure if the pip install jupyter_client was the fix though.
Thanks.

**Comment by anurag3290** [comment]
try `sudo pip install jupyter`
