### ISSUE TITLE
Error w/ if/else control flow

### ISSUE THREAD

**Issue by eldonclay** [yhat/rodeo#486]
There is issue with executing if-else statements, unsure how far back this goes. Rodeo will execute if statements fine, but cannot seem to read the "else" portion when included. Tried in the console and in the editor. Keeps throwing a syntax error on the "else".

**Comment by rkipp1210** [comment]
Hey @eldonclay,

I am able to get `if-else` to run correctly (mac osx 10.11.6, py2.7, rodeo 2.4.2):
```
>>> flow = False 
...  
... if flow: 
...     print("hello from if") 
... else: 
...     print("hello from else") 
...  
... 
hello from else
```

I'm wondering if you have a sytax error right before the else, like when I leave the closing paren off my print statement just above the else:
```
>>> flow = False 
...  
... if flow: 
...     print("hello from if" 
... else: 
...     print("hello from else") 
...  
... 
  File "", line 5
    else:
       ^
SyntaxError: invalid syntax
```
Hope that helps.

**Comment by eldonclay** [comment]
@rkipp1210 thanks for checking! I'm pretty sure that it is not a syntax issue :)

I just updated to 2.4.2 on both OS X and windows 7, running python 3.5.2; issue still exists.

If I select the whole block and run it, the code executes fine. However, you can't run the same code line-by-line, or individually in the console like you can with the regular python interpreter.

I was running my script line-by-line when the issue cropped up... atleast we have a work-around with running the whole block for now.

**Comment by rkipp1210** [comment]
Yeah, I too have noticed strangeness when running a block of code line by line (I always just highlight and execute the block).  Going to close this one for now, but feel free to open a new issue for the line by line running.
