### ISSUE TITLE
Setting up Brew Cask formula

### ISSUE THREAD

**Issue by nhejazi** [yhat/rodeo#498]
I've using Rodeo for a while now, but (after looking recently) have been unable to find a formula for downloading/installing the GUI via Brew Cask. Are there any plans to support building a simple formula for making Rodeo installation easier? My apologies in advance if this is a duplicate issue.

**Comment by coristig** [comment]
Looks like someone submitted it to [brew](https://github.com/caskroom/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/rodeo.rb)

The command below should work:

`$ brew cask install rodeo`

**Comment by nhejazi** [comment]
Looks like the `brew cask install rodeo` is working (based on a first pass try).

Agree -- would be great to have this in the docs now that it's available.
