### ISSUE TITLE
deb missing for v2.4.3 release

### ISSUE THREAD

**Issue by chendaniely** [yhat/rodeo#499]
or should everyone else stay on v2.4.2 because v2.4.3 was a windows only release?

**Comment by coristig** [comment]
Hey @chendaniely!

v2.4.3 was a Windows only release so everyone else should still be on v2.4.2

Also as a side note, we're working on supporting Linux dist. better with apt-get and yum installable Rodeos.  We'll keep you updated!

**Comment by chendaniely** [comment]
sorry for the confusion.

I'm actually using the `.deb` files for Arch linux: https://aur.archlinux.org/packages/rodeo/

This issue can be closed.
