### ISSUE TITLE
exit() command

### ISSUE THREAD

**Issue by itdxer** [yhat/rodeo#50]
```
>>> print(3)
3

>>> exit()
null
>>> 1 + 2
>>> print('hello world')
>>> 
```

**Comment by JanSchulz** [comment]
The KernelClient has a `is_alive()` method, which should probably be called before any execution. I haven't done that in knitpy either, so no experience yet...

**Comment by glamp** [comment]
fixed in latest release
![image](https://cloud.githubusercontent.com/assets/1409333/8478086/208da0d0-209d-11e5-81b3-d9acfb102b12.png)
