### ISSUE TITLE
Highlight Execute - Undesired Behavior

### ISSUE THREAD

**Issue by ben519** [yhat/rodeo#501]
A very minor annoyance I run into frequently - If you have a multi-line statement and you try to highlight and execute a snippet of the statement, Rodeo doesn't execute your highlighted portion and instead waits for more input.  For example if you put this in the editor

```
foo = 'hello world'
foo.find(
    "hello"
)
```

Now highlight the second `foo` and Cmd+Return.  I get this

<img width="119" alt="screen shot 2016-10-13 at 10 38 54 am" src="https://cloud.githubusercontent.com/assets/723099/19355801/43d19302-9131-11e6-8db9-ae7a73eb438d.png">

I think Rodeo should be executing the command here, without waiting for more input.

**Comment by TakenPilot** [comment]
I think I've fixed this in https://github.com/yhat/rodeo/releases/tag/v2.4.8

Could you test it out and verify the fix?

**Comment by ben519** [comment]
Looks good.  Thanks Dane.

**Comment by TakenPilot** [comment]
🌟
