### ISSUE TITLE
Feature request: "Set working directory"

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [yhat/rodeo#502]
I recommend including a "Set working directory" button (like R Studio) somewhere in the IDE, as to avoid manually typing `os.chdir(path)` to set your WD.  Otherwise, a user needs to specify the path via copy-paste or manually (both of which are cumbersome), instead of conveniently clicking to it.  I am using Rodeo 2.4.2.

Best wishes,
Bohdan Khomtchouk

**Comment by TariqAHassan** [comment]
@Bohdan-Khomtchouk 

Perhaps I misunderstand you, but I believe this can already be done by clicking the path in the lower right of the console.

**Comment by Bohdan-Khomtchouk** [comment]
When I click on it and select where I want to go and press Open, I get:

>>> cd "/Users/bohdankhomtchouk/Desktop/rodeo_testing"
/Users/bohdankhomtchouk

So it doesn't actually change my working directory.  It's still the same (`/Users/bohdankhomtchouk`), which is the default.

**Comment by yzhang5471** [comment]
@TariqAHassan It seems not working in Windows.
