### ISSUE TITLE
[Documentation] Docs About Launching from command line have a URL that 404s

### ISSUE THREAD

**Issue by pellagic-puffbomb** [yhat/rodeo#506]
<img width="802" alt="screen shot 2016-10-14 at 2 27 18 pm" src="https://cloud.githubusercontent.com/assets/4587833/19403219/851e3650-921a-11e6-8273-7c4e54e16c0f.png">

This link (https://raw.githubusercontent.com/yhat/rodeo/master/bin/rodeo) 404s.

On this page: http://rodeo.yhat.com/docs/#launching-rodeo-from-the-command-line

**Comment by coristig** [comment]
Hey thanks for pointing that out.  I just updated the docs.  In short, you can run 
`echo "alias rodeo=open -a /Applications/rodeo.app/" >> ~/.bash_profile`

**Comment by pellagic-puffbomb** [comment]
Awesome! Thank you.
