### ISSUE TITLE
Inconsistent downloads for Linux

### ISSUE THREAD

**Issue by Gabriel-p** [yhat/rodeo#511]
If I attempt to download from the home page, I get the file:

https://github.com/yhat/rodeo/archive/v2.4.2.zip

This package contains no .deb file nor any instructions on how to install whatsoever.

If I follow the instruction in this repo (*Check bareback.s.yhat.com for the latest release. Download it!*), I get a file:

`rodeo-2.0.10-amd64.deb`

which does not look like the final release.

I can only download v2.4.2 from https://github.com/yhat/rodeo/releases

**Comment by coristig** [comment]
Hey @Gabriel-p 

We're in the process of adding supported `apt-get` and `yum` repos for Rodeo.  Still in the process of testing, but if you run the commands below, it should install the package for you:

```
# add the yhat public key and add the repo
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 33D40BC6
sudo add-apt-repository -u "deb http://rodeo-apt-test.s3.amazonaws.com/ rodeo main"

# install rodeo and run it
sudo apt-get -y install rodeo
/opt/Rodeo/Rodeo
```

Let us know if this works / doesn't.

**Comment by coristig** [comment]
Just a heads up, we moved repo URL and gave it a CNAME (in case we need to move it around).  Updated commands are below:

```
# add the yhat public key and add the repo
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 33D40BC6
sudo add-apt-repository -u "deb http://rodeo-deb.yhat.com/ rodeo main"

# install rodeo and run it
sudo apt-get -y install rodeo
Rodeo
```
