### ISSUE TITLE
Console crashes executing input() function

### ISSUE THREAD

**Issue by pingviner** [yhat/rodeo#512]
Hello,
I am using the latest Rodeo version Windows 10 64bit. When I run a script containing input(), the console freezes. I cannot type in any input and have to restart the terminal. Is there any known solution to that issue. Thanks

**Comment by TakenPilot** [comment]
I think this is fixed in https://github.com/yhat/rodeo/releases/tag/v2.4.8

Could you verify that it's fixed for you?

**Comment by pingviner** [comment]
Bug is fixed! Thanks
