### ISSUE TITLE
There are no result with chinese characters

### ISSUE THREAD

**Issue by lukexue** [yhat/rodeo#525]
\# -*- coding: utf-8 -*-
import pandas as pd
df = pd.read_csv("https://s3.amazonaws.com/rodeo-tutorials/data/credit-training.csv")
#測試
#df.head()
pd.value_counts(df.age,sort=False).plot(kind='bar')

#on Mac OS X 10.12.1
#python 3.5.2_3

**Comment by TakenPilot** [comment]
I can reproduce this.  Working on it now.

**Comment by coristig** [comment]
This is with the latest build (v2.4.9):

![image](https://cloud.githubusercontent.com/assets/7118371/20361169/9ee0a056-ac04-11e6-9e7c-a4dfe3edec86.png)

Can you try to replicate it again with the latest version? 👍

**Comment by coristig** [comment]
I was able to replicate this using python 2.7, but this is expected as it doesn't handle unicode by default, whereas python 3 does.

![image](https://cloud.githubusercontent.com/assets/7118371/20361970/ac9aad6a-ac07-11e6-9293-d92c44e28960.png)

**Comment by lukexue** [comment]
v2.4.9 using python 3.5:

<img width="1280" alt="2016-11-17 11 33 45" src="https://cloud.githubusercontent.com/assets/2391716/20375399/0550fb6e-acba-11e6-9161-7de95535e53d.png">
<img width="1280" alt="2016-11-17 11 34 35" src="https://cloud.githubusercontent.com/assets/2391716/20375401/0557cc3c-acba-11e6-9720-0476a70dd50c.png">
<img width="1280" alt="2016-11-17 11 34 50" src="https://cloud.githubusercontent.com/assets/2391716/20375400/0553231c-acba-11e6-82fd-9de561fc7b17.png">

<img width="1280" alt="2016-11-17 11 36 45" src="https://cloud.githubusercontent.com/assets/2391716/20375440/2a7ef616-acba-11e6-963a-c8692d019a34.png">

**Comment by lukexue** [comment]
2.4.10

<img width="1280" alt="2016-11-17 11 48 17" src="https://cloud.githubusercontent.com/assets/2391716/20375705/cf6a055c-acbb-11e6-9435-93f842badf79.png">

**Comment by TakenPilot** [comment]
Someone on the forums discovered the answer!

http://discuss.yhat.com/t/multi-byte-string-support/399/3

Add this environment variable, and it should work:

```bash
export PYTHONIOENCODING=UTF-8
```
