### ISSUE TITLE
Console text size is not resizeable

### ISSUE THREAD

**Issue by jstaf** [yhat/rodeo#529]
I wanted to do some teaching with Rodeo the other day, but discovered that the console text size was microscopic on my projector and could not be changed. 

Is there any way that the console text size could use the same text size as the editor? (If the console would use the same editor color theme, that would be even better!)

**Comment by TakenPilot** [comment]
You're right!  That used to work...

Fixed in https://github.com/yhat/rodeo/releases/tag/v2.4.8  ?

Could you test to see if this does what you expect?

**Comment by jstaf** [comment]
Fantastic, looks like it's working!

**Comment by TakenPilot** [comment]
🌟
