### ISSUE TITLE
Bugs: Plots not showing, forced scrollbars, null values and autocompletion

### ISSUE THREAD

**Issue by rsmith31415** [yhat/rodeo#53]
I tested rodeo in Ubuntu 15.04, Chrome 42 and Firefox 37 using an anaconda environment and noticed a few bugs:

1 . Plots are not showing. I get the correct output in the console:
```
>>> ax.plot(range(10))
[<matplotlib.lines.Line2D at 0x7fdf4f954ed0>]
```
but the Plots tab is not showing anything and there is an `Uncaught SyntaxError: Unexpected token ` error in the console.

*UPDATE*: Now this has been fixed.

2 . The interface is forcing a scrollbar in the window:

![screenshot from 2015-04-24 14 31 55](https://cloud.githubusercontent.com/assets/599274/7326921/bb96a742-ea8e-11e4-9f85-f1602ef0ffc2.png)

3 . As reported previously, the fonts are too small and the name of the panels are very large:

![screenshot from 2015-04-24 14 34 44](https://cloud.githubusercontent.com/assets/599274/7326965/126346fc-ea8f-11e4-8a18-860a0b223641.png)

4 . There is a superfluous scrollbar in the DataFrame and History tabs:

![screenshot from 2015-04-24 14 32 37](https://cloud.githubusercontent.com/assets/599274/7326957/0a07840a-ea8f-11e4-8223-a3f5aebbf175.png)

*UPDATE*: Also fixed.

5 . After saving a file, there is not an indication of the file name in the URL address.

6 . A lot of null values in the console (it would be better not to show that):

![screenshot from 2015-04-24 14 36 16](https://cloud.githubusercontent.com/assets/599274/7327005/6122ce70-ea8f-11e4-9f76-672fae563a12.png)

7 . DataFrames variables are not being shown in the DataFrames tab.

*UPDATE*: Also fixed.

8 . Autocompletion seems not to show the correct objects at first:

![screenshot from 2015-04-24 14 44 18](https://cloud.githubusercontent.com/assets/599274/7327142/74cf0e24-ea90-11e4-90a6-b105b3ad2fa0.png)

However, after executing that line, the objects are shown correctly:

![screenshot from 2015-04-24 14 45 35](https://cloud.githubusercontent.com/assets/599274/7327153/98497b5a-ea90-11e4-886f-41099d786508.png)

**Comment by patwater** [comment]
+=1 on plots not showing.  Firefox on windows on activestate python

**Comment by glamp** [comment]
9327375798478ed9446db1f47d1e12bf6e5b1f9c let me know if that fixes the plots

**Comment by rsmith31415** [comment]
Thanks. It fixes that issue and also the issue with the Data Frame tab.

By the way, a recent change made the font size even smaller.

**Comment by glamp** [comment]
nulls should be fixed

i added a font-size preference to File > Preferences. I will look into the Tab font size as well

**Comment by glamp** [comment]
autocomplete is working for me. not sure why you're not seeing the right choices.

![image](https://cloud.githubusercontent.com/assets/1409333/7333554/8958a6e6-eb41-11e4-8ed7-d86f71b76131.png)

**Comment by glamp** [comment]
> After saving a file, there is not an indication of the file name in the URL address.

Not sure what this means

**Comment by glamp** [comment]
superfluous scrollbar is super annoying. i don't see it on chrome but i'm sure it's just a small css thing.

**Comment by JanSchulz** [comment]
Re scrollbars: 
```
-  overflow-y: scroll;
+  overflow-y: auto;
```

?

**Comment by rsmith31415** [comment]
>Not sure what this means

When I save a file, the URL should be updated to reflect the file name:

![screenshot from 2015-04-25 11 25 42](https://cloud.githubusercontent.com/assets/599274/7333670/f1d1c6a2-eb3d-11e4-94d7-9363a56b798d.png)

Otherwise, it is not possible to copy the link or bookmark it to retrieve a file (other than loading the file again, of course).

**Comment by rsmith31415** [comment]
@glamp 

>autocomplete is working for me. not sure why you're not seeing the right choices.

Now I can see the correct autocomplete. It seems a bit odd that I can see DataFrame and Series even before loading pandas. This is not happening with numpy.

**Comment by glamp** [comment]
@JanSchulz  thanks just pushed

**Comment by rsmith31415** [comment]
Yes, that fixes the scrollbars in the DataFrames and History tabs.

**Comment by rsmith31415** [comment]
By the way, I noticed that pandas is actually loaded automatically. Is that an intended behavior?

**Comment by glamp** [comment]
these are either fixed or duplicate issues so closing this out

**Comment by rsmith31415** [comment]
@glamp Can you reference what are the issues that duplicate:

2 . The interface is forcing a scrollbar in the window.

5 . After saving a file, there is not an indication of the file name in the URL address.

**Comment by syzhjjw** [comment]
Console font is too small
