### ISSUE TITLE
In the Terminal window, the alt-key does not work properly

### ISSUE THREAD

**Issue by yannche** [yhat/rodeo#539]
I can't type caracters which require pressing the "alt" key in the Terminal window of Rodeo. But everything works well in the editor window.

For example, to get the bracket sign "[" on my AZERTY keyboard, I have to press alt+shift+5. This does not work in the terminal of rodeo, but it works in the editor window.

However, the shortcuts based on alt key do work. For example "view->change editor->move one left", which accessible by cmd+alt+rightArrow, works as expected.

by the way, I'm using Rodeo 2.4.9 on Mac os Sierra, with the latest Anaconda distribution. I also use an AZERTY keyboard (the french layout),

**Comment by TakenPilot** [comment]
Oh, this is interesting.  I'm using React's keyboard bindings, and they may not be functioning as they should.  I'm going to experiment with this and see if I can find a workaround.

Thanks for such a thorough bug report!  It really helps.

**Comment by TakenPilot** [comment]
Released in [v2.4.10](https://github.com/yhat/rodeo/releases/tag/v2.4.10)
