### ISSUE TITLE
tab completion broken in editor, fine in console

### ISSUE THREAD

**Issue by enteehc** [yhat/rodeo#54]
I'm just starting to use rodeo, and pressing tab in the editor simply inserts a tab instead of doing any completion. Tab completion does appear to work in the terminal however. Nominally this is version 0.2.1, python is version 2.7.9 and ipython is at version 3.1.0. I'm running OS X 10.10.3 and the issue happens in safari, firefox and chrome.

**Comment by rsmith31415** [comment]
I think currently the autocompletion only works after a dot (e.g. `numpy.<tab>`), but definitely this should be a feature request (maybe using shift-tab just like IPython/Jupyter)

**Comment by entee** [comment]
I tried it using the following code in the editor:
```python
import pandas as pd
df = pd.D<tab>
```
just got extra tabs after the D. In the console it gives several options including the expected.

**Comment by glamp** [comment]
fixed
