### ISSUE TITLE
Using Rodeo with docker image

### ISSUE THREAD

**Issue by jasmeenpatel** [yhat/rodeo#544]
I want to use python environment present in a docker image with the rodeo, so that i can use rodeo from any machine and with the same environment. I have tried to find the solution on the forums and  other discussions and documentation but i wasn't able to gather information needed.

**Comment by TakenPilot** [comment]
Docker images don't have a graphical user interface.  Rodeo is currently a Desktop-only application.  Later, there is a Rodeo Server version that runs like a webpage, but we're currently focusing on a one-step installation process.
