### ISSUE TITLE
Dataframe view displays first time, freezes at fetching data on successive attempts

### ISSUE THREAD

**Issue by davidthewatson** [yhat/rodeo#55]
I have rodeo pip installed in a virtual env. Here's the output of freeze:

    alabaster==0.7.3
    Babel==1.3
    backports.ssl-match-hostname==3.4.0.2
    certifi==14.5.14
    docopt==0.6.2
    docutils==0.12
    Flask==0.10.1
    gnureadline==6.3.3
    ipython==3.0.0
    itsdangerous==0.24
    jedi==0.8.1
    Jinja2==2.7.3
    jsonschema==2.4.0
    MarkupSafe==0.23
    matplotlib==1.4.3
    mistune==0.5.1
    mock==1.0.1
    nose==1.3.4
    numpy==1.9.2
    numpydoc==0.5
    pandas==0.16.0
    plotly==1.6.13
    psycopg2==2.6
    ptyprocess==0.4
    Pygments==2.0.2
    pyparsing==2.0.3
    python-dateutil==2.4.1
    pytz==2015.2
    pyzmq==14.5.0
    requests==2.6.0
    rodeo==0.2.1
    six==1.9.0
    snowballstemmer==1.2.0
    Sphinx==1.3.1
    sphinx-rtd-theme==0.1.7
    terminado==0.5
    tornado==4.1
    vincent==0.4.4
    Werkzeug==0.10.4

I run some SQL against postgresql that populates two dataframes. I can view each one successfully once. After the first view, if I click view again, the view stops at *fetching data*. There are no exceptions in the terminal. The dataframe display just freezes forever at *fetching data* with a spinning chrome circle cursor.

**Comment by glamp** [comment]
my guess is your query returned "too many" rows. this should get fixed once https://github.com/yhat/rodeo/issues/95 is implemented
