### ISSUE TITLE
New Update 2.5.1 on Windows 7 64 bit not working correctly

### ISSUE THREAD

**Issue by prayer007** [yhat/rodeo#566]
Today Rodeo got automatically updated, though all have been working like it should and i dont wanted to update it ! Now, with the new update, thats only a buggy IDE. It isnt possible to run the script neither with the shortcuts nor with the button "Run Script". If you press "Run scirpt" only "Unable to excute" appears in the terminal. With ALT + SHIFT + ENTER nothing happens. Same for "run line". In the Termin the ENTER button isnt working, so the program is totally useless after the latest update. 

How to disable the automatic update ?

p.s Rodeo i such a great think with a lot of potential ! But every update i am afraid that another important thing isnt working properly. 

greeZ

**Comment by TakenPilot** [comment]
Oh no!  That's the _worst_ thing to hear after pushing a release.  : (

I'll remove the update right away.

**Comment by prayer007** [comment]
Now i am working with 2.4.10, which works great ! But I think if the new update works properly, it will be a nice success :)

**Comment by TakenPilot** [comment]
Thanks!  It has a huge number of changes that would be so nice, like a significantly shorter startup time, and saving application state (like the files you had open) between closing and opening Rodeo.  But... the risk is that a lot of stuff changed on the inside.

I guess the risk was a bit too high...

**Comment by TakenPilot** [comment]
Which version of Python are you working with?  Are you using tensorflow?

**Comment by prayer007** [comment]
I am using _Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32_

**Here goes the rodeo.log:**

2016-12-20T16:50:53.736Z - info: node\services\installer\index:: squirrel saw { activeCommand: undefined,
  passiveCommand: undefined,
  execPath: 'C:\\Users\\prayer\\AppData\\Local\\rodeo\\app-2.5.1\\Rodeo.exe',
  systemRoot: 'C:\\Windows' }
2016-12-20T16:50:53.739Z - info: node\index:: { action: 'started',
  argv: 
   { _: {},
     dev: false,
     startup: true,
     h: false,
     help: false,
     version: false,
     '$0': 'Rodeo.exe' },
  'process.argv': { '0': 'C:\\Users\\prayer\\AppData\\Local\\rodeo\\app-2.5.1\\Rodeo.exe' },
  cwd: 'C:\\Users\\prayer\\AppData\\Local\\rodeo\\app-2.5.1',
  versions: 
   { http_parser: '2.7.0',
     node: '6.5.0',
     v8: '5.3.332.47',
     uv: '1.9.1',
     zlib: '1.2.8',
     ares: '1.10.1-DEV',
     modules: '50',
     openssl: '1.0.2h',
     electron: '1.4.10',
     chrome: '53.0.2785.143',
     'atom-shell': '1.4.10' },
  resourcesPath: 'C:\\Users\\prayer\\AppData\\Local\\rodeo\\app-2.5.1\\resources',
  isActiveSquirrelCommand: false }
2016-12-20T16:50:53.758Z - info: node\index:: will-finish-launching
2016-12-20T16:50:53.759Z - info: node\index:: startMainWindow
2016-12-20T16:50:53.794Z - info: node\index:: serving plots from port 8662
2016-12-20T16:50:53.795Z - info: node\index:: attachIpcMainEvents
2016-12-20T16:50:54.659Z - info: node\services\updater:: checking for updates for 2.5.1
2016-12-20T16:50:54.661Z - info: node\services\updater:: check for update at http://bareback.s.yhat.com/update/win32/2.5.1
2016-12-20T16:50:54.675Z - info: node\index:: Getting Environment Variables
2016-12-20T16:50:54.678Z - info: node\services\env:: Got Environment Variables {
  MY ENVIRONMENT }
2016-12-20T16:50:54.743Z - info: node\index:: creating new python kernel process creating python client
2016-12-20T16:50:54.752Z - info: node\services\processes:: added child process { pid: 7448,
  cmd: 'python',
  args: 
   { '0': '-c',
     '1': 'import os\nimport sys\nimport json\nimport pprint as pp\nimport threading\nfrom datetime import datetime\nfrom collections import OrderedDict\n\n# start compatibility with IPython Jupyter 4.0\ntry:\n    from jupyter_client import manager\nexcept ImportError:\n    try:\n        from IPython.kernel import manager\n    except ImportError:\n        raise Exception(\'Jupyter is not installed\')\n\ntry:\n    import pip\nexcept:\n    raise Exception(\'Pip is not installed\')\n\ntry:\n    import numpy\nexcept:\n    raise Exception(\'Numpy is not installed\')\n\ntry:\n    import pandas\nexcept:\n    raise Exception(\'Pandas is not installed\')\n\ntry:\n    import matplotlib\nexcept:\n    raise Exception(\'Matplotlib is not installed\')\n\n# python3/python2 nonsense\ntry:\n    from Queue import Empty\n    import Queue\nexcept:\n    from queue import Empty\n    import queue as Queue\n\ndef json_serial(obj):\n    """JSON serializer for objects not serializable by default json code"""\n\n    if isinstance(obj, datetime):\n        serial = obj.isoformat()\n        return serial\n    raise TypeError ("Type not serializable")\n\ndef add_input(input_queue):\n    while True:\n        input_queue.put(sys.stdin.readline())\n\ndef kernel(wd=None, verbose=0):\n    # setup ipython kernel and configure it\n    kernel_manager, kernel_client = manager.start_new_kernel(extra_arguments=["--matplotlib=\'inline\'"])\n    current_timeout_min = 0.0005\n    current_timeout_max = 0.01\n    current_timeout = current_timeout_max\n\n    acceptable_types = [\n      "execute_input",\n      "stream",\n      "display_data",\n      "error",\n      "execute_result",\n      "execute_reply",\n      "complete_reply"\n    ]\n\n    input_queue = Queue.Queue()\n\n    input_thread = threading.Thread(target=add_input, args=(input_queue,))\n    input_thread.daemon = True\n    input_thread.start()\n\n    # we\'re up and running!\n    sys.stdout.write(json.dumps({ "id": "startup-complete", "status": "complete" }) + "\\n")\n\n    should_continue = True\n    while should_continue:\n        if not input_queue.empty():\n            current_timeout = current_timeout_min\n            line = input_queue.get().strip()\n            payload = json.loads(line)\n            uid = payload["id"]\n            args = payload.get("args", [])\n            kwargs = payload.get("kwargs", {})\n            method = payload.get("method", False)\n            target_str = payload.get("target", "client")\n            exec_eval = payload.get("exec_eval", False)\n\n            if target_str == "manager":\n              target = kernel_manager\n            else:\n              target = kernel_client\n\n            if method:\n                if getattr(target, method, False):\n                    result = getattr(target, method)(*args, **kwargs)\n                    if result:\n                        sys.stdout.write(json.dumps({"source": "link", "result": result, "id": uid }) + \'\\n\')\n                else:\n                    sys.stdout.write(json.dumps({ "error": "Missing method " + method, "id": uid }) + \'\\n\')\n\n            if exec_eval:\n                result = eval(exec_eval)\n                sys.stdout.write(json.dumps({ "source": "eval", "result": result, "id": uid }) + \'\\n\')\n\n        try:\n            data = kernel_client.get_shell_msg(timeout=current_timeout)\n\n            content = data.get(\'content\', False)\n\n            if content:\n                payload = content.get(\'payload\', False)\n                if payload:\n                    try:\n                        first = payload[0]\n                        if first:\n                            source = first.get(\'source\', False)\n                            keepkernel = first.get(\'keepkernel\', False)\n                            if source == \'ask_exit\' and keepkernel == False:\n                                should_continue = False\n                    except IndexError:\n                        pass\n                msg_type = data.get(\'msg_type\', False)\n                if msg_type == \'shutdown_reply\':\n                    shutdown_restart = content.get(\'restart\', False)\n                    if not shutdown_restart:\n                        should_continue = False\n            sys.stdout.write(json.dumps({"source": "shell", "result": data, "should_continue": should_continue}, default=json_serial) + \'\\n\')\n            current_timeout = current_timeout_min\n        except Empty:\n            pass\n\n        try:\n            while True:\n                data = kernel_client.get_iopub_msg(timeout=current_timeout)\n                sys.stdout.write(json.dumps({"source": "iopub", "result": data}, default=json_serial) + \'\\n\')\n                sys.stdout.flush()\n                current_timeout = current_timeout_min\n        except Empty:\n            pass\n\n        try:\n            data = kernel_client.get_stdin_msg(timeout=current_timeout)\n            sys.stdout.write(json.dumps({"source": "stdin", "result": data}, default=json_serial) + \'\\n\')\n            sys.stdout.flush()\n            current_timeout = current_timeout_min\n        except Empty:\n            pass\n\n        current_timeout = min(current_timeout * 1.1, current_timeout_max)\n\nif __name__=="__main__":\n    wd = None\n    if len(sys.argv) > 1:\n        wd = sys.argv[1]\n    kernel(wd, verbose=2)\n',
     '2': 'python3' },
  options: 
   { cwd: 'H:\\Programs\\XAMPP\\htdocs\\masterthesis_climate_geography\\snowmodel\\python',
     env: 
      { MY ENVIRONMENT },
     stdio: { '0': 'pipe', '1': 'pipe', '2': 'pipe' },
     encoding: 'UTF8' } } ; 1 children running
2016-12-20T16:50:54.754Z - info: node\index:: created new python kernel process ciwxqyk5z000080owzhnzlfcg process 7448 { cmd: 'python',
  cwd: 'H:\\Programs\\XAMPP\\htdocs\\masterthesis_climate_geography\\snowmodel\\python',
  kernelName: 'python3' }
2016-12-20T16:50:54.770Z - info: node\index:: python kernel process event ciwxqyk5z000080owzhnzlfcg process 7448 { cmd: 'python',
  cwd: 'H:\\Programs\\XAMPP\\htdocs\\masterthesis_climate_geography\\snowmodel\\python',
  kernelName: 'python3' } { source: 'stderr.data',
  data: '  File "C:\\Users\\prayer\\AppData\\Local\\rodeo\\app-2.5.1\\resources\\conda\\Lib\\site.py", line 176\r\n    file=sys.stderr)\r\n        ^\r\nSyntaxError: invalid syntax\r\n' }
2016-12-20T16:50:54.773Z - info: node\services\processes:: removed child process { pid: 7448,
  code: 1,
  signal: null,
  errors: {},
  cmd: 'python',
  args: 
   { '0': '-c',
     '1': 'import os\nimport sys\nimport json\nimport pprint as pp\nimport threading\nfrom datetime import datetime\nfrom collections import OrderedDict\n\n# start compatibility with IPython Jupyter 4.0\ntry:\n    from jupyter_client import manager\nexcept ImportError:\n    try:\n        from IPython.kernel import manager\n    except ImportError:\n        raise Exception(\'Jupyter is not installed\')\n\ntry:\n    import pip\nexcept:\n    raise Exception(\'Pip is not installed\')\n\ntry:\n    import numpy\nexcept:\n    raise Exception(\'Numpy is not installed\')\n\ntry:\n    import pandas\nexcept:\n    raise Exception(\'Pandas is not installed\')\n\ntry:\n    import matplotlib\nexcept:\n    raise Exception(\'Matplotlib is not installed\')\n\n# python3/python2 nonsense\ntry:\n    from Queue import Empty\n    import Queue\nexcept:\n    from queue import Empty\n    import queue as Queue\n\ndef json_serial(obj):\n    """JSON serializer for objects not serializable by default json code"""\n\n    if isinstance(obj, datetime):\n        serial = obj.isoformat()\n        return serial\n    raise TypeError ("Type not serializable")\n\ndef add_input(input_queue):\n    while True:\n        input_queue.put(sys.stdin.readline())\n\ndef kernel(wd=None, verbose=0):\n    # setup ipython kernel and configure it\n    kernel_manager, kernel_client = manager.start_new_kernel(extra_arguments=["--matplotlib=\'inline\'"])\n    current_timeout_min = 0.0005\n    current_timeout_max = 0.01\n    current_timeout = current_timeout_max\n\n    acceptable_types = [\n      "execute_input",\n      "stream",\n      "display_data",\n      "error",\n      "execute_result",\n      "execute_reply",\n      "complete_reply"\n    ]\n\n    input_queue = Queue.Queue()\n\n    input_thread = threading.Thread(target=add_input, args=(input_queue,))\n    input_thread.daemon = True\n    input_thread.start()\n\n    # we\'re up and running!\n    sys.stdout.write(json.dumps({ "id": "startup-complete", "status": "complete" }) + "\\n")\n\n    should_continue = True\n    while should_continue:\n        if not input_queue.empty():\n            current_timeout = current_timeout_min\n            line = input_queue.get().strip()\n            payload = json.loads(line)\n            uid = payload["id"]\n            args = payload.get("args", [])\n            kwargs = payload.get("kwargs", {})\n            method = payload.get("method", False)\n            target_str = payload.get("target", "client")\n            exec_eval = payload.get("exec_eval", False)\n\n            if target_str == "manager":\n              target = kernel_manager\n            else:\n              target = kernel_client\n\n            if method:\n                if getattr(target, method, False):\n                    result = getattr(target, method)(*args, **kwargs)\n                    if result:\n                        sys.stdout.write(json.dumps({"source": "link", "result": result, "id": uid }) + \'\\n\')\n                else:\n                    sys.stdout.write(json.dumps({ "error": "Missing method " + method, "id": uid }) + \'\\n\')\n\n            if exec_eval:\n                result = eval(exec_eval)\n                sys.stdout.write(json.dumps({ "source": "eval", "result": result, "id": uid }) + \'\\n\')\n\n        try:\n            data = kernel_client.get_shell_msg(timeout=current_timeout)\n\n            content = data.get(\'content\', False)\n\n            if content:\n                payload = content.get(\'payload\', False)\n                if payload:\n                    try:\n                        first = payload[0]\n                        if first:\n                            source = first.get(\'source\', False)\n                            keepkernel = first.get(\'keepkernel\', False)\n                            if source == \'ask_exit\' and keepkernel == False:\n                                should_continue = False\n                    except IndexError:\n                        pass\n                msg_type = data.get(\'msg_type\', False)\n                if msg_type == \'shutdown_reply\':\n                    shutdown_restart = content.get(\'restart\', False)\n                    if not shutdown_restart:\n                        should_continue = False\n            sys.stdout.write(json.dumps({"source": "shell", "result": data, "should_continue": should_continue}, default=json_serial) + \'\\n\')\n            current_timeout = current_timeout_min\n        except Empty:\n            pass\n\n        try:\n            while True:\n                data = kernel_client.get_iopub_msg(timeout=current_timeout)\n                sys.stdout.write(json.dumps({"source": "iopub", "result": data}, default=json_serial) + \'\\n\')\n                sys.stdout.flush()\n                current_timeout = current_timeout_min\n        except Empty:\n            pass\n\n        try:\n            data = kernel_client.get_stdin_msg(timeout=current_timeout)\n            sys.stdout.write(json.dumps({"source": "stdin", "result": data}, default=json_serial) + \'\\n\')\n            sys.stdout.flush()\n            current_timeout = current_timeout_min\n        except Empty:\n            pass\n\n        current_timeout = min(current_timeout * 1.1, current_timeout_max)\n\nif __name__=="__main__":\n    wd = None\n    if len(sys.argv) > 1:\n        wd = sys.argv[1]\n    kernel(wd, verbose=2)\n',
     '2': 'python3' },
  options: 
   { cwd: 'H:\\Programs\\XAMPP\\htdocs\\masterthesis_climate_geography\\snowmodel\\python',
     env: 
      { MY ENVIRONMENT },
     stdio: { '0': 'pipe', '1': 'pipe', '2': 'pipe' },
     encoding: 'UTF8' } } ; 0 children running
2016-12-20T16:50:54.773Z - info: node\index:: python kernel process closed ciwxqyk5z000080owzhnzlfcg process 7448 { cmd: 'python',
  cwd: 'H:\\Programs\\XAMPP\\htdocs\\masterthesis_climate_geography\\snowmodel\\python',
  kernelName: 'python3' } { code: 1, signal: null }
2016-12-20T16:50:54.802Z - info: node\services\browser-windows:: ipc ciwxqyk6v000180owwmb1vsfu: close completed 27ms
2016-12-20T16:50:54.804Z - info: node\services\browser-windows:: did-finish-load mainWindow
2016-12-20T16:50:54.849Z - info: node\services\files:: startWatching file-viewer C:\Users\prayer\*
2016-12-20T16:50:56.044Z - info: node\services\browser-windows:: app-command mainWindow unknown
2016-12-20T16:50:56.174Z - info: node\services\updater:: dispatch { type: 'AUTO_UPDATE_ERROR',
  data: 'Command failed: 4294967295\nSystem.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Net.WebException: Der Remoteserver hat einen Fehler zur�ckgegeben: (500) Interner Serverfehler.\r\n   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.Update.Program.<Download>d__7.MoveNext()\r\n   --- Ende der internen Ausnahmestapel�berwachung ---\r\n   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   bei System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   bei System.Threading.Tasks.Task`1.get_Result()\r\n   bei Squirrel.Update.Program.executeCommandLine(String[] args)\r\n   bei Squirrel.Update.Program.main(String[] args)\r\n   bei Squirrel.Update.Program.Main(String[] args)\r\n---> (Interne Ausnahme #0) System.Net.WebException: Der Remoteserver hat einen Fehler zur�ckgegeben: (500) Interner Serverfehler.\r\n   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()\r\n--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Squirrel.Update.Program.<Download>d__7.MoveNext()<---\r\n\r\n' }
2016-12-20T16:50:56.178Z - info: node\services\browser-windows:: ipc ciwxqyl9q000280ow1nziaaqp: dispatch completed 3ms
2016-12-20T16:51:14.793Z - info: node\services\browser-windows:: ipc ciwxqyzms000380owtniscuwn: getTabs completed 4ms

**Comment by prayer007** [comment]
2.5.2 works now very well :)
