### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by zach-wildfig** [yhat/rodeo#598]
The sidebar is an eyesore that is distracting at best and criminally bad from a design standpoint. It's a fairly easy and simple fix to have a toggle for the sidebar to go from hide to show in the css. Confirmed working on local build.

**Comment by ben519** [comment]
@zach-wildfig I'm pretty sure calling the sidebar "horrid" and "criminally bad from a design standpoint" isn't the best way to get a positive and quick response from the Rodeo devs, especially considering Rodeo is **_free_**.

With that said, I'm also not a fan of the sidebar.  I'm all for yhat promoting Science Ops and their blog, but I feel like those icons could be put somewhere else (maybe a yhat tab in the bottom right pane?). Sure would be nice to have the extra real estate for coding.
