### ISSUE TITLE
Make brew installable

### ISSUE THREAD

**Issue by glamp** [yhat/rodeo#6]
```
$ brew install rodeo
```

**Comment by DavidLGoldberg** [comment]
I think this might be better suited for cask

**Comment by TakenPilot** [comment]
I agree about cask.

**Comment by glamp** [comment]
I believe somebody already did this....not sure where to find it though 😦

**Comment by chohner** [comment]
`brew cask install rodeo` should work, the corresponding file lives [here](https://github.com/caskroom/homebrew-cask/blob/960ed478f1120006002b38f12347335d70fbad92/Casks/rodeo.rb). Current version is the outdated 2.0.2 but I already submitted a [PR](https://github.com/caskroom/homebrew-cask/pull/22659) for the update to 2.0.5.

**Comment by glamp** [comment]
👍
