### ISSUE TITLE
Data Frames variable window shows nothing

### ISSUE THREAD

**Issue by feliperyan** [yhat/rodeo#60]
Instantiating a data frame via pd.read_csv works fine but data frame variable is not displayed/added to the Data Frames variables window.

**Comment by glamp** [comment]
What version of pandas are you running? Are there errors in the browser console?

**Comment by masnick** [comment]
I have this same problem. I am on pandas 0.16.0. I am getting this JS error in the console:

```
[Error] SyntaxError: JSON Parse error: Unrecognized token '?'
	parse (localhost, line 1192)
	(anonymous function) (localhost, line 1192)
	j (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	x (jquery.min.js, line 4)
	(anonymous function) (jquery.min.js, line 4)
```

The context of the error is this: <https://tmp.m-n.us/pb-NWHLewxUS2-s5B5bAt1Ja>

**Comment by glamp** [comment]
just curious but how big is the DF?

**Comment by masnick** [comment]
@glamp I'm reading in a 10mb Stata file.
```
>>> df.shape
(4619, 124)
```

**Comment by feliperyan** [comment]
I'm reading about 200 rows. Using Python 3.4.3 and Pyvenv on Yosemite.

**Comment by stonebig** [comment]
@feliperyan 

I had the same initial issue I was not registering the dataframe in a variable. 
(a bad Ipython practice, as Ipython displays the last result by default)
==> Did you the same error ?

**Comment by feliperyan** [comment]
@stonebig no I'm definitely doing something like: 
df = pd.read_csv('mycsv.csv')

**Comment by feliperyan** [comment]
@glamp Yes there are errors in the browser: 
![screen shot 2015-05-17 at 4 10 51 pm](https://cloud.githubusercontent.com/assets/1303103/7669289/51f54d4c-fcaf-11e4-9253-4b7128bb9c9c.png)

**Comment by feliperyan** [comment]
@glamp pip3 freeze output
![screen shot 2015-05-17 at 4 12 20 pm](https://cloud.githubusercontent.com/assets/1303103/7669296/8cde61c8-fcaf-11e4-8aa5-f29d29000bbb.png)

**Comment by glamp** [comment]
is this still an issue in the latest release?

**Comment by Teva** [comment]
yes still an issue for me !


<img width="1437" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2189059/10648129/0346a8c6-783d-11e5-8e68-7e671754bb8e.png">

**Comment by glamp** [comment]
can you try w/ v1.0+?

**Comment by spriganalytics01** [comment]
Works perfectly now ! thanks !
<img width="1434" alt="rodeo" src="https://cloud.githubusercontent.com/assets/15729877/11197446/d802be8a-8cbd-11e5-8938-a8246ed3a9ad.png">

**Comment by Teva** [comment]
works perfectly, thanks.

<img width="1434" alt="rodeo" src="https://cloud.githubusercontent.com/assets/2189059/11197607/d884f3ae-8cbe-11e5-94ef-c27c92dfca82.png">
