### ISSUE TITLE
urllib2 (Python 2.7) used in current HEAD (not Python 3.4 compatible)

### ISSUE THREAD

**Issue by ianozsvald** [yhat/rodeo#63]
I just cloned HEAD, upon running with Python 3.4 (Anaconda) I get:
```
$ rodeo .
...
rodeo/rodeo.py", line 6, in <module>
    import urllib2
ImportError: No module named 'urllib2'
```

A trivial fix in `rodeo.py` is:
```
try:
    import urllib2
except ImportError:
    import urllib.request as urllib2
```
but really something like https://pythonhosted.org/six/#module-six.moves.urllib.request makes more sense.

**Comment by glamp** [comment]
removed this code

**Comment by ianozsvald** [comment]
Confirmed working with Python 3.4, thanks :-)
