### ISSUE TITLE
Is this software abandoned? 

### ISSUE THREAD

**Issue by sdrygalski** [yhat/rodeo#631]
No commits since January.

**Comment by funkindy** [comment]
I double the question.

**Comment by ghost** [comment]
It seems they (yhat) been acquired by some other company. I suppose this is dead.

**Comment by andrewl786** [comment]
I'd like to know if there are any updates being planned

**Comment by IOpsycode** [comment]
Welp, looks like we're going to Spyder. Too bad, I liked Rodeo

**Comment by d4tum** [comment]
Yes, I'd like to know too.
I've been getting friendly with Spyder since the day Rodeo was acquired by Alteryx.
Would be good to have a yhat person chime in on the future of Rodeo...

**Comment by TheTS** [comment]
An official update would be nice! I'm reluctant to make this my primary IDE if it's just abandonware.

**Comment by jonoleson** [comment]
I would like to pile on this existing pile-on. And construct additional pile-ons.

**Comment by toshikb** [comment]
rodeo is a nice IDE. I'd like to use it ongoingly.

**Comment by d4tum** [comment]
@glamp Closed with no resolution?

**Comment by glamp** [comment]
There is nothing to resolve. This isn't an issue.

**Comment by jonoleson** [comment]
But, any answers on the future of Rodeo, or lack thereof?

**Comment by lefft** [comment]
pile on a year later :)

**Comment by treder** [comment]
no answer is an answer?
