### ISSUE TITLE
Rodeo cannot install packages (Windows 7)

### ISSUE THREAD

**Issue by philipkiely** [yhat/rodeo#645]
I'm running rodeo on Windows 7. I'm trying to install statsmodels, which is included with anaconda. I cannot install it, or any package other than pandas and numpy, using any of pip, condas, or the graphical user interface package installer in the packages tab. It does not give any error message, but I simply cannot import the package after running the command to install it.

**Comment by philipkiely** [comment]
Turns out it is actually a permissions issue on my work computer.

**Comment by Rothurford** [comment]
How could you solve that problem when I input "pip install pandas" with a promt like this:
'pip' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���m? I meet the similar questions shows""
