### ISSUE TITLE
Conda environment not loading

### ISSUE THREAD

**Issue by joelrivest** [yhat/rodeo#649]
I'm using Rodeo version 2.5.2 on Windows 7. I've set up the environment in the preferences :
Python Command : C:\Anaconda3\envs\tensorflow\python.exe
but Rodeo is using C:\Anaconda3\

Any help? Thanks

**Comment by DamBarreto** [comment]
Try to use Rodeo version 2.4.10.
I was having the same problem

**Comment by joelrivest** [comment]
I tried Rodeo version 2.4.10 (after uninstalling current version and erasing files in %appdata%), but the problem still there.

**Comment by joelrivest** [comment]
OK, the source of the problem seems to be outside Rodeo, I got the same problem with Spyder within Anaconda Navigator.

**Comment by joelrivest** [comment]
OK, the source of the problem seems to be outside Rodeo, I got the same problem with Spyder within Anaconda Navigator.
