### ISSUE TITLE
Strange syntax error message when trying to view dataframe (Python 3.4 via conda)

### ISSUE THREAD

**Issue by pybokeh** [yhat/rodeo#68]
I've loaded the mtcars data from ggplot and when I go to view the mtcars dataframe, I get a weird, syntax error message:
[1;36m File [1;32m"[1;36m File [1;32m"[1;36m File [1;32m"[1;36m File [1;32m""[1;36m, line [1;32m1[0m [1;33m print mtcars.ix[:5000].to_html()[0m [1;37m ^[0m [1;31mSyntaxError[0m[1;31m:[0m invalid syntax 

I launched a Python 2.7 virtual environment, viewed the dataframe, it works fine.

**Comment by glamp** [comment]
try upgrading to the latest version

**Comment by pybokeh** [comment]
Is latest 0.2.4?  I installed via pip install git+https://github.com/yhat/rodeo.git and still get same problem.

**Comment by pybokeh** [comment]
Didn't think there would be a difference, but I downloaded the source and then build from source, it is ok now.  Thought install from .git file would have done the same, but guess not.
