### ISSUE TITLE
add base_url option

### ISSUE THREAD

**Issue by hsharrison** [yhat/rodeo#69]
I would like to run rodeo at (e.g.) http://localhost:5000/rodeo, in order to facilitate putting it behind a nginx reverse proxy and securing it for WAN access. In IPython this option is called `base_url`.

**Comment by glamp** [comment]
What happens when you try to setup the reverse proxy now? Any idea what base_url is doing?

**Comment by hsharrison** [comment]
I'm not sure how the IPython Notebook implements it, but you're using Flask and I see that there is a `url_prefix` option there. I tried putting together a pull request but I've never used Flask before and it seems to require making use of a "Blueprint", more than just a quick insert of a command-line option I'm afraid.

In any case, it works fine behind a reverse proxy if I put it at `https://server/`. The problem is, then I can have only one application that can only handle being at the root URL.

If I put it at `https://server/rodeo`, it almost works, but many of the features are broken. In the right pane for example, History works and Packages looks correct, but Data Frames, Files, Plots, and Help never update. I'm guessing anything that relies on an internal URL is broken. Using the `url_prefix` option of `flask.Blueprint` should fix all that.

**Comment by glamp** [comment]
> If I put it at https://server/rodeo, it almost works, but many of the features are broken. In the right pane for example, History works and Packages looks correct, but Data Frames, Files, Plots, and Help never update.

I bet it has to do with the ajax requests being routed to the wrong url (namely `/` instead of `/rodeo`).

I've never used blueprint but it seems like what we'd want. If you give it a try I'd be happy to merge it in (assuming it works :smile: ).

**Comment by glamp** [comment]
ok i think i can fix this by just using flask properly

From http://flask.pocoo.org/docs/0.10/quickstart/...

> If your application is placed outside the URL root (say, in /myapplication instead of /), url_for() will handle that properly for you.

**Comment by glamp** [comment]
fixed in 7aea46e408a5340854b0c16ab2ee5cec5b475554

**Comment by hsharrison** [comment]
Awesome! I'll try it out soon.

**Comment by hsharrison** [comment]
Which `slugify` package do I need? I'm finding a few on PyPi, none of them seem to work.

**Comment by glamp** [comment]
sorry this should be fixed in 729d159110fdfd33af1bded56353e02ac6a4e3e9

**Comment by hsharrison** [comment]
you missed one on line 38
