### ISSUE TITLE
Can't save as file in specific directory

### ISSUE THREAD

**Issue by dyngts** [yhat/rodeo#72]
I'm really on the mood with this new IDE, but actually got some basic problem where when i save the file, it will be store on the same directory as i open rodeo. Trying to explicitly define relative path of my prefer directory but still not working. Is it bug or i missing something?

**Comment by glamp** [comment]
This is definitely a bug. Thanks for submitting the issue. Check out the latest release and let me know what you think. I added some support for files in sub-directories.

**Comment by dyngts** [comment]
Hi @glamp,

Thanks for the additional feature when saving to sub-directories. But in my opinion, the save feature still not natural like usual. I mean it seems bleeding for me to manually write down which directory i prefer everytime i like to save. I don't know if this is possible if the behavior is like opening file where you just choose file that you want to open. Thanks

**Comment by glamp** [comment]
fixed in 1.0
