### ISSUE TITLE
DataFrame viewer - perhaps look at qgrid from Quantopian? (feature suggestion, not a bug)

### ISSUE THREAD

**Issue by ianozsvald** [yhat/rodeo#74]
The existing DataFrame viewer is useful but plain. It is great to see all rows in a df but there's no sort or filtering. Quantopian's QGrid includes these (and supports multi-indexes), it embeds in a Notebook to render a javascript view on the DataFrame:
https://github.com/quantopian/qgrid

The demo in this Notebook shows the sorting and interaction:
http://nbviewer.ipython.org/github/quantopian/qgrid/blob/master/qgrid_demo.ipynb

This would add a useful chunk of additional tools to the viewer so I figure it is worth mentioning but since it is designed for a Notebook it might not however be an easy drop-in replacement.

**Comment by tycho01** [comment]
On a similar note, [DataTables](http://www.datatables.net/) would be a similar cool means of rendering tables.

**Comment by glamp** [comment]
good idea. QGrid looks great but the [numpy/pandas](https://github.com/quantopian/qgrid/blob/master/setup.py#L42-L43) dependencies scare me. i know it's not an issue for most people, but i think it's important that things are as easy to install as possible--hence why [there's no pandas here](https://github.com/yhat/rodeo/blob/master/setup.py#L46-L51).

DataTables looks good and seems to be relatively simple. I will give it a shot and let you know if I can get it working.

**Comment by glamp** [comment]
75d45eea1eda34ecf6dd3c632c60518b8979a852
