### ISSUE TITLE
Can't autocomplete for package

### ISSUE THREAD

**Issue by dyngts** [yhat/rodeo#76]
Hi all,

I'm trying to use autocomplete to find out available package, but it's not working. for example, i want to use library pandas. so that i write down like this:

import pan

then, using tab to autocomplete. but it's not working. Is it bug or the feature is still not available?

**Comment by nikhiljjoshi** [comment]
Hi,

Yes, I second that. 
For me, it does show the completion options, but normally when there is a single option, it's better if it actually autocompletes. Instead, it keeps showing autocompletion options (here, as single one). Seems a bug to me.

Great job though :). I am liking it!

**Comment by glamp** [comment]
fixed in 1.0
