### ISSUE TITLE
Tab key and other input behavior is wonky

### ISSUE THREAD

**Issue by hernamesbarbara** [yhat/rodeo#8]
```
x = 10
# x = now hit the tab key
```

Observe the x = text that you've already inputted now indents 5 spaces which is weird behavior.

2. control + k and control + u should use `readlines` style clear behavior to erase to start and end of the line like it does in a normal ipython / bash shell.

NOTE - control + L appears to clear the shell as expected. just k and u that do not work.

3. option + left arrow and option + right arrow should jump between word breaks

4. control + w should erase one word backwards

5. option + backspace should erase one word backwords.

ideally rodeo would look for the users ~/.inputrc file and respect whatever behaviors and keybindings / escape sequences are defined in that file if possible.

**Comment by glamp** [comment]
w, k, and u are done. options are tricky. not sure about those yet.

**Comment by glamp** [comment]
tab now working

**Comment by glamp** [comment]
bc55604c34eb1621be566d4e18ccae0d1c16f4d3
