### ISSUE TITLE
Cannot save file in python3 and answer

### ISSUE THREAD

**Issue by togetherapp** [yhat/rodeo#82]
When I tried to save my working file, the console complained 

"  File "/usr/local/lib/python3.4/site-packages/rodeo/rodeo.py", line 60, in save_file
    f.write(request.form['source'])
TypeError: 'str' does not support the buffer interface"

It works in python2, but in python3 it should change to "f.write(bytes(request.form['source'], "utf8"))".

**Comment by glamp** [comment]
Thanks for catching this

**Comment by glamp** [comment]
https://github.com/yhat/rodeo/pull/81
