### ISSUE TITLE
Interface has a scrollbar in the main window

### ISSUE THREAD

**Issue by rsmith31415** [yhat/rodeo#88]
As I reported previously in #53, the interface is forcing an annoying scrollbar in the window:

![Alt text](https://cloud.githubusercontent.com/assets/599274/7326921/bb96a742-ea8e-11e4-9f85-f1602ef0ffc2.png)

This causes constant jumps when the focus changes to the console.

This happens in Chrome 42 and Firefox 37 on Ubuntu 15.04.

**Comment by glamp** [comment]
is this fixed in latest release?
