### ISSUE TITLE
Update URL address with filename after saving file

### ISSUE THREAD

**Issue by rsmith31415** [yhat/rodeo#89]
As reported in #53, the URL address needs to be updated with the filename after saving a file or  included as localhost:5000/Untitled.txt or something like that for unknown filenames.

![Alt text](https://cloud.githubusercontent.com/assets/599274/7333670/f1d1c6a2-eb3d-11e4-94d7-9363a56b798d.png)

This helps to navigate through files, copy and bookmark links and to provide a history in the browser.

**Comment by glamp** [comment]
> the URL address needs to be updated with the filename after saving a file or included as localhost:5000/Untitled.txt

I don't really understand why this is useful. If you can find other people who want this too then I'll consider it.

**Comment by rsmith31415** [comment]
Maybe I'm not explaining this correctly. 

This is important because URLs should keep the location of a given resource so that users will be able to find it (e.g. opening a file using a link, bookmarks, page suggestions in the URL bar)

It is also important for the application in itself. URLs contain the state of the application so you may want to use the URL to see that something in your application needs to change. Single page applications rely on URLs to change the behavior of the page (inspecting manually the URL or using a router).

Furthermore, applications should avoid breaking basic functionality in the browser. If you don't push the state of you application to the browser history, the back and forward buttons are useless.
