### ISSUE TITLE
New file gets text from already open file and file not saved

### ISSUE THREAD

**Issue by roshannair** [yhat/rodeo#94]
Rodeo 0.3.3 on ubuntu and opera browser on mac. 

I use rodeo in opera on my mac, so I can have a dedicated browser that I can cmd+tab to. I use chrome otherwise. 

I had a python file open and clicked the '+' to create a new file. When I click save as -> xyz.md -> Ok, the text from the first file appears in the second. Subsequently entering text into the first file and saving does not work.

I couldn't reproduce this problem on chrome. For now, I've switched back to chrome.

**Comment by roshannair** [comment]
I notice another issue - this time on Chrome and Safari. Open rodeo in a browser tab. 
1. Open an existing file 'a.py' from the files pane, so you have two tabs Untitled and 'a.py'. 
2. Close Untitled, so you have only 'a.py' open. 
3. Now open another existing file 'b.py' from the files tab. Now if you click back on 'a.py' in the editor pane, the text that shows up in the editor is the contents of 'b.py'. 

This only happens in this particular sequence. Any other sequence of opening files and the editor contents are correct.

**Comment by edoardovivo** [comment]
I have noticed the same issue as the last comment on version 0.4.4.

**Comment by glamp** [comment]
fixed in 2+
